-- Historias: modelo editorial inicial para Supabase/Postgres.
-- Ejecutar desde el editor SQL de un proyecto nuevo de Supabase.

create extension if not exists "pgcrypto";

do $$ begin
  create type public.story_status as enum ('draft', 'in_progress', 'published', 'complete');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.media_status as enum ('pending', 'published', 'archived');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  eyebrow text,
  tagline text,
  synopsis text not null default '',
  author text not null default 'Historias',
  status public.story_status not null default 'draft',
  cover_url text,
  cover_prompt text,
  cover_alt text,
  total_reading_minutes integer not null default 0 check (total_reading_minutes >= 0),
  featured boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique
);

create table if not exists public.story_genres (
  story_id uuid not null references public.stories(id) on delete cascade,
  genre_id bigint not null references public.genres(id) on delete cascade,
  primary key (story_id, genre_id)
);

create table if not exists public.chapters (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references public.stories(id) on delete cascade,
  number integer not null check (number > 0),
  title text not null,
  excerpt text,
  content jsonb not null default '[]'::jsonb,
  reading_minutes integer not null default 1 check (reading_minutes > 0),
  status public.story_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (story_id, number)
);

create table if not exists public.chapter_media (
  id uuid primary key default gen_random_uuid(),
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  sort_order integer not null default 0,
  after_block integer not null default 0 check (after_block >= 0),
  image_url text,
  alt_text text not null default '',
  generation_prompt text,
  aspect_ratio text not null default '16/9',
  status public.media_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists chapters_story_number_idx on public.chapters (story_id, number);
create index if not exists chapter_media_chapter_order_idx on public.chapter_media (chapter_id, sort_order);

insert into public.genres (slug, name)
values
  ('suspense', 'Suspense'),
  ('intriga', 'Intriga'),
  ('aventura', 'Aventura'),
  ('accion', 'Acción'),
  ('ciencia-ficcion', 'Ciencia ficción')
on conflict (slug) do update set name = excluded.name;

alter table public.stories enable row level security;
alter table public.genres enable row level security;
alter table public.story_genres enable row level security;
alter table public.chapters enable row level security;
alter table public.chapter_media enable row level security;

create policy "Public can read published stories" on public.stories for select
  using (status in ('published', 'complete') or auth.role() = 'authenticated');
create policy "Public can read genres" on public.genres for select using (true);
create policy "Public can read story genres" on public.story_genres for select using (true);
create policy "Public can read published chapters" on public.chapters for select
  using (status in ('published', 'complete') or auth.role() = 'authenticated');
create policy "Public can read published chapter media" on public.chapter_media for select
  using (status = 'published' or auth.role() = 'authenticated');

create policy "Authenticated users can manage stories" on public.stories for all to authenticated
  using (true) with check (true);
create policy "Authenticated users can manage genres" on public.genres for all to authenticated
  using (true) with check (true);
create policy "Authenticated users can manage story genres" on public.story_genres for all to authenticated
  using (true) with check (true);
create policy "Authenticated users can manage chapters" on public.chapters for all to authenticated
  using (true) with check (true);
create policy "Authenticated users can manage chapter media" on public.chapter_media for all to authenticated
  using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('story-media', 'story-media', true)
on conflict (id) do update set public = excluded.public;

create policy "Public can view story media" on storage.objects for select
  using (bucket_id = 'story-media');
create policy "Authenticated users can upload story media" on storage.objects for insert to authenticated
  with check (bucket_id = 'story-media');
create policy "Authenticated users can update story media" on storage.objects for update to authenticated
  using (bucket_id = 'story-media') with check (bucket_id = 'story-media');
create policy "Authenticated users can delete story media" on storage.objects for delete to authenticated
  using (bucket_id = 'story-media');
