-- Ficción Oculta: esquema editorial, autenticación y almacenamiento.
-- Puede ejecutarse más de una vez desde el SQL Editor de Supabase.

create extension if not exists "pgcrypto";

do $$ begin
  create type public.story_status as enum ('draft', 'in_progress', 'published', 'complete');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.media_status as enum ('pending', 'published', 'archived');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  eyebrow text,
  tagline text,
  synopsis text not null default '',
  author text not null default 'Ficción Oculta',
  status public.story_status not null default 'draft',
  year integer not null default extract(year from current_date)::integer,
  cover_url text,
  cover_prompt text,
  cover_alt text,
  cover_variant text not null default 'signal',
  cover_accent text not null default '#f1b75a',
  cover_ink text not null default '#071319',
  cover_code text not null default 'FO-01',
  total_reading_minutes integer not null default 0 check (total_reading_minutes >= 0),
  featured boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stories add column if not exists year integer not null default extract(year from current_date)::integer;
alter table public.stories add column if not exists cover_variant text not null default 'signal';
alter table public.stories add column if not exists cover_accent text not null default '#f1b75a';
alter table public.stories add column if not exists cover_ink text not null default '#071319';
alter table public.stories add column if not exists cover_code text not null default 'FO-01';
alter table public.stories alter column author set default 'Ficción Oculta';

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique
);

create table if not exists public.story_genres (
  story_id uuid not null references public.stories(id) on delete cascade,
  genre_id bigint not null references public.genres(id) on delete cascade,
  primary key (story_id, genre_id)
);

create table if not exists public.chapters (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references public.stories(id) on delete cascade,
  number integer not null check (number > 0),
  title text not null,
  excerpt text,
  content jsonb not null default '[]'::jsonb,
  reading_minutes integer not null default 1 check (reading_minutes > 0),
  status public.story_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (story_id, number)
);

create table if not exists public.chapter_media (
  id uuid primary key default gen_random_uuid(),
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  sort_order integer not null default 0,
  after_block integer not null default 0 check (after_block >= 0),
  image_url text,
  alt_text text not null default '',
  generation_prompt text,
  aspect_ratio text not null default '16/9',
  status public.media_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists chapters_story_number_idx on public.chapters (story_id, number);
create index if not exists chapter_media_chapter_order_idx on public.chapter_media (chapter_id, sort_order);

insert into public.genres (slug, name)
values
  ('suspense', 'Suspense'),
  ('intriga', 'Intriga'),
  ('aventura', 'Aventura'),
  ('accion', 'Acción'),
  ('ciencia-ficcion', 'Ciencia ficción')
on conflict (slug) do update set name = excluded.name;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();
drop trigger if exists stories_set_updated_at on public.stories;
create trigger stories_set_updated_at before update on public.stories
for each row execute procedure public.set_updated_at();
drop trigger if exists chapters_set_updated_at on public.chapters;
create trigger chapters_set_updated_at before update on public.chapters
for each row execute procedure public.set_updated_at();
drop trigger if exists chapter_media_set_updated_at on public.chapter_media;
create trigger chapter_media_set_updated_at before update on public.chapter_media
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select is_admin from public.profiles where id = (select auth.uid())),
    false
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.stories enable row level security;
alter table public.genres enable row level security;
alter table public.story_genres enable row level security;
alter table public.chapters enable row level security;
alter table public.chapter_media enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Public can read published stories" on public.stories;
drop policy if exists "Public can read genres" on public.genres;
drop policy if exists "Public can read story genres" on public.story_genres;
drop policy if exists "Public can read published chapters" on public.chapters;
drop policy if exists "Public can read published chapter media" on public.chapter_media;
drop policy if exists "Authenticated users can manage stories" on public.stories;
drop policy if exists "Authenticated users can manage genres" on public.genres;
drop policy if exists "Authenticated users can manage story genres" on public.story_genres;
drop policy if exists "Authenticated users can manage chapters" on public.chapters;
drop policy if exists "Authenticated users can manage chapter media" on public.chapter_media;
drop policy if exists "Admins can manage stories" on public.stories;
drop policy if exists "Admins can manage genres" on public.genres;
drop policy if exists "Admins can manage story genres" on public.story_genres;
drop policy if exists "Admins can manage chapters" on public.chapters;
drop policy if exists "Admins can manage chapter media" on public.chapter_media;

create policy "Users can read own profile" on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

create policy "Public can read published stories" on public.stories for select
  using (status in ('in_progress', 'published', 'complete'));
create policy "Public can read genres" on public.genres for select using (true);
create policy "Public can read story genres" on public.story_genres for select
  using (
    exists (
      select 1 from public.stories
      where stories.id = story_genres.story_id
        and stories.status in ('in_progress', 'published', 'complete')
    )
    or (select public.is_admin())
  );
create policy "Public can read published chapters" on public.chapters for select
  using (
    exists (
      select 1 from public.stories
      where stories.id = chapters.story_id
        and stories.status in ('in_progress', 'published', 'complete')
    )
    or (select public.is_admin())
  );
create policy "Public can read published chapter media" on public.chapter_media for select
  using (
    exists (
      select 1
      from public.chapters
      join public.stories on stories.id = chapters.story_id
      where chapters.id = chapter_media.chapter_id
        and stories.status in ('in_progress', 'published', 'complete')
        and chapter_media.status = 'published'
    )
    or (select public.is_admin())
  );

create policy "Admins can manage stories" on public.stories for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can manage genres" on public.genres for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can manage story genres" on public.story_genres for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can manage chapters" on public.chapters for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can manage chapter media" on public.chapter_media for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'story-media',
  'story-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view story media" on storage.objects;
drop policy if exists "Authenticated users can upload story media" on storage.objects;
drop policy if exists "Authenticated users can update story media" on storage.objects;
drop policy if exists "Authenticated users can delete story media" on storage.objects;
drop policy if exists "Admins can upload story media" on storage.objects;
drop policy if exists "Admins can update story media" on storage.objects;
drop policy if exists "Admins can delete story media" on storage.objects;

create policy "Public can view story media" on storage.objects for select
  using (bucket_id = 'story-media');
create policy "Admins can upload story media" on storage.objects for insert to authenticated
  with check (bucket_id = 'story-media' and (select public.is_admin()));
create policy "Admins can update story media" on storage.objects for update to authenticated
  using (bucket_id = 'story-media' and (select public.is_admin()))
  with check (bucket_id = 'story-media' and (select public.is_admin()));
create policy "Admins can delete story media" on storage.objects for delete to authenticated
  using (bucket_id = 'story-media' and (select public.is_admin()));

-- Después de crear el usuario administrador en Authentication > Users,
-- sustituye el correo y ejecuta únicamente esta sentencia:
-- update public.profiles set is_admin = true where email = 'tu-correo@ejemplo.com';
