import type { Chapter } from "@/lib/types";

interface LighthouseChapterDraft {
  title: string;
  paragraphs: string[];
  visual: string;
}

const lighthouseChapterDrafts: LighthouseChapterDraft[] = [
  {
    title: "La luz en la niebla",
    visual:
      "Barco oceanográfico pequeño frente a un faro de piedra negra que emerge de una niebla nocturna, un sendero de luz blanca sobre el mar y rocas imposibles alrededor de la proa, suspense marítimo realista, iluminación cinematográfica, sin texto",
    paragraphs: [
      "El mar estaba en calma cuando una luz blanca cortó la niebla por primera vez.",
      "No fue el destello intermitente de una baliza ni el barrido circular de un faro costero. Aquel haz permaneció inmóvil sobre el agua, formando un sendero pálido que parecía comenzar bajo la proa del Argos y prolongarse hasta un punto imposible del horizonte.",
      "Mara Vidal apartó los ojos del monitor cartográfico. —Gael, ¿qué faro hay al oeste? El capitán no respondió de inmediato. Inclinado sobre el timón, comparaba la brújula magnética con el rumbo indicado por el sistema de navegación. —Ninguno. —Pues alguien acaba de encender uno.",
      "El Argos era un antiguo barco de salvamento convertido en embarcación oceanográfica: catorce metros de acero, dos motores diésel y más reparaciones que piezas originales. Mara lo había alquilado para investigar una anomalía detectada a treinta millas de la costa de Cádiz, una elevación submarina que aparecía en los sondeos antiguos y desaparecía en los modernos.",
      "Gael Ríos había aceptado el trabajo con una condición: regresar antes del anochecer. El sol llevaba oculto más de una hora.",
      "Desde la mesa de radio, Inés Oria ajustó los auriculares. —Estoy recibiendo una señal. —¿De Salvamento? —No. Es onda media. Muy débil. Entre los chasquidos de la estática surgieron tres notas de piano, la voz lejana de un locutor y una secuencia de golpes cortos y largos.",
      "Inés tomó un lápiz y comenzó a traducir el código Morse. —Esto no tiene sentido. —¿Qué dice? La joven dejó de escribir. Miró a Mara y después a Gael. —«Vidal. No sigas la luz».",
      "El apellido quedó suspendido en el puente. Gael redujo la velocidad. —Damos la vuelta. Mara lo sujetó por el brazo. —Mi padre desapareció buscando estas coordenadas. —Precisamente por eso. —Nunca me dijiste que sabías dónde estaba. —No lo sabía. —Pero reconoces la señal.",
      "Gael mantuvo la vista al frente. En los últimos años había aprendido a ocultar el miedo detrás de un gesto cansado, pero sus nudillos blancos alrededor del timón lo traicionaron. —Reconozco la forma en que empiezan las cosas que terminan mal.",
      "La niebla se abrió. A menos de una milla apareció una torre de piedra negra. Se alzaba sobre un islote estrecho, azotado por olas que el Argos no sentía. Su linterna brillaba a más de cuarenta metros de altura.",
      "Mara buscó la formación en la carta digital. La pantalla mostraba trescientos doce metros de profundidad. —El radar no detecta tierra —dijo Inés. —Yo sí la veo —respondió Mara.",
      "Gael hizo girar el timón, pero el barco no cambió de rumbo. La aguja de la brújula abandonó el norte y apuntó hacia el faro. Entonces el haz de luz se apagó.",
      "Durante unos segundos solo hubo niebla. Cuando volvió a encenderse, unas rocas habían aparecido a ambos lados del Argos, tan cerca del casco que Mara podía distinguir el agua escurriendo por ellas. Ante la proa se extendía un embarcadero. Y al final del muelle esperaba un hombre.",
    ],
  },
  {
    title: "La torre imposible",
    visual:
      "Interior de un faro imposible de 1932, cartas náuticas antiguas en las paredes, una lente blanca y otra de cristal negro, tres exploradores descubren una isla bajo el haz de luz, misterio marítimo cinematográfico",
    paragraphs: [
      "El hombre desapareció antes de que el Argos alcanzara el embarcadero.",
      "Gael dio marcha atrás, pero las rocas cerraban el paso por el que habían entrado. No emergieron del agua. Simplemente estaban allí, formando una ensenada que no podía existir. —Quince minutos —dijo—. Miramos el faro y volvemos al barco.",
      "Mara saltó al muelle sin esperar. La piedra se encontraba cubierta de líquenes, pero los peldaños de la escalera estaban limpios. Alguien los utilizaba con frecuencia. Inés la siguió llevando una radio portátil y una vieja brújula de latón que había pertenecido a su abuela. Gael fue el último en desembarcar.",
      "La puerta del faro no tenía cerradura. Sobre el dintel se leía: FARO DE LA AGUJA. SERVICIO DE SEÑALES MARÍTIMAS. 1932. —No existe ningún Faro de la Aguja —dijo Mara. —Existió un proyecto —respondió Gael—. Los informes oficiales dicen que nunca llegó a construirse.",
      "Dentro olía a parafina, sal y madera húmeda. Una escalera de caracol ascendía alrededor de un hueco central. En las paredes colgaban cartas náuticas deformadas por la humedad. Algunas mostraban islas sin nombre; otras, grandes espacios de océano atravesados por líneas rojas.",
      "Inés se detuvo ante un mapa del golfo de Cádiz. —Aquí estamos nosotros. Un alfiler negro señalaba su posición. Junto a él aparecía dibujada una isla alargada que no figuraba en la carta del Argos.",
      "Debajo había una anotación escrita con tinta azul: «Primera noche: Cárdena. Segunda noche: La Ceniza. Tercera noche: Isla Baja. No permitir dos barcos en la ruta».",
      "Mara reconoció inmediatamente la letra. —Es de mi padre. Tomás Vidal había sido hidrógrafo antes de dedicarse a cartografiar pecios y fondos marinos. Dieciocho años atrás salió de Barbate a bordo de una embarcación alquilada. Nunca regresó. Solo encontraron una boya, dos bidones vacíos y un fragmento del casco.",
      "Mara pasó los dedos sobre la tinta. Parecía recién trazada. —Esto se ha escrito hace poco. Gael retrocedió hacia la puerta. —Tenemos que volver al barco. —¿Estabas con él? El capitán bajó la mirada.",
      "En ese momento, la brújula de Inés comenzó a girar. La aguja dio tres vueltas y se detuvo apuntando hacia la escalera. Desde la parte superior llegaron tres golpes metálicos.",
      "Subieron. La sala de la linterna ocupaba toda la planta superior. En el centro se alzaba una lente de cristal de más de dos metros, sostenida por engranajes de cobre. No había bombillas ni cables. En su interior ardía una llama blanca que no desprendía calor.",
      "Mara descubrió una segunda lámpara detrás de la lente. Era más pequeña y estaba fabricada con un cristal oscuro, casi negro. En la base alguien había grabado una advertencia: «Toda luz proyecta una sombra».",
      "La maquinaria comenzó a moverse. El haz blanco barrió el mar hasta detenerse en el horizonte. Bajo su resplandor apareció una isla cubierta de casas: primero los tejados, después un campanario y finalmente un puerto entero sobre las aguas.",
      "Desde algún lugar de la isla sonó una campana. Gael contó los tañidos. —Siete. Igual que entonces. La radio de Inés cobró vida. Entre la estática apareció la voz de Tomás Vidal. —Mara, si estás escuchando esto, no vengas a buscarme.",
    ],
  },
  {
    title: "La isla de las casas abiertas",
    visual:
      "Pueblo insular abandonado de 1958 con mesas preparadas, puertas abiertas y relojes girando hacia atrás, tres navegantes corren hacia un puerto que desaparece bajo la niebla, aventura sobrenatural realista",
    paragraphs: [
      "La transmisión duró cuatro segundos. Inés intentó recuperar la frecuencia, pero solo encontró estática. Mara pidió que reprodujera el mensaje una segunda vez. No había duda. Era la voz de su padre.",
      "—Vamos a esa isla —dijo. —No sabemos qué es —respondió Gael. —Sabemos que él estuvo allí. —Y sabemos que no quería que lo siguieras. Mara descendió las escaleras sin discutir.",
      "Cuando llegaron al muelle, el haz del faro formaba un corredor de luz sobre el agua. Al otro extremo se distinguía el puerto de la isla. El motor del Argos arrancó a la primera. Gael mantuvo las manos inmóviles sobre el timón hasta que Mara se situó a su lado. —Puedes quedarte —le dijo ella. —Tu padre me dijo lo mismo. Empujó la palanca de potencia.",
      "La travesía no duró más de diez minutos. Sin embargo, durante ese tiempo desaparecieron las estrellas y el agua se volvió lisa como una lámina de vidrio. A ambos lados del corredor luminoso se movían sombras de barcos que no estaban allí.",
      "El puerto de Cárdena olía a pan recién hecho. Las amarras colgaban de los noráis y varias barcas se mecían junto al muelle. En la plaza había mesas preparadas para una celebración. Los platos conservaban restos de comida y de una ventana abierta llegaba el sonido de una radio. No vieron a ninguna persona.",
      "En el ayuntamiento encontraron un calendario detenido en agosto de 1958. Los relojes marcaban horas diferentes, aunque todos sus segunderos giraban hacia atrás. —Cárdena —recordó Inés—. Mi abuela hablaba de este lugar. Decía que el mar se lo había tragado.",
      "Gael examinó las fotografías colgadas en la pared. Una mostraba a los habitantes reunidos frente al puerto. En el reverso figuraba una fecha: 11 de agosto de 1958. Al fondo de la imagen había un hombre que no pertenecía a aquella época. Tomás Vidal miraba a la cámara con la misma chaqueta que llevaba el día de su desaparición.",
      "Unos pasos sonaron en el piso superior. Allí encontraron una habitación convertida en dormitorio. Sobre la cama descansaba una mochila moderna. Dentro había alimentos caducados en 2009, una linterna, una navaja y un cuaderno protegido por una funda de plástico.",
      "La primera página estaba escrita por Tomás: «Cárdena no se hundió. Fue apartada. El faro conserva lugares que alguien quiso borrar. Aquí han pasado trescientos doce días. Fuera, quizá ninguno». Más abajo había una frase dirigida a Gael: «Si has regresado, cuéntale la verdad a Mara».",
      "Un portazo resonó en la calle. Todas las puertas de las casas se cerraban al mismo tiempo. Los postigos golpeaban las fachadas y las luces se apagaban una tras otra. En el campanario comenzó a sonar la campana. —La ruta se está cerrando —dijo Gael.",
      "Corrieron hacia el puerto. A mitad de la plaza, Mara vio a una niña bajo los soportales. Vestía un abrigo rojo y sostenía una lámpara de aceite. —¡Esperad! —gritó—. ¡Tomás sigue en la tercera isla! La niña levantó el rostro. Tenía los mismos ojos que Inés.",
      "—Abuela… —susurró la joven. Inés dio un paso hacia ella, pero la brújula de latón ardió en su mano. La niña se fragmentó en bandas de luz, como una transmisión mal sintonizada. No había estado realmente en la plaza.",
      "La última campanada sacudió Cárdena. El puerto comenzó a desaparecer.",
    ],
  },
  {
    title: "Cuarenta y siete minutos",
    visual:
      "Farero de edad indescifrable con lámpara de aceite frente a tres navegantes en un muelle nocturno, detrás un gran buque moderno se acerca al faro imposible, tensión cinematográfica marítima",
    paragraphs: [
      "El Argos abandonó Cárdena mientras las casas se disolvían en la niebla.",
      "Durante unos instantes, la mitad del barco quedó dentro del corredor luminoso y la otra mitad en completa oscuridad. El casco crujió como si dos corrientes opuestas intentaran partirlo. Gael aceleró hasta que el motor comenzó a expulsar humo negro.",
      "El faro reapareció ante ellos. Cuando cruzaron la última franja de luz, el mar recuperó su oleaje y las estrellas volvieron a ocupar el cielo.",
      "Inés consultó el reloj del puente. Habían permanecido en Cárdena casi nueve horas. En el Argos solo habían transcurrido cuarenta y siete minutos.",
      "Mara abrió el cuaderno de su padre. Las últimas páginas contenían cálculos sobre las rotaciones de la lente. Junto a cada isla figuraban dos medidas temporales: la del interior y la del mundo exterior. —¿Dónde estaba la gente? —preguntó Inés. —Escondida —respondió una voz desde el muelle—. Ya no confían en quienes llegan siguiendo la luz.",
      "El hombre que habían visto al principio estaba allí. Era alto, de barba gris y rostro de edad difícil de precisar. Vestía un viejo uniforme de farero. En una mano sostenía una lámpara de aceite; en la otra, un fusil oxidado.",
      "Gael salió a cubierta. —Ezequiel. —Has tardado mucho en regresar. El farero miró a Mara. —Te pareces a Tomás. Sobre todo cuando estás a punto de hacer algo que te han advertido que no hagas.",
      "—¿Dónde está mi padre? —En Isla Baja. —Lléveme hasta él. —La luz decide la ruta, no yo. La segunda noche abrirá el camino a La Ceniza. La tercera, si el mecanismo resiste, llegaréis al 19 de julio de 1936.",
      "Mara le mostró la nota. —La tinta no puede llevar dieciocho años ahí. Ezequiel rozó el papel. —Dentro de esta torre la tinta no termina de secarse, el aceite no se consume y las heridas cicatrizan mal. El faro se encuentra entre los tiempos que ilumina.",
      "Inés levantó la brújula de latón. Ezequiel bajó el fusil. —Aurora llevaba esa brújula cuando abandonó Isla Baja. —Era mi abuela. —Entonces consiguió llegar a tierra. —¿Quién se la dio? Ezequiel estudió el rostro de Inés. —Nunca lo supe. Quizá todavía no haya ocurrido.",
      "—¿Quién es usted? —Su hermano. Inés negó con la cabeza. Aurora había muerto a los noventa y dos años. —Usted debería tener más de cien. —Yo tenía treinta y ocho aquella mañana. Para mí fue hace unos once meses. El faro no conserva los años como vosotros.",
      "Una nueva luz apareció a lo lejos. No procedía de un faro, sino de un barco de gran tamaño que avanzaba con todas las luces encendidas. En el casco se distinguía un nombre: ALCIÓN.",
      "Ezequiel cerró la brújula. —Salvador Veyra ha esperado dieciocho años a que se repita la alineación. Ya nos ha encontrado.",
    ],
  },
  {
    title: "El guardián de la sombra",
    visual:
      "Cámara secreta bajo un faro con una maqueta de siete islas de bronce, mapas y fórmulas en las paredes, un farero revela el origen de una lente negra a tres exploradores, misterio histórico cinematográfico",
    paragraphs: [
      "Antes de que el Alción llegara, Ezequiel los condujo a una sala oculta bajo el faro.",
      "La entrada estaba detrás de una estantería de cartas marítimas. Descendieron por una escalera hasta una cámara excavada en la roca. Las paredes estaban cubiertas de fórmulas, dibujos y anotaciones realizadas durante décadas por manos diferentes. En el centro había una maqueta del faro rodeada por siete pequeñas islas de bronce.",
      "—Mi padre, Samuel Oria, era físico y constructor de lentes —explicó Ezequiel—. En 1931 recibió el encargo de diseñar una señal capaz de atravesar las nieblas del Estrecho. Encontró en el fondo marino un cristal que desviaba la luz de una forma que no sabía explicar.",
      "Señaló un fragmento oscuro incrustado en la maqueta. —Al probarlo, la lámpara no iluminó la costa. Iluminó una isla que había desaparecido cuarenta años antes. El Faro de la Aguja solo puede entrar en contacto con nuestro presente cuando la misma combinación de mareas y posición lunar se repite. El ciclo tarda dieciocho años y permanece abierto tres noches.",
      "—¿Es un viaje en el tiempo? —preguntó Inés. —No exactamente. El faro no permite elegir cualquier momento. Encuentra lugares que han quedado fuera de la historia: islas evacuadas, pueblos olvidados, barcos que nadie buscó. Heridas que el mundo cerró demasiado deprisa.",
      "En 1936, Isla Baja albergaba a decenas de familias que huían de la violencia desatada en la península. Entre ellas había maestros, pescadores, militares, sindicalistas y personas cuyo único delito era poseer algo que otro deseaba. El comandante Álvaro Veyra recibió la orden de ocupar la isla.",
      "—Mi padre activó la lente para ocultarnos —continuó Ezequiel—. Funcionó, pero murió al fijar la primera ruta. Isla Baja desapareció del mar y de todas las cartas. Yo quedé en la torre para mantener la luz; los demás quedaron atrapados en el mismo día.",
      "Ezequiel explicó también lo que habían visto en Cárdena. La brújula había sincronizado durante unos segundos dos rutas distintas. La niña no estuvo físicamente allí: era la imagen de Aurora transmitida desde Isla Baja a través de la lente.",
      "—¿Y cómo logró salir mi abuela? —preguntó Inés. —Siempre contó que tres desconocidos la ayudaron durante una tormenta —dijo Mara—. Una mujer, un hombre herido y un marinero de barba roja. Ezequiel miró a los tres navegantes. —Entonces el faro aún no ha terminado de contar esa parte.",
      "Mara rodeó la maqueta. Una de las piezas representaba una isla calcinada. —¿La Ceniza? Ezequiel asintió. —Allí llegó Tomás hace dieciocho años. Después cruzó a Isla Baja y desde entonces impide que Veyra encuentre el Libro de los Nombres.",
      "Sacó una fotografía de un vapor llamado Santa Irene. Bajo su línea de flotación había viajado una caja fuerte con un registro de propiedades confiscadas, detenciones y ejecuciones ordenadas durante los primeros días del conflicto. Álvaro Veyra había pretendido destruirlo. Su nieto quería terminar el trabajo y apoderarse de los cálculos de Tomás.",
      "—La fortuna de los Veyra comenzó aquella semana —dijo Ezequiel—. Puertos, almacenes, barcos y tierras cambiaron de dueño mientras sus propietarios desaparecían. El libro demuestra cómo ocurrió.",
      "El sonido de una sirena recorrió la ensenada. A través de una rendija vieron aproximarse al Alción. En su cubierta esperaban varios hombres armados. —Hay algo más —advirtió Ezequiel—. Si dos barcos entran en una misma ruta, despiertan la segunda lámpara. La luz encuentra lo perdido. La sombra reclama uno de los navíos que la despertaron y, hasta recibirlo, empieza a borrar otro lugar.",
    ],
  },
  {
    title: "La deuda de Gael",
    visual:
      "Magnate marítimo elegante desembarca de un gran buque escoltado por hombres armados frente a un viejo capitán y una cartógrafa, faro negro detrás, thriller marítimo realista",
    paragraphs: [
      "Salvador Veyra llegó al faro poco antes del amanecer.",
      "Era un hombre de sesenta años, impecablemente vestido a pesar de la travesía. Subió al muelle acompañado por cuatro guardias y saludó a Gael como si acudiera a una reunión concertada. —Nunca creí que volverías. —Yo sí —respondió el capitán—. Por eso no he dormido bien en dieciocho años.",
      "Veyra observó a Mara. —La hija de Tomás Vidal. Esto empieza a parecer una reunión familiar. Mara sintió deseos de golpearlo, pero esperó.",
      "Veyra afirmó que buscaba los restos de una expedición financiada por su empresa. Según él, Tomás había robado información histórica y provocado la desaparición de dos hombres. —Mi padre trató de detenerlo —explicó—. Gael estaba allí.",
      "Mara miró al capitán. Gael no lo negó. Veyra propuso unir fuerzas. A cambio de acceder al faro, pondría el Alción a su disposición para rescatar a Tomás. —No confío en usted —dijo Mara. —No es necesario. Basta con que confíe en que también quiero salir vivo.",
      "Cuando Veyra regresó a su barco, dejó a dos hombres vigilando el muelle. Mara condujo a Gael hasta el puente del Argos. —Cuéntamelo todo.",
      "Dieciocho años atrás, Gael era patrón de una lancha propiedad de la familia Veyra. Tomás lo había contratado para localizar el Faro de la Aguja. Salvador y su padre se enteraron y obligaron a Gael a llevar también a varios de sus hombres.",
      "Encontraron la torre durante una noche sin luna. Tomás descubrió que los Veyra no buscaban un tesoro, sino el libro escondido en Isla Baja. Hubo una pelea en la sala de la lente. Dos embarcaciones entraron en la ruta, la lámpara negra se encendió y La Ceniza apareció en medio de una tormenta.",
      "—Tu padre consiguió que yo saliera —dijo Gael—. Me entregó sus notas y me ordenó llevarlas a tierra. —Pero no lo hiciste. —Los hombres de Veyra me esperaban en el puerto. Me quitaron casi todo y amenazaron a mi familia. Dije que Tomás había muerto en el naufragio.",
      "—Me mentiste durante dieciocho años. —Sí. —¿Por qué has vuelto? Gael sacó del interior de su chaqueta una pieza semicircular de cobre. Encajaba en el reverso de la brújula de Inés. —Porque logré esconder esto. Y porque cada noche, desde entonces, sueño que tu padre sigue esperando.",
      "Inés unió ambas piezas. La aguja dejó de señalar el norte. Bajo la rosa de los vientos apareció una cuadrícula diminuta y tres números: 47, 18 y 36. Cuarenta y siete minutos era la duración de la primera ruta; dieciocho años, el intervalo de la alineación; treinta y seis, el año al que conducía la tercera noche.",
      "En la radio del Argos apareció la voz de Veyra. —La segunda puesta de sol será esta tarde. Os recomiendo descansar. Mañana por la noche abriremos 1936. Gael apagó el receptor. —No sabe cómo hacerlo. Inés sostuvo la brújula completa. —Ahora sí.",
      "Desde el exterior llegó un disparo. Cuando salieron, Ezequiel había desaparecido. En el suelo del muelle solo quedaba su lámpara, rota y manchada de sangre.",
    ],
  },
  {
    title: "El mapa bajo el agua",
    visual:
      "Tres buceadores descubren una cámara inundada bajo un faro, mosaico luminoso con siete islas y rutas temporales bajo el agua, aventura submarina oscura y realista",
    paragraphs: [
      "Los hombres de Veyra afirmaron que Ezequiel había intentado atacarlos y se había arrojado al mar.",
      "Mara no les creyó. No encontraron el cuerpo, pero sí un rastro de sangre que terminaba junto a una compuerta de hierro al pie del faro. La marea la cubría casi por completo. Inés observó la brújula. La aguja apuntaba hacia la compuerta.",
      "Esperaron a que los vigilantes se alejaran. Después descendieron desde la popa del Argos con trajes de buceo. La puerta conducía a un túnel inundado. Avanzaron entre tuberías oxidadas y restos de engranajes hasta emerger en una cámara de aire bajo la torre.",
      "Ezequiel estaba allí. La bala le había rozado el costado y había logrado escapar utilizando un conducto que los hombres de Veyra desconocían. —Sabía que la brújula os traería —dijo.",
      "En el suelo de la cámara había un mosaico cubierto por una fina capa de agua. Cuando Inés colocó su lámpara bajo la superficie, aparecieron líneas plateadas. Era un mapa de las siete islas del mecanismo y de los corredores que las unían. Cada ruta comenzaba en el faro y terminaba en una fecha.",
      "Cárdena: 1958. La Ceniza: 2008. Isla Baja: 1936. Las otras cuatro fechas habían sido borradas.",
      "—Mi padre construyó este mapa para que la luz no pudiera controlarse únicamente desde la torre —explicó Ezequiel—. La lente abre la puerta, pero la brújula elige por dónde regresar.",
      "Mara recorrió con los dedos la ruta de La Ceniza. —¿Encontraremos allí a Tomás? —Encontraréis lo que dejó antes de cruzar a Isla Baja. —¿Por qué fue hasta 1936? —Para impedir que Veyra llegara al libro. Y para reparar el accidente que provocamos en 2008.",
      "Ezequiel señaló dos líneas superpuestas. Dieciocho años atrás habían entrado dos embarcaciones en la misma ruta. Una regresó. La otra quedó atrapada entre La Ceniza y la sombra. —Si el Argos y el Alción cruzan juntos, volverá a ocurrir.",
      "—Entonces inutilicemos el faro —propuso Gael. —Si rompemos la lente mientras las islas siguen conectadas, sus habitantes desaparecerán también de la memoria de quienes los conocieron.",
      "Inés se arrodilló frente al mapa. Bajo las líneas apareció una inscripción al acercar la brújula: «La sombra reclamará uno de los dos navíos que la despierten». —No habla del peso físico —aclaró Ezequiel—. Habla de la incursión. Un barco entra de más y un barco debe quedarse.",
      "Un ruido metálico resonó sobre ellos. La compuerta del túnel acababa de cerrarse. Después escucharon la voz de Veyra a través de una tubería. —Gracias por encontrar el mapa.",
      "El agua empezó a subir.",
    ],
  },
  {
    title: "La segunda noche",
    visual:
      "Isla quemada bajo nubes rojas con un pecio de 2008 y un campamento abandonado, tres navegantes descubren una cámara de vídeo mientras figuras oscuras aparecen entre árboles carbonizados, terror marítimo realista",
    paragraphs: [
      "Gael encontró una válvula de desagüe oculta entre los engranajes. La tubería llevaba décadas sin abrirse. Los tres tiraron hasta que el metal cedió y una corriente violenta arrastró el agua hacia un conducto inferior.",
      "Escaparon pocos minutos antes de que la cámara quedara inundada. Cuando llegaron a la superficie, el sol comenzaba a ponerse. La segunda noche había llegado.",
      "El haz del faro se encendió sin que nadie tocara la lámpara. Giró lentamente hasta apuntar hacia el sur. Allí apareció La Ceniza. Era un fragmento de costa devastado por un incendio. Los troncos carbonizados se extendían hasta una montaña cubierta de nubes rojas.",
      "Veyra observaba desde la cubierta del Alción. —Tenéis una hora —anunció por radio—. Después iré yo. Mara comprendió que les permitía cruzar para comprobar si la ruta era segura.",
      "El Argos entró en el corredor de luz. En La Ceniza encontraron los restos de la embarcación utilizada por Tomás dieciocho años atrás. La proa estaba incrustada en las rocas, el metal cubierto de sal y el motor completamente frío. Para aquel lugar habían transcurrido meses, no años.",
      "En el interior del barco encontraron tres cadáveres. Gael reconoció a los hombres de Veyra. El tiempo apenas había alterado sus cuerpos. —Tomás sobrevivió —dijo Mara.",
      "Un sendero conducía desde el pecio hasta un campamento levantado entre las ruinas de un observatorio meteorológico. Había doscientas ochenta y cuatro marcas talladas en una pared, latas vacías, ropa endurecida por la ceniza y páginas arrancadas de un cuaderno. Sobre una mesa descansaba una cámara de vídeo.",
      "La batería todavía funcionaba. Tomás apareció en la pantalla, más delgado y con una venda alrededor de la cabeza. —Día doscientos ochenta y cuatro. En el exterior se acerca una nueva apertura. La ruta hacia Isla Baja ha vuelto a responder.",
      "Mara contuvo el aliento. —La lámpara negra sigue activa —continuó Tomás—. Cada vez que el faro abre una puerta, la sombra intenta intercambiar las islas por algún lugar del presente. Cruzaré a 1936 para impedir que Veyra encuentre el libro.",
      "Tomás bajó la mirada. —Si Mara llega hasta aquí, decidle que no desperdicie su vida intentando devolverme la mía. La imagen se llenó de interferencias.",
      "Afuera, alguien llamó a Mara. Era la voz de su padre. —Estoy aquí. Ven sola. Mara dio un paso hacia la puerta, pero Gael la detuvo. —Eso no es Tomás.",
      "Entre los árboles apareció una figura con el rostro de su padre. Proyectaba una sombra que caminaba en dirección contraria. Mara disparó una bengala. La luz atravesó el cuerpo y reveló agua negra llena de pequeños puntos luminosos.",
      "La figura se deshizo sobre la tierra. Detrás de ella comenzaron a levantarse otras formas.",
    ],
  },
  {
    title: "Dieciocho años en un día",
    visual:
      "Tres personas corren por una isla donde el cielo alterna día y noche a cada paso, figuras de agua negra los persiguen hasta un barco dentro de un corredor de luz, acción sobrenatural cinematográfica",
    paragraphs: [
      "El suelo comenzó a vibrar. —¡Al barco! —gritó Gael.",
      "Corrieron hacia la costa mientras otras formas aparecían entre los árboles. Algunas imitaban a los hombres muertos en el pecio. Otras no tenían rostro. Inés consultó la brújula. —La ruta se está desplazando.",
      "El corredor luminoso ya no terminaba frente al puerto. Se movía hacia el acantilado occidental. Tuvieron que atravesar una zona donde el tiempo avanzaba a distinta velocidad. A cada paso, el cielo pasaba de la noche al día y del día a la noche. La vegetación crecía, se secaba y volvía a brotar en pocos segundos.",
      "Gael cayó. Cuando Mara lo ayudó a levantarse, su barba había encanecido por completo y las arrugas de su rostro eran más profundas. —¿Cuánto tiempo ha pasado? —No lo sé.",
      "Inés lanzó una cuerda desde una roca y descendieron hasta el Argos. Detrás de ellos, las figuras llenaban el acantilado. El barco cruzó la ruta mientras la isla ardía.",
      "Al llegar al faro, Gael recuperó poco a poco su aspecto. Solo quedó una franja blanca en su barba. Habían pasado siete minutos en el mundo exterior.",
      "Veyra los esperaba en el muelle. Sus hombres registraron el Argos y se llevaron la cámara de Tomás. También encontraron la brújula, pero la pieza de cobre permanecía escondida bajo la consola del timón.",
      "—Mañana iremos todos a Isla Baja —dijo Veyra—. Vuestro barco abrirá la ruta y el mío la mantendrá estable. —Dos barcos no pueden cruzar —advirtió Mara. —Eso dice Ezequiel. También decía que el faro era imposible.",
      "Encerraron a Mara, Gael e Inés en el camarote de popa. Poco antes del amanecer, la radio se encendió por sí sola. Una voz infantil surgió entre los crujidos. —¿Me escucháis? Me llamo Aurora Oria. Hoy es 19 de julio de 1936.",
      "Inés acercó el micrófono. —Te escucho. Aurora, tienes que esconder la pieza de cristal de tu padre en la cueva que hay bajo el cementerio. No se la entregues a nadie. Al otro lado hubo un silencio. —Ya lo hice —respondió la niña—. Me lo dirás mañana.",
      "Inés miró a Mara. Las transmisiones del faro no solo cruzaban años; tampoco respetaban el orden de los acontecimientos.",
      "La puerta del camarote se abrió. Salvador Veyra estaba al otro lado. Tenía la brújula de Inés en una mano y una pistola en la otra. —Gracias —dijo—. Ahora ya sé dónde está la primera llave.",
    ],
  },
  {
    title: "La voz de 1936",
    visual:
      "Niña de 1936 transmitiendo desde la radio de un viejo vapor mientras una mujer del presente escucha emocionada en un barco moderno, dos épocas unidas por estática, drama de misterio cinematográfico",
    paragraphs: [
      "Aurora hablaba desde la estación de radio del Santa Irene.",
      "El vapor había sufrido una avería frente a Isla Baja. Sesenta y tres personas se refugiaban en el puerto mientras una patrullera al mando de Álvaro Veyra se aproximaba desde la península.",
      "La niña describió el faro, las casas blancas y el almacén donde Tomás había escondido el Libro de los Nombres después de sacarlo de la caja fuerte del Santa Irene. —Hay un hombre con nosotros —añadió—. Se llama Tomás. Dice que su hija vendrá por el mar.",
      "Mara tomó el micrófono. —Aurora, ¿puedes pasármelo? Se oyeron pasos y voces. Después, una respiración. —¿Mara? Durante dieciocho años había preparado acusaciones, preguntas y reproches. Cuando escuchó a su padre no pudo pronunciar ninguno. —Papá.",
      "Tomás tampoco habló durante unos segundos. —¿Cuántos años tienes? —Treinta y seis. Él soltó el aire lentamente. —Cuando me marché tenías dieciocho. —Para ti no ha pasado tanto. —Trescientos nueve días entre La Ceniza e Isla Baja.",
      "Mara apoyó la frente contra la radio. —Voy a buscarte. —Veyra está contigo. No era una pregunta. —Sí. —No dejes que cruce. El Libro de los Nombres no es lo único que busca.",
      "Tomás explicó que Álvaro Veyra había descubierto la naturaleza de la lente en 1936. Quería utilizarla para ocultar barcos, trasladar armas y borrar lugares enteros de las cartas. Salvador pretendía recuperar sus cálculos y las grabaciones de La Ceniza para volver a abrir las rutas.",
      "—La lámpara negra está despierta —continuó—. Si entran dos barcos, la sombra elegirá un puerto del presente para sustituir Isla Baja. Puede desaparecer una ciudad entera. —¿Cómo la detenemos? —Hay que cerrar la ruta desde los dos extremos. Ezequiel sabe cómo hacerlo.",
      "—Está herido. —Entonces necesitará la brújula de Aurora. Inés tomó el micrófono. —La tengo yo. Al otro lado, la niña rio. —Te dije que volvería.",
      "La comunicación comenzó a desvanecerse. —Papá —dijo Mara—, ¿puedes regresar? —Puedo intentarlo. —Eso no es una respuesta. —Mi cuerpo tiene dieciocho años pendientes. Al cruzar quizá quiera recuperarlos de golpe.",
      "—No me importa. —A mí sí. He pasado toda tu vida tomando decisiones por ti. No volveré a hacerlo. Antes de que la señal desapareciera, Tomás añadió: —Cuando lleguéis, no sigáis solo la luz blanca. Recordad qué barco debe recibir la sombra.",
      "Veyra había escuchado desde la puerta. —Su padre sigue vivo —dijo—. Puedo traerlo de vuelta. —Usted no quiere rescatarlo. —Quiero el libro y los cálculos. Pero nuestros objetivos todavía son compatibles.",
      "Mara sostuvo su mirada. —Solo hasta que se encienda la luz.",
    ],
  },
  {
    title: "Los hombres del Alción",
    visual:
      "Hombres armados conectan un gran buque a un faro antiguo mientras una ingeniera alinea una brújula de latón con una lente gigante, dos barcos esperan ante un corredor temporal, thriller marítimo nocturno",
    paragraphs: [
      "Veyra trasladó a Ezequiel a la sala de la lente y obligó a Inés a colocar la brújula en el mecanismo.",
      "—Abrirás la ruta —ordenó—. Después recuperaré a Tomás, el libro y todos sus cálculos. —¿Y los refugiados? —Llevan noventa años muertos para el resto del mundo. —No para ellos. —La historia está llena de personas que no tuvieron un final justo. No podemos rescatarlas a todas.",
      "Mara comprendió que Veyra había ensayado aquel argumento muchas veces. No pretendía convencerlos. Intentaba convencerse a sí mismo.",
      "Sus hombres instalaron cables entre el generador del Alción y la lámpara. La energía eléctrica hizo vibrar la lente. Ezequiel yacía en el suelo, pálido por la pérdida de sangre. —Necesita un médico —dijo Mara. —Lo tendrá cuando abra la puerta.",
      "El sol descendió. La tercera noche comenzó. Inés introdujo la brújula, pero sin la pieza semicircular no aparecía la cuadrícula completa. Fingió estudiar los números mientras buscaba una forma de retrasarlos.",
      "En el Argos, Gael permanecía vigilado junto al timón. Había ocultado la pieza de cobre bajo la consola. Cuando nadie miraba la colocó sobre la brújula magnética del barco. Las dos mitades del instrumento, separadas por el muelle, comenzaron a resonar y ambas agujas se desviaron hacia el oeste.",
      "Inés vio el cambio desde la torre y comprendió el mensaje. Giró el mecanismo exactamente cuarenta y siete grados. La lente despertó.",
      "El haz blanco atravesó el horizonte y encontró Isla Baja. Apareció bajo una tormenta, con sus casas iluminadas por lámparas de aceite y el Santa Irene atracado en el puerto.",
      "Antes de abandonar la torre, Ezequiel sujetó la muñeca de Inés. —Llévate la brújula. Cuando encuentres a Aurora, dásela. —Pero mi abuela me la entregó cuando yo era niña. —Entonces tendrás que cerrar el círculo. La brújula quizá nunca tuvo un primer dueño.",
      "Inés liberó el instrumento del soporte y escondió la pieza principal bajo la chaqueta. Al llegar al Argos, Gael le devolvió la mitad de cobre. El mecanismo del faro continuó girando con el rumbo que ya había recibido.",
      "Veyra subió al Alción. Uno de sus hombres tomó el timón del Argos bajo la amenaza de un arma, pero Gael lo redujo en cuanto dejaron el muelle. —Sacad uno de los barcos de la línea —advirtió Ezequiel por radio—. Todavía estáis a tiempo.",
      "El Argos entró primero en el corredor. El Alción aceleró detrás. Durante unos segundos ambas embarcaciones ocuparon la misma franja de luz.",
      "La segunda lámpara se encendió. No produjo oscuridad, sino una luz negra que parecía borrar todo cuanto tocaba. Las estrellas desaparecieron sobre el Alción y su reflejo se desvaneció del agua. Del mar surgieron chimeneas, mástiles y edificios pertenecientes a épocas diferentes.",
      "En la distancia apareció la costa de Cádiz. Parpadeó una vez y perdió todas sus luces.",
    ],
  },
  {
    title: "La lámpara negra",
    visual:
      "Dos barcos atraviesan un corredor de luz sobre un océano negro mientras ciudades y navíos de distintas épocas aparecen alrededor, un farero bloquea una lente agrietada en la torre, fantasía marítima cinematográfica",
    paragraphs: [
      "El Alción quedó atrapado entre dos mares.",
      "A babor se extendía la noche del presente. A estribor amanecía sobre una costa de 1936. Entre ambas, la luz negra recortaba un vacío que crecía hacia Cádiz.",
      "Ezequiel golpeó uno de los engranajes con la base de su lámpara. La lente se detuvo a mitad de la rotación y el corredor tembló. —No puedo contener la sombra mucho tiempo —advirtió por radio—. Uno de los dos barcos tendrá que regresar o ser entregado.",
      "Veyra ordenó aumentar la potencia. El Alción embistió la corriente y arrastró al Argos. Una descarga recorrió los cables conectados al faro. El cristal exterior de la lente se agrietó y cada fragmento empezó a reflejar una escena diferente.",
      "Mara se vio de niña esperando a su padre frente a una ventana. Gael se vio abandonando a Tomás en La Ceniza. Inés vio a su abuela anciana entregándole la misma brújula que ahora llevaba contra el pecho.",
      "—La sombra utiliza recuerdos para fijar aquello que quiere sustituir —explicó Ezequiel—. No miréis las imágenes. Mantened el rumbo.",
      "Mara tomó el timón del Argos. —Podemos retroceder. —Si partes ahora la ruta —respondió Ezequiel—, Isla Baja quedará unida a la sombra y desaparecerá. Debéis cerrarla desde 1936.",
      "—¿Y usted? —Alguien debe mantener el faro encendido hasta que el último barco cruce.",
      "Inés apretó la brújula. —¿Volverá a ver a Aurora? —Durante once meses he pensado que había muerto. Ahora sé que tuvo una vida. Si llego a verla, será al final.",
      "La tormenta cambió al atravesar el centro del corredor. La radio comenzó a emitir música de otra época. La voz de un locutor anunció noticias confusas sobre sublevaciones, acuartelamientos y carreteras cortadas.",
      "Un periódico flotó junto al casco. Inés alcanzó a leer la fecha: 19 de julio de 1936.",
      "Ante ellos se extendía Isla Baja. En la playa, decenas de personas observaban los dos barcos llegados del futuro. Entre ellas había un hombre de cabello oscuro y chaqueta azul.",
      "Mara lo reconoció antes de verle el rostro. Tomás Vidal había esperado trescientos nueve días para abrazar a una hija que había envejecido dieciocho años.",
    ],
  },
  {
    title: "La ruta de julio",
    visual:
      "Padre e hija se reencuentran en el muelle de una isla española de 1936 mientras un barco moderno aparece detrás, refugiados con ropa de época observan bajo una tormenta, escena emotiva cinematográfica",
    paragraphs: [
      "Tomás saltó a bordo antes de que terminaran de amarrar.",
      "Durante unos segundos, Mara permaneció inmóvil. Su padre conservaba casi el mismo rostro del día en que desapareció. Tenía nuevas cicatrices y algunas canas, pero seguía siendo un hombre de cincuenta años frente a una hija que ya no tenía dieciocho.",
      "Tomás la abrazó. Mara quiso resistirse. No pudo. —Lo siento —dijo él. —No es suficiente. —Lo sé. —Pero tendrás que empezar por ahí.",
      "Detrás de ellos, el Alción entró en el puerto. Veyra y sus hombres descendieron armados. Los habitantes de la isla retrocedieron hacia las casas.",
      "Tomás condujo a Mara, Gael e Inés hasta un almacén. Allí conocieron a Aurora, una niña delgada con el mismo pelo oscuro de Inés. La observó con una curiosidad absoluta. —Eres tú. La mujer de la radio. —Y tú eres mi abuela. Aurora meditó la respuesta. —Todavía no.",
      "Tomás desplegó un mapa sobre una mesa. Isla Baja no llevaba noventa años repitiendo una fecha completa, sino una única jornada. Cada amanecer, las casas, los barcos y los cuerpos de sus habitantes regresaban al comienzo del 19 de julio. Ellos conservaban los recuerdos de las trescientas nueve repeticiones; sus cuerpos no envejecían. Tomás, por haber llegado desde el exterior, sí había envejecido cada uno de esos días.",
      "El faro podía liberar a los habitantes enviando la isla a Poniente, una de las rutas borradas del mapa donde el tiempo avanzaba con normalidad aunque permaneciera separada del mundo. —¿Por qué no traerlos al presente? —preguntó Mara. —Porque la lámpara negra elegiría el mismo número de vidas para sustituirlos —respondió Tomás—. Poniente no exige ese intercambio.",
      "—¿Y tú? —Yo entré desde el presente. Puedo regresar. Mara percibió la vacilación. —¿Qué me estás ocultando? —Mi cuerpo tiene una deuda de dieciocho años. No sé qué ocurrirá al cruzar.",
      "Desde el puerto llegó un disparo. Veyra había encontrado el almacén donde se ocultaba el Libro de los Nombres. Gael recogió un fusil. —¿Qué necesita para trasladar la isla? —Dos llaves del mecanismo —explicó Tomás—. Una pieza de cristal que Samuel confió a Aurora y una llave metálica que Álvaro robó durante el primer ataque. No abren el libro; fijan los dos extremos de la ruta.",
      "Un motor antiguo resonó más allá del cabo. Una patrullera apareció entre la niebla. En su proa ondeaba una bandera y varios hombres preparaban las armas.",
      "Salvador Veyra salió al muelle para recibirla. En el puente de la patrullera estaba su abuelo, el hombre que había iniciado la fortuna de su familia y que, según los registros, desaparecería en el mar aquella misma noche.",
    ],
  },
  {
    title: "La isla sitiada",
    visual:
      "Un magnate moderno se enfrenta a su abuelo uniformado de 1936 en un muelle, detrás un buque futurista y una patrullera histórica, habitantes levantan barricadas en un pueblo insular, thriller histórico realista",
    paragraphs: [
      "Álvaro Veyra desembarcó acompañado por doce soldados.",
      "Era más joven de lo que Salvador esperaba. Apenas superaba los treinta años. Llevaba el uniforme abierto, una pistola al cinto y una expresión de desprecio que no cambió al contemplar el Alción.",
      "—¿Quién manda aquí? —preguntó. Salvador avanzó hacia él. —Soy su nieto. Álvaro lo miró de arriba abajo. —Mi hijo Ernesto apenas tiene cuatro años. —Será mi padre. —Entonces procuraré educarlo mejor.",
      "Salvador intentó explicarle que procedía del futuro. Álvaro escuchó en silencio hasta que vio el nombre de la compañía pintado en el casco del Alción: Veyra Oceanic. Comprendió que aquel barco era la prueba de que sus planes habían funcionado. —Así que ganamos. —Nuestra familia construye una de las mayores navieras del país. —¿Y has venido a darme las gracias? —He venido por el libro. —Entonces aún no hemos ganado del todo.",
      "Desde una azotea, Mara y Tomás presenciaron la conversación. Veyra no buscaba únicamente proteger su apellido. Las propiedades inscritas en el libro incluían terrenos portuarios, astilleros y almacenes que seguían formando parte de su empresa. Si se demostraba su origen, perdería gran parte de su fortuna.",
      "Álvaro ordenó registrar la isla. Los habitantes levantaron barricadas en las calles. Eran pescadores, familias y tripulantes sin experiencia militar. No podrían resistir un ataque.",
      "Inés llevó a Aurora hasta la cueva situada bajo el cementerio. Allí encontraron la primera llave, la pieza de cristal negro que la niña había escondido siguiendo una instrucción recibida desde su propio futuro.",
      "—Mi padre dijo que no debía dársela a nadie —explicó Aurora. —Tenía razón. Inés guardó la llave y colocó la brújula en las manos de la niña. —Pero esto sí debes conservarlo.",
      "Aurora leyó la inscripción: «Para que siempre encuentres el camino de regreso». —¿Me ayudará a volver? —Siempre. La niña cerró la tapa. En ese instante, Inés sintió desaparecer del bolsillo el recuerdo físico de haber llevado dos brújulas. Solo había existido aquella, viajando de una a otra a través del mismo círculo.",
      "—Cuando llegue la tormenta, ve al embarcadero pequeño —le indicó—. Habrá una barca y dos marineros del Santa Irene esperándote. —¿Vienes conmigo? —Te acompañaré hasta donde pueda.",
      "En el pueblo comenzaron los disparos. Gael organizó la evacuación hacia el Santa Irene. Tomás preparó el mecanismo que permitiría desplazar la isla a Poniente.",
      "Mara regresó al almacén. La caja fuerte a la que Tomás había trasladado el libro estaba abierta. En el suelo encontraron a uno de los hombres de Salvador, muerto de un disparo. Sobre la pared alguien había escrito con tiza: «El futuro pertenece a quien borra mejor el pasado».",
      "Álvaro Veyra se había llevado el Libro de los Nombres y la segunda llave.",
    ],
  },
  {
    title: "El hombre que esperaba",
    visual:
      "Padre e hija conversan en una habitación austera de un faro de 1936, dibujos del rostro adulto de ella cubren la pared y una tormenta temporal une una ciudad moderna con el pueblo antiguo, drama cinematográfico",
    paragraphs: [
      "Tomás llevó a Mara al antiguo faro de Isla Baja.",
      "No era la torre que habían encontrado en el presente, sino su reflejo: una construcción más pequeña levantada sobre el acantilado y conectada a la lente principal mediante espejos enterrados bajo el mar.",
      "Allí había vivido durante las últimas veinticinco repeticiones, después de abandonar La Ceniza. En una habitación encontró Mara dibujos de su rostro realizados de memoria. Algunos la mostraban con dieciocho años. En otros, Tomás había intentado imaginar cómo sería de adulta.",
      "—Pensé en ti todos los días —dijo. —Pensar no es lo mismo que estar. —No.",
      "Tomás no trató de justificarse. Le contó que en 2008 tuvo la oportunidad de regresar. El corredor permaneció abierto el tiempo suficiente para que una persona cruzara. Él eligió enviar a Gael porque sabía manejar el barco y podía avisar a las autoridades.",
      "—Gael no avisó. —Lo sé. Pero yo tomé la decisión. Después descubrí el plan de los Veyra y permanecí para proteger el libro. Con el tiempo comprendí que también me escondía detrás de aquella misión. Mientras siguiera salvando la isla, no tendría que afrontar todo lo que había perdido.",
      "—Quizá no fui su prisionero —admitió—. Quizá convertí el faro en una excusa. Mara contempló el mar. —No puedo recuperar los años que no estuviste. —No. —Y todavía no sé si podré perdonarte. —No tienes obligación de hacerlo.",
      "—Pero vas a regresar conmigo y tendrás que darme tiempo para decidirlo. Tomás sonrió. —Eso suena justo.",
      "Afuera, dos épocas comenzaban a ocupar el mismo espacio. Edificios modernos aparecían entre las casas de 1936. Durante unos segundos, una autopista atravesó la plaza y varios automóviles pasaron entre los refugiados sin verlos.",
      "Mara utilizó la radio del faro. —Salvador, su abuelo se ha llevado el libro y la segunda llave. Si regresa a tierra con ellos, sabrá exactamente cómo construir el futuro del que usted viene. Quizá decida que su hijo no necesita heredar nada.",
      "Era una posibilidad, no una certeza, pero resultó suficiente. El Alción encendió los motores. Salvador ordenó perseguir a su propio abuelo.",
      "La patrullera abandonó el puerto. El gran barco moderno fue detrás. Sobre el horizonte, la silueta de Cádiz se oscureció hasta convertirse en una ciudad sin faros, carreteras ni puerto.",
      "La sombra ya había empezado a borrar el presente.",
    ],
  },
  {
    title: "El Libro de los Nombres",
    visual:
      "Abuelo y nieto de épocas distintas se enfrentan junto a una batería costera, un libro antiguo arde parcialmente mientras una cartógrafa intenta rescatarlo, tormenta y barcos al fondo, thriller histórico cinematográfico",
    paragraphs: [
      "Gael condujo el Argos tras los dos barcos.",
      "La patrullera de Álvaro era más lenta, pero conocía los arrecifes. El Alción tuvo que reducir velocidad mientras navegaba entre rocas que aparecían y desaparecían. Mara, Tomás e Inés encontraron la embarcación de 1936 encallada en una bahía.",
      "Álvaro había desembarcado con el libro y se dirigía hacia una antigua batería costera desde la que podía incendiar Isla Baja. Salvador llegó antes que ellos. Abuelo y nieto se enfrentaron en lo alto del acantilado.",
      "—Entrégueme el libro —exigió Salvador. —Todo lo que tienes existe gracias a mí. —Precisamente por eso debo destruirlo. Álvaro levantó el volumen, grueso, encuadernado en cuero y protegido por una cubierta impermeable. —Aquí no hay culpa. Hay propiedades. —Hay nombres. —Los nombres desaparecen. La tierra permanece.",
      "Salvador pareció verse por primera vez desde fuera. Toda su vida había defendido el legado familiar imaginando decisiones difíciles tomadas en tiempos caóticos. Ante él no había un hombre obligado por las circunstancias, sino alguien orgulloso de haber utilizado el caos.",
      "Álvaro lanzó el libro a una hoguera encendida junto a la batería. Mara corrió. Tomás la sujetó por la cintura mientras ella alcanzaba el volumen entre las llamas. La cubierta ardió, pero las páginas interiores permanecieron intactas.",
      "Álvaro disparó. Salvador se interpuso. La bala le atravesó el hombro. Gael respondió con un disparo que obligó a Álvaro a refugiarse entre los cañones.",
      "Inés recogió una pieza metálica que había caído de la chaqueta del comandante. Era la segunda llave. —Ya tenemos las dos.",
      "El acantilado se estremeció. Sobre el mar apareció la silueta del puerto moderno. Las grúas, edificios y depósitos de combustible parpadearon como una imagen defectuosa. En las radios se mezclaron voces de 1936 con avisos de emergencia del presente.",
      "Tomás examinó el horizonte. —La sombra ha elegido qué quiere borrar mientras espera uno de los dos barcos que la despertaron. —¿Qué lugar? —preguntó Mara. —El puerto de Cádiz.",
      "Miles de personas vivían y trabajaban en la zona que comenzaba a desaparecer. Gael miró el Alción. —Ese barco abrió la sombra. Ese barco puede cerrarla.",
      "Salvador, tendido en el suelo, comprendió lo que proponía. El Alción era el buque insignia de su empresa y guardaba las copias de la cámara y los cálculos recuperados en La Ceniza.",
      "—El sistema de navegación está protegido —dijo—. Sin mis códigos no podréis llevarlo al centro del corredor. —Entonces déselos —respondió Mara. Salvador observó a su abuelo, al libro chamuscado y al barco que llevaba su apellido. —Tendréis los códigos. Pero yo iré a bordo.",
    ],
  },
  {
    title: "La noche de las dos costas",
    visual:
      "Dos costas de 1936 y del presente superpuestas durante una tormenta, tres navegantes preparan dos barcos y una niña parte en una barca con marineros, faro blanco y sombra negra sobre el mar, épica cinematográfica",
    paragraphs: [
      "La tormenta cayó sobre Isla Baja al anochecer.",
      "Dos costas ocupaban ahora el mismo espacio. En una, las casas de 1936 se preparaban para soportar el ataque de Álvaro. En la otra, las luces del puerto moderno parpadeaban mientras barcos y edificios desaparecían durante segundos.",
      "Inés colocó las dos llaves en el mecanismo del faro de la isla. La lente respondió con un pulso que recorrió las calles. Ezequiel habló desde la torre principal. Su voz apenas atravesaba la estática. —Puedo abrir Poniente y recoger también a Cárdena durante el último barrido. Pero alguien tendrá que fijar la ruta desde Isla Baja.",
      "—Tomás lo hará —dijo Mara. —Si permanece en el mecanismo, no podrá regresar. Mara miró a su padre. Tomás ya lo sabía.",
      "—Tiene que existir otra forma. —La hay —respondió Ezequiel—. Tres navegantes pueden mantener el rumbo desde el mar: uno para la luz, otro para la sombra y otro para el tiempo.",
      "Mara conduciría el Argos por el corredor blanco. Gael llevaría el Alción hasta el centro de la sombra. Inés coordinaría los dos faros y las llaves. Cuando el buque de Veyra desapareciera, Tomás podría cerrar el mecanismo y cruzar antes de que la ruta se extinguiera.",
      "Salvador entregó sus códigos. Con el hombro vendado, insistió en acompañar a Gael. —Es mi barco. —También es mi deuda —replicó el capitán. —Usted ya lleva dieciocho años pagándola. Yo acabo de empezar.",
      "En el embarcadero pequeño, Inés encontró la barca preparada. Dos marineros del Santa Irene aguardaban a bordo para llevar a Aurora hasta la costa. La niña sostenía la brújula contra el pecho.",
      "—Navegad hacia las tres luces y no miréis atrás, aunque oigáis voces —indicó Inés. Aurora la abrazó. —¿Volveremos a vernos? Inés pensó en su abuela anciana enseñándole a distinguir las estrellas. —Sí. Pero tú no me reconocerás.",
      "Gael apareció con la barba mojada por la lluvia. Un relámpago tiñó de cobre la franja blanca que La Ceniza había dejado en ella. Salvador llegó detrás, pálido y con el brazo inmovilizado. Entregó agua y una carta de navegación a los dos marineros antes de ayudar a Aurora a subir.",
      "La niña miró a los tres desconocidos que conservaría en su memoria: la mujer de la radio, el hombre herido y el marinero de barba roja. La historia había alcanzado por fin su propio recuerdo.",
      "Gael empujó la embarcación hacia el corredor que desembocaba cerca de la costa de 1936. A lo lejos, la patrullera de Álvaro volvió a ponerse en movimiento. Sus cañones apuntaban al Santa Irene.",
      "La primera detonación iluminó las dos costas.",
    ],
  },
  {
    title: "Toda luz proyecta una sombra",
    visual:
      "Pequeño barco navega por un corredor blanco y un gran buque por una franja de luz negra, una patrullera de 1936 los persigue bajo una tormenta temporal, clímax marítimo épico y realista",
    paragraphs: [
      "El Argos salió del puerto bajo el fuego de la patrullera.",
      "Mara estaba al timón. Tomás permanecía en Isla Baja junto al mecanismo y Ezequiel controlaba la lente desde el faro principal. Inés coordinaba las tres posiciones por radio. —Luz blanca a treinta grados. Sombra al oeste.",
      "El Alción avanzaba en paralelo. Gael y Salvador trataban de mantenerlo dentro de la franja negra, donde el mar carecía de reflejos. Álvaro los persiguió convencido de que el corredor conducía al futuro que había visto y de que allí podría reclamar el imperio levantado con su apellido.",
      "La patrullera abrió fuego. Un proyectil golpeó la popa del Argos. El timón quedó bloqueado y Mara perdió el control. El barco comenzó a desviarse hacia la sombra.",
      "Tomás habló por radio. —Mara, escucha. El mar empujará hacia aquello que más temes perder. No luches contra él. —Eso no es navegación. —Esta noche sí.",
      "Mara soltó el timón. Pensó en los dieciocho años consumidos por la ausencia de su padre, en la necesidad de rescatarlo y de reconstruir una vida que ya no existía. Dejó que ese miedo tirara del barco. En el último momento encendió el motor de babor. El Argos giró alrededor de su propia sombra y regresó al corredor blanco.",
      "En el Alción, Gael activó el piloto automático. Salvador miró la patrullera de su abuelo. —Nos seguirá hasta el centro. —Eso necesitamos. —Él no sabe que la ruta termina allí. —Tú tampoco lo sabías cuando empezaste.",
      "Salvador abrió un armario de emergencia y entregó un chaleco a Gael. —Hay una lancha en estribor. Cuando lleguemos a la boya negra, salte. —¿Y tú? —Alguien debe impedir que mi abuelo cambie de rumbo. —La culpa no se arregla muriendo —respondió Gael. —Entonces procure recogerme.",
      "La boya negra apareció entre las olas. Gael soltó la lancha y se alejó unos metros. Salvador permaneció en el puente hasta que la patrullera entró detrás del Alción. Bloqueó los mandos y saltó al mar.",
      "Gael regresó contra la corriente y consiguió subirlo a la lancha. Instantes después, el Alción y la patrullera chocaron en el centro de la sombra.",
      "Durante un segundo, Álvaro Veyra vio ante él la ciudad futura que pretendía conquistar. Después, la luz negra borró los dos barcos. No hubo explosión: solo un silencio absoluto y un hueco en el océano.",
      "Las copias de los cálculos de Tomás y todas las grabaciones robadas desaparecieron con el Alción. La sombra había recibido uno de los dos navíos que la despertaron. El puerto de Cádiz recuperó sus luces.",
      "—¡Ahora! —gritó Ezequiel. Tomás activó el mecanismo. Isla Baja se desprendió de 1936 y comenzó a navegar hacia Poniente bajo el haz del faro.",
    ],
  },
  {
    title: "El último rumbo",
    visual:
      "Dos islas fantasmales llenas de habitantes atraviesan un gran haz de luz hacia un horizonte dorado, un farero cruza con ellos mientras un hombre salta desde una torre que desaparece hacia un barco, final épico marítimo",
    paragraphs: [
      "Las casas de Isla Baja se desvanecieron una a una del mar de 1936.",
      "No fueron destruidas. Mara pudo verlas al final del corredor, bajo un cielo distinto. Sus habitantes permanecían en las calles contemplando por primera vez un amanecer que no retrocedería al comenzar el día.",
      "La lente giró una última vez hacia Cárdena. El pueblo de 1958 apareció entre la niebla con sus puertas abiertas. Sus habitantes salieron de los escondites y siguieron la señal de Ezequiel. Las dos islas se reunieron en Poniente, donde el tiempo avanzaría con normalidad aunque ninguna carta pudiera encontrarlas.",
      "Ezequiel abandonó la torre principal y apareció en el límite del corredor. Al otro lado lo esperaban Aurora en el recuerdo de su partida y las personas a las que había protegido durante once meses. —Ven con nosotros —le pidió Inés por radio. —Aurora tuvo una vida en vuestro mundo. Yo quiero tener la mía con quienes quedaron aquí.",
      "Cruzó hacia Poniente. Las dos islas desaparecieron del horizonte.",
      "Solo quedaba cerrar la ruta. —Tomás, es tu turno —dijo Mara. No hubo respuesta.",
      "En Isla Baja, la torre secundaria comenzaba a derrumbarse. Tomás intentaba liberar la palanca que mantenía abierto el corredor. —Está atascada. Si la suelto antes de tiempo, no llegaré.",
      "Mara giró el Argos. —Voy a buscarte. —No. Mantén el rumbo. —No pienso dejarte otra vez. —Tú nunca me dejaste.",
      "Tomás golpeó el mecanismo con una barra de hierro. La palanca cedió y la luz comenzó a apagarse desde el extremo de la isla. Corrió. El corredor desaparecía detrás de él, devorando el muelle, las calles y el acantilado.",
      "Tomás saltó desde la última roca. Mara lanzó una cuerda y su padre la atrapó en el aire. Inés, Gael y Salvador ayudaron a izarlo. En cuanto cayó sobre la cubierta, la última franja de luz se extinguió.",
      "El Faro de la Aguja se quebró. La torre no cayó al mar: se volvió transparente y desapareció, como si nunca hubiera ocupado aquel espacio. La última mancha de luz negra se disolvió con ella.",
      "Tomás comenzó a envejecer. Su cabello se volvió blanco, las arrugas recorrieron su rostro y sus manos. Su cuerpo reclamaba los dieciocho años que el faro le había prestado. Mara lo sostuvo. —Quédate conmigo.",
      "Durante varios segundos no respiró. Después tosió. Cuando volvió a abrir los ojos era un hombre cercano a los setenta años. —Creo que me debes una explicación —dijo Mara. —Varias. —Tienes tiempo. Tomás miró el mar vacío. —Eso espero.",
    ],
  },
  {
    title: "Ninguna carta",
    visual:
      "El barco Argos navega al amanecer sobre un mar sereno, una cartógrafa y su padre anciano observan tres destellos de un faro invisible en el horizonte, final misterioso y esperanzador cinematográfico",
    paragraphs: [
      "Las autoridades encontraron el Argos al amanecer.",
      "Nadie creyó toda la historia. La desaparición del Alción fue atribuida a una tormenta súbita y a una maniobra temeraria. Salvador Veyra sobrevivió para declarar que había ordenado entrar en una zona peligrosa ignorando las advertencias de su tripulación.",
      "Entregó el control de la empresa mientras se investigaba el origen de sus propiedades. El Libro de los Nombres llegó a manos de historiadores y jueces. La sal y el fuego habían dañado algunas páginas, pero cientos de nombres seguían siendo legibles. Familias que llevaban generaciones formulando preguntas encontraron al fin una respuesta.",
      "Los archivos digitales recuperados por Veyra se habían perdido con el Alción. Tomás quemó las últimas coordenadas capaces de abrir las rutas y conservó únicamente una carta sin datos de navegación, dibujada para recordar los lugares que habían salvado.",
      "Gael reparó el Argos. Conservó la franja blanca de la barba y dejó de despertarse cada noche buscando un faro en la ventana.",
      "Inés encontró entre las pertenencias de Aurora una fotografía que nunca había visto. Mostraba a su abuela con doce años, recién llegada a un puerto de la península junto a los dos marineros del Santa Irene. En una mano sostenía la brújula de latón. En el reverso había una frase: «Para Inés, cuando llegue su turno de devolvérmela».",
      "Tomás necesitó meses para acostumbrarse al presente. Aprendió a utilizar un teléfono, descubrió que muchos de sus amigos habían muerto y recorrió una ciudad en la que cada calle guardaba dieciocho años de recuerdos ajenos.",
      "Mara no lo perdonó de inmediato. Empezaron tomando café una vez por semana. Después navegaron juntos.",
      "Un año más tarde, el Instituto Hidrográfico publicó una nueva carta del golfo de Cádiz. Mara la extendió sobre la mesa del Argos. En el punto donde habían encontrado el faro no aparecía tierra alguna. Solo una anotación: «Fenómeno luminoso ocasional. Origen desconocido».",
      "—Sigue sin estar en el mapa —dijo Inés. —Los faros indican peligros —respondió Gael—. Tal vez este sea el peligro. Tomás negó con la cabeza. —Los faros indican que hay alguien al otro lado de la oscuridad.",
      "Esa noche navegaron hasta las coordenadas. El mar estaba en calma. A medianoche apareció una luz en el horizonte. No formaba un corredor ni señalaba ninguna isla. Emitió tres destellos y se apagó.",
      "La radio recibió una voz lejana. Era Ezequiel. —Poniente informa. Isla Baja y Cárdena, todos a salvo. Inés sonrió. —¿Podemos responder? Tomás observó la oscuridad. —No hace falta. Sabe que estamos aquí.",
      "Mara permaneció en cubierta mientras el Argos regresaba a puerto. A ambos lados se extendía un océano sin caminos visibles, pero lleno de lugares que ninguna carta recordaba.",
      "Antes del amanecer creyó distinguir una torre sobre el agua. Duró apenas un instante. Luego salió el sol. Y donde no había tierra, una luz blanca señaló el camino de regreso.",
    ],
  },
];

export const lighthouseChapters: Chapter[] = lighthouseChapterDrafts.map(
  ({ title, paragraphs, visual }, index) => {
    const number = index + 1;
    const wordCount = paragraphs.join(" ").trim().split(/\s+/).length;

    return {
      number,
      title,
      readingMinutes: Math.max(3, Math.ceil(wordCount / 190)),
      paragraphs,
      visuals: [
        {
          id: `el-faro-sin-mapa-capitulo-${number}-imagen-1`,
          afterParagraph: Math.ceil(paragraphs.length / 2),
          alt: `Escena del capítulo ${number}, ${title}, de El faro sin mapa`,
          prompt: visual,
          aspectRatio: "16/9",
          status: "pending",
          url: null,
        },
      ],
    };
  },
);

export const lighthouseReadingMinutes = lighthouseChapters.reduce(
  (total, chapter) => total + chapter.readingMinutes,
  0,
);
