import type { Chapter } from "@/lib/types";

interface StationChapterDraft {
  title: string;
  paragraphs: string[];
  visual: string;
  visualAfter?: number;
}

const stationChapterDrafts: StationChapterDraft[] = [
  {
    title: "El último tren",
    visual:
      "Estación ferroviaria europea vacía de madrugada, panel rojo anunciando TREN 317, una empleada con linterna frente a monitores antiguos y una niña de abrigo amarillo en un andén cubierto de niebla, suspense cinematográfico realista, tonos azul petróleo y ámbar, sin texto",
    paragraphs: [
      "A las tres y diecisiete de la madrugada, el panel de llegadas de la estación de Santa Lucía encendió una línea que llevaba veintidós años apagada. Vera Salvatierra estaba sola en el vestíbulo cuando las letras rojas comenzaron a formar un destino que no figuraba en ningún mapa: TREN 317. PROCEDENCIA DESCONOCIDA. ANDÉN 0. La indicación duró apenas dos segundos, se borró y volvió a aparecer con un parpadeo que tiñó de rojo los cristales de las taquillas.",
      "No debía seguir allí. Su turno en objetos perdidos había terminado cuarenta minutos antes, pero una llamada sin número la había retenido junto al teléfono gris de la oficina. Al otro lado, entre chasquidos de estática, una voz de mujer había pronunciado su nombre y una única frase: «Si el tren aparece, no dejes que abra las puertas». Vera preguntó quién llamaba. Solo obtuvo una respiración breve, un golpe metálico y el rumor lejano de ruedas sobre raíles.",
      "Pensó en una broma hasta que escuchó el silbido. Llegó desde el túnel norte, cerrado desde el incendio de 2004. Primero fue un hilo de aire frío; después, un temblor que hizo vibrar los objetos olvidados en las estanterías: paraguas, maletas, un cochecito de niño. El reloj de pared se detuvo. Las agujas coincidieron en las tres y diecisiete, aunque el móvil de Vera marcaba ya las tres y dieciocho.",
      "Las luces del vestíbulo se apagaron por filas. Vera tomó la linterna de emergencia y corrió hacia el puesto de seguridad. Las doce pantallas habían dejado de mostrar los pasillos de la estación. En todas aparecía la misma imagen granulada: un andén antiguo cubierto de niebla, bancos de madera, anuncios de hacía décadas y una niña de espaldas junto al borde. Llevaba un abrigo amarillo con dos botones negros en el cuello.",
      "Vera dejó caer la linterna. Ella misma había cosido uno de aquellos botones la tarde anterior a la desaparición de su hermana. Lucía tenía dieciséis años en 2004 y aquel abrigo fue lo único que su madre pudo describir a la policía sin romper a llorar. Nunca encontraron el cuerpo. Tampoco apareció entre las cuatro víctimas oficiales del incendio, pero después de meses sin una sola pista todos dejaron de buscarla.",
      "La niña de los monitores levantó lentamente el rostro. No había envejecido un día. Miró directamente a la cámara y movió los labios. Vera se acercó tanto a la pantalla que su aliento empañó el cristal. «No abras», creyó leer. Luego Lucía miró hacia el túnel, aterrada, y echó a correr. Las cámaras volvieron una a una a sus imágenes normales, salvo la número siete, que mostró durante un instante una puerta metálica donde solo debía haber pared.",
      "Un estruendo cruzó bajo el suelo. Vera salió al vestíbulo justo cuando una corriente de aire lanzó papeles y polvo contra las columnas. Detrás del muro que separaba la estación nueva del túnel clausurado pasó una sucesión de ventanas iluminadas. En cada una había pasajeros inmóviles. No vio el tren: vio su luz atravesar la piedra como una sombra proyectada desde el otro lado de la realidad.",
      "El teléfono de objetos perdidos volvió a sonar. Vera regresó y descolgó con las manos temblando. Esta vez no hubo estática. La voz de Lucía sonó tan cerca como cuando compartían dormitorio. «Vera», dijo, «esta vez no te bajes». La comunicación se cortó y, en el auricular, quedó el latido regular de una señal de vía.",
    ],
  },
  {
    title: "Andén cero",
    visual:
      "Escalera de servicio descendiendo hacia un andén ferroviario secreto de 2004, azulejos húmedos, señal con un cero, una mujer y un vigilante alumbrando con linternas, niebla y tensión cinematográfica realista",
    paragraphs: [
      "Marcos Leal encontró a Vera arrodillada junto al teléfono, con el auricular todavía pegado al oído. Era el responsable de seguridad de la noche y la única persona que podía haber visto las mismas imágenes. Sin embargo, cuando revisó la grabación, las cámaras mostraban pasillos vacíos. En la número siete no aparecía ninguna puerta: solo la pared de ladrillo pintada de gris que ambos conocían.",
      "—No estoy imaginándolo —dijo Vera—. Era Lucía. Marcos no se apresuró a contradecirla. Había oído el silbido y aún sostenía en la mano una taza de café agrietada por la vibración. Revisó el registro del teléfono. La llamada constaba como interna y procedía de la extensión 0317, un número que el sistema rechazaba porque ya no existía. Perteneció al antiguo puesto de señales del túnel norte.",
      "Fueron hasta la pared de la cámara siete. A simple vista no tenía nada especial, pero el aire junto al zócalo era varios grados más frío. Marcos pasó un detector por la pintura y descubrió una línea rectangular bajo las sucesivas capas. Vera recordó entonces algo que llevaba años creyendo un sueño: una escalera muy estrecha, la mano de Lucía tirando de ella y una placa blanca con un cero negro.",
      "El cerrojo estaba oculto detrás de la carcasa de un extintor. No tenía ranura para una llave moderna, sino una hendidura circular del tamaño de una moneda. Vera metió la mano en el bolsillo de su chaqueta buscando el móvil y tocó un objeto de latón. Era una ficha ferroviaria vieja, con el número 24 troquelado. Estaba segura de no haberla visto antes. Al acercarla al cerrojo, el metal vibró y la puerta se abrió hacia dentro con un suspiro de aire estancado.",
      "La escalera descendía más de lo que permitía la altura entre plantas. Bajaron sesenta y tres peldaños mientras el ruido de la estación moderna desaparecía sobre sus cabezas. Al final encontraron un andén enterrado, revestido de azulejos color marfil. Los carteles anunciaban cafeterías cerradas hacía décadas. En una columna, bajo una costra de hollín, sobrevivía el círculo blanco con el número 0.",
      "Había veinticuatro marcas verticales raspadas en la pared. Veintitrés estaban cruzadas por una línea horizontal. La última, separada de las demás, terminaba en una flecha que apuntaba hacia la vía. Marcos fotografió las marcas. En la pantalla del móvil aparecieron palabras que a simple vista no estaban allí: «FALTA UNA». Antes de que pudiera enseñárselo a Vera, el teléfono se apagó con la batería completamente cargada.",
      "Una luz se encendió al fondo del túnel. No era blanca, sino amarillenta, como los faros de los trenes antiguos. Vera quiso acercarse al borde, pero Marcos la sujetó. El convoy atravesó el andén sin mover el aire. Vagones verdes, ventanillas empañadas, rostros detenidos en una misma expresión. En la tercera ventana, Lucía golpeaba el cristal con ambas manos. Tras ella, un hombre con uniforme ferroviario intentaba alcanzar el freno de emergencia.",
      "El tren desapareció en la boca opuesta y el silencio regresó de golpe. Entonces alguien aplaudió una sola vez desde el extremo del andén. Bajo la luz de emergencia esperaba un hombre alto, muy viejo, vestido con un abrigo gris. «Has tardado veintidós años, Vera», dijo. En una mano sostenía una llave de señales; en la otra, una fotografía de ella y Lucía tomada la noche del incendio.",
    ],
  },
  {
    title: "El hombre del abrigo gris",
    visual:
      "Hombre anciano con abrigo gris y llave ferroviaria antigua al final de un andén secreto, mujer con ficha de latón y guardia frente a él, luces de emergencia rojas, thriller realista y oscuro",
    paragraphs: [
      "El anciano se presentó como Esteban Vela, aunque Vera ya había leído ese nombre cientos de veces. En 2004 era el jefe de circulación de Santa Lucía y la última persona que habló con el maquinista del tren 317. Declaró que el convoy había salido de la estación antes del incendio. Tres meses después abandonó el ferrocarril y desapareció de la vida pública. Los investigadores nunca lograron localizarlo para una segunda declaración.",
      "Marcos le ordenó que dejara la llave en el suelo. Esteban sonrió sin humor. «Si me detienes, condenas a todos los que van ahí dentro». Señaló el túnel por el que el tren acababa de desvanecerse. Explicó que solo aparecía durante diecisiete segundos cada madrugada, pero aquella noche era distinta. Las luces, el panel y la puerta abierta indicaban que el circuito estaba perdiendo estabilidad. Al amanecer el tren entraría por completo en la estación una sola vez.",
      "—Entonces abriremos las puertas —dijo Vera. Esteban dio un paso brusco hacia ella. Marcos se interpuso. «Si las abrís mientras el tren siga entre fases, no saldrá vuestra familia. Saldrán sus restos». No quiso explicar qué significaba. Miró la ficha de latón que Vera apretaba en la palma y su expresión cambió. La llamó billete de retorno y aseguró que llevaba buscándolo desde el incendio.",
      "Vera escondió la ficha en el puño. Le preguntó por Lucía, por los veintitrés nombres borrados de los informes y por la fotografía. Esteban la dejó caer entre ambos. Mostraba a las hermanas frente al tren 317: Lucía, con el abrigo amarillo; Vera, de once años, sujetando dos billetes; detrás de ellas, su padre Gabriel con el uniforme de ingeniero de señales. En el margen constaba la hora: 03:09 del 14 de noviembre de 2004.",
      "Los recuerdos llegaron como cristales. Una alarma. Humo bajando del techo. Lucía empujándola dentro de un vagón. Su padre gritando desde el andén. Después, una mano adulta tiró de Vera en el último instante y la hizo caer fuera del tren. Siempre había creído que aquella mano era la de Gabriel. Al mirar la fotografía comprendió que el hombre del abrigo gris llevaba el mismo anillo ancho que asomaba en su recuerdo.",
      "—Fuiste tú quien me sacó. Esteban no lo negó. Dijo que Vera no debía estar a bordo, que su presencia impedía cerrar «el circuito». Cuando Marcos le exigió una explicación, las lámparas del andén comenzaron a parpadear. Esteban aprovechó la oscuridad, golpeó a Marcos con el hombro y trató de arrebatarle la ficha a Vera. Ella le clavó las uñas y sintió bajo la manga del abrigo una cicatriz profunda, circular, idéntica a la que tenía en su propia muñeca.",
      "Marcos recuperó el equilibrio, pero Esteban ya corría hacia un corredor lateral. Vera lo siguió hasta una puerta con el rótulo SEÑALES NORTE. El anciano la cerró desde el otro lado. Antes de alejarse dijo algo a través del metal: «Yo también tengo a alguien en ese tren. Mi hijo Daniel ocupa el asiento veintidós. Si debo elegir entre él y tu hermana, ya sabes qué puerta abriré».",
      "Al volver al andén, Vera encontró la fotografía boca abajo. En el reverso había una lista escrita por Gabriel. Veintitrés nombres, un número de asiento junto a cada uno y una frase subrayada dos veces: NO PERMITIR LA APERTURA EN ANDÉN CERO. El último nombre era Lucía Salvatierra, asiento 23. Debajo quedaba una línea en blanco junto al número 24.",
    ],
  },
  {
    title: "Una voz en la megafonía",
    visual:
      "Altavoces antiguos de estación y cabina de megafonía abandonada, una mujer escucha la voz de su hermana mientras un tren espectral cruza monitores, luz verde enfermiza, suspense cinematográfico",
    paragraphs: [
      "La megafonía despertó cuando regresaban por la escalera. Primero sonó una campanilla de dos tonos, la misma que precedía a los anuncios en las viejas grabaciones de la estación. Después una voz femenina recitó números sin aparente orden: «Trece. Cero. Veinticuatro. Norte». Marcos grabó el mensaje. Vera no necesitaba escucharlo de nuevo para reconocer a Lucía.",
      "La voz volvió, deformada por ecos. «No confiéis en el hombre gris. Tampoco dejéis que suba». Las últimas palabras se hundieron bajo un chirrido de ruedas. Marcos localizó la señal en el sistema analógico de emergencia, una red de cables de cobre que seguía instalada pero no recibía corriente desde la reforma de 2008. Alguien, o algo, la estaba alimentando desde el túnel clausurado.",
      "Subieron hasta la antigua cabina de megafonía. El cuarto se usaba como almacén y olía a papel húmedo. Detrás de cajas de horarios encontraron un panel de clavijas, un micrófono de cuello flexible y una cinta de bobina que giraba sin motor. Vera pulsó la tecla de emisión. «Lucía, soy yo». Durante diecisiete segundos solo se oyó el paso rítmico del tren. Luego llegó una respuesta entrecortada: «Sé que eres tú. Te veo cada vez».",
      "Vera preguntó cuánto tiempo llevaba dentro. «Diecisiete minutos», contestó Lucía. Después corrigió: «Diecisiete minutos muchas veces». Dijo que los pasajeros despertaban al entrar en el túnel, revivían el humo, la frenada y la oscuridad, y volvían al principio. La mayoría olvidaba cada repetición. Ella no, porque conservaba la mitad de un billete en el bolsillo. Gabriel también recordaba, añadió, pero el resto de la frase quedó enterrado en estática.",
      "—¿Papá está contigo? La bobina aceleró. Una voz masculina gritó algo desde muy lejos. Lucía respondió apresuradamente: «Busca lo que dejó en la taquilla trece. El reloj abre la puerta. Cuando se apaguen las luces del norte tendrás tres minutos. Y, Vera...». La transmisión se quebró. En el último fragmento se distinguía una advertencia: «No vuelvas a ocupar tu asiento».",
      "Marcos encontró en un archivador el plano de las taquillas antiguas. La número trece no estaba en la sala pública, sino en el pasillo de personal destruido por el incendio. Mientras copiaba la ubicación, Vera vio movimiento tras el cristal de la cabina. Una figura con uniforme se encontraba en el corredor. Tenía la piel gris de ceniza y una quemadura que le atravesaba el rostro. Levantó un dedo hasta los labios y señaló el altavoz.",
      "La figura desapareció cuando Marcos se volvió. En el suelo quedó una tarjeta de interventor a nombre de Julián Costa, uno de los desaparecidos del tren. La fecha de caducidad era diciembre de 2004. En el reverso alguien había escrito con bolígrafo: «No somos fantasmas. Todavía no». Vera guardó la tarjeta junto a la fotografía y sintió que el mundo conocido se estrechaba alrededor de una única hora.",
      "A las tres y treinta y cuatro, exactamente diecisiete minutos después de la aparición, todos los relojes de la estación emitieron un chasquido. Sus agujas retrocedieron hasta las tres y diecisiete. Solo uno siguió avanzando: el viejo reloj de pulsera de Gabriel, expuesto desde hacía años en la vitrina de objetos sin reclamar. Vera lo había catalogado aquella misma semana sin saber que era suyo.",
    ],
  },
  {
    title: "El reloj detenido",
    visual:
      "Primer plano de un reloj ferroviario detenido a las 3:17 sobre planos quemados y una cinta de vídeo, manos de una mujer abriendo un compartimento secreto, iluminación ámbar y azul, misterio realista",
    paragraphs: [
      "El reloj tenía el cristal roto y la correa endurecida por el fuego. Vera recordaba que su madre recibió una caja con las pertenencias de Gabriel, pero aquel objeto no estaba dentro. Según la etiqueta de la vitrina, alguien lo depositó en objetos perdidos hacía tres días. No figuraba nombre ni firma. Marcos forzó con cuidado la tapa posterior y descubrió bajo el mecanismo una llave plana, casi tan fina como una aguja.",
      "La taquilla número trece se encontraba detrás de un tabique provisional en el ala norte. El pasillo conservaba las cicatrices del incendio: azulejos cuarteados, metal retorcido y manchas negras que ninguna reforma había cubierto. En la cerradura había un pequeño orificio circular. Vera introdujo la corona del reloj y oyó girar engranajes dentro de la pared. No se abrió una taquilla, sino un panel entero.",
      "Dentro aguardaban una cinta de vídeo, un cuaderno chamuscado y un sobre dirigido a VERA, SI EL RELOJ VUELVE A ANDAR. También había recortes de prensa. El titular del 15 de noviembre de 2004 hablaba de cuatro muertos y de una avería que había obligado a evacuar la estación. En otro periódico, publicado antes de que alguien retirara la edición, se leía: «Desaparece un tren con veintitrés pasajeros durante el incendio de Santa Lucía».",
      "Marcos conectó un reproductor guardado en el almacén. La cinta mostró una cámara de servicio a las 03:09. Vera y Lucía entraban en el vagón seis mientras Gabriel discutía en el andén con Esteban. El vídeo no tenía sonido, pero el jefe de circulación señalaba con furia a un joven que acababa de subir: Daniel Vela. Después empezaba a salir humo de un armario eléctrico y las puertas del tren se cerraban.",
      "Gabriel corría hacia la cabina. Esteban accionaba una palanca en el puesto de señales. En la imagen siguiente, Vera golpeaba una puerta desde dentro. Esteban la abría con una llave manual, la agarraba del brazo y la arrojaba al andén. Lucía intentaba seguirla, pero las hojas se cerraban entre ambas. El tren arrancaba hacia un túnel que en los planos oficiales terminaba a cuatrocientos metros.",
      "La última secuencia estaba grabada desde la locomotora. Gabriel aparecía frente a la cámara, cubierto de hollín. «Si alguien encuentra esto, la derivación Umbral ha fallado. Esteban ha enviado el 317 a la vía de contención y el incendio ha sobrecargado los inductores. No intentéis detenerlo en el andén. Debe completar la salida sur o el tiempo acumulado caerá sobre los pasajeros». Miró hacia atrás, como si oyera acercarse el tren. «Mis hijas están dentro. Voy a subir».",
      "El vídeo terminó. Vera abrió el sobre con el pulso desbocado. Solo contenía un esquema incompleto de tres desvíos y una frase escrita por su padre: «Un billete de ida mantiene la puerta cerrada. Dos mitades de retorno pueden traerlos a casa». En una esquina había dibujado el reloj y tres líneas convergentes: NORTE, CATEDRAL, RÍO.",
      "Entonces el reloj de Gabriel empezó a andar. El segundero dio una vuelta completa y se detuvo a las tres y dieciocho. Al mismo tiempo, el panel de la estación se iluminó sobre sus cabezas: TREN 317. LLEGADA PREVISTA 05:41. Faltaban menos de dos horas y media. Al pie del anuncio apareció una cuenta atrás, y el primer minuto comenzó a consumirse.",
    ],
  },
  {
    title: "Billete de ida",
    visual:
      "Billete ferroviario de 2004 con asiento 24 y borde rasgado sobre una caja de música abierta, apartamento oscuro, fotografía de dos hermanas y luz de farolas entrando por la ventana, thriller realista",
    paragraphs: [
      "El cuaderno de Gabriel estaba escrito con abreviaturas técnicas, pero en la última página Vera encontró una dirección: el piso en el que había vivido con su familia. Tras la muerte de su madre, tres años antes, nadie había vuelto a entrar. Conservaba las llaves por una mezcla de culpa y pereza; aquella noche comprendió que Gabriel había contado con ello.",
      "Marcos quiso acompañarla, aunque el tiempo se agotaba. Condujeron por calles vacías mientras la cuenta atrás se repetía en las pantallas de las marquesinas y desaparecía al acercarse cualquier otro vehículo. No era un aviso público. El tren se lo estaba mostrando solo a Vera. A las cuatro menos diez faltaban ciento once minutos para la llegada.",
      "El piso olía a muebles cerrados. En el dormitorio que las hermanas compartieron seguían las estrellas fluorescentes del techo y una marca de lápiz con sus alturas. Vera abrió el armario de Lucía. El hueco del abrigo amarillo permanecía entre dos perchas, tan limpio que parecía reciente. En el fondo encontró una caja de música con la bailarina arrancada y el mismo círculo de latón que llevaba troquelado su ficha.",
      "Al colocar la ficha en el mecanismo, sonó una melodía infantil y se levantó un doble fondo. Dentro había un billete de cartón: SANTA LUCÍA–PUERTO SUR, TREN 317, ASIENTO 24, a nombre de Vera Salvatierra. Una esquina estaba cortada en diagonal. En el reverso, Gabriel había escrito: «Este era tu billete de ida. Lucía guarda la vuelta. Juntas forman la salida».",
      "Vera recordó por fin la noche entera. Ella había subido al 317 para impedir que Lucía viajara sola después de una discusión con su madre. Gabriel llegó al andén buscándolas justo cuando empezó el incendio. Esteban no salvó a Vera por compasión: la arrancó del vagón porque el prototipo solo podía admitir veintitrés ocupantes. Al dejarla fuera cerró el circuito, con su propio hijo y Lucía todavía dentro.",
      "El espejo del armario reflejó una silueta en la puerta. Esteban los había seguido. Llevaba una pistola de señales y mantenía la llave de desvío colgada al cuello. «Daniel quería escapar de mí», dijo. «Iba a marcharse en ese tren. Solo pretendía retenerlo diecisiete minutos, el tiempo necesario para que la policía llegara a la siguiente estación. No sabía que el fuego convertiría la vía de contención en una jaula».",
      "Pidió el billete. Prometió usarlo para sacar a los pasajeros, pero sus ojos no se apartaban del nombre de Daniel escrito en la fotografía. Marcos volcó una estantería entre ambos. La pistola disparó una bengala que prendió las cortinas, y durante unos segundos el dormitorio volvió a llenarse del mismo humo de 2004. Vera y Marcos escaparon por la cocina mientras Esteban apagaba las llamas para que no consumieran el billete que creía aún en la caja.",
      "En la calle, Vera abrió la mano. Había guardado el cartón dentro de la funda de su móvil. Una nueva línea acababa de aparecer bajo su nombre: RETORNO SUJETO A VALIDACIÓN. En el borde rasgado se dibujaban media fecha y media palabra. La otra mitad seguía veintidós años lejos, en el bolsillo del abrigo amarillo de Lucía.",
    ],
  },
  {
    title: "La taquilla número trece",
    visual:
      "Cámara secreta detrás de una taquilla ferroviaria quemada, grabadoras de bobina, planos técnicos del Proyecto Umbral y luces de emergencia, dos investigadores observan un modelo de vías imposible, realismo cinematográfico",
    paragraphs: [
      "Regresaron a Santa Lucía por el acceso del aparcamiento. La policía ya esperaba en la entrada principal: Esteban había denunciado el robo de material histórico y descrito a Vera como una exempleada inestable. Marcos apagó su radio antes de que seguridad pudiera localizarlo. Conocía un conducto de equipajes que desembocaba detrás de la taquilla trece.",
      "El panel que habían abierto ocultaba una segunda cerradura. Esta vez hicieron falta el reloj y el billete: la corona encajó en un orificio y el cartón en una ranura horizontal. Al girar ambos, el fondo de la taquilla retrocedió. Apareció una habitación protegida del fuego, llena de instrumentos analógicos, cintas etiquetadas y una maqueta circular de la red ferroviaria.",
      "Una placa identificaba el lugar como PUESTO DE ENSAYO UMBRAL. El proyecto había sido diseñado a finales de los noventa para despejar una vía en caso de atentado o colisión. Mediante tres anillos electromagnéticos, un tren podía desviarse a un tramo de contención durante diecisiete minutos y regresar al mismo punto apenas un segundo después. No viajaba al pasado: quedaba aislado del tiempo exterior mientras repetía un recorrido cerrado.",
      "Gabriel había grabado instrucciones después de detectar fallos en las primeras pruebas. En una cinta explicaba que el sistema necesitaba una lista exacta de ocupantes. Los billetes eran parte del control de masa; cada validación actuaba como ancla. Esteban había retirado a Vera para ajustar el tren al límite de veintitrés personas, pero el incendio fundió el temporizador antes de que pudiera ordenar el regreso.",
      "La voz de Gabriel se volvió más baja. «Si el ciclo supera una hora, no abráis las puertas dentro de la contención. El cuerpo intentará recuperar de golpe el tiempo que el campo le ha negado. Debéis invertir los tres desvíos durante un apagón completo y llevar el convoy hasta la salida sur. La persona que falta en el manifiesto tendrá que validar la ida desde dentro. La persona que conserva la vuelta deberá validarla al final».",
      "Vera comprendió la advertencia de Lucía. El sistema seguía considerándola la pasajera número veinticuatro aunque Esteban la hubiera sacado. Si subía, podía completar el manifiesto y permitir el cambio de vía; si no conseguían salir, quedaría incorporada al siguiente ciclo. Marcos señaló tres luces en la maqueta: Norte, Catedral y Río. Solo la primera seguía encendida.",
      "Otra cinta contenía un mensaje de Marta Dávila, directora técnica de Umbral. Afirmaba que había ordenado cancelar el proyecto una semana antes del incendio y que Esteban conservó ilegalmente una llave maestra. «Si las luces del norte vuelven a encenderse, buscadme en el kilómetro 0,8», decía. «No sigáis ninguna instrucción digital. El circuito aprende de quienes quedan dentro y puede imitar sus voces».",
      "La observación dejó a Vera helada. Tal vez no había hablado con Lucía, sino con algo que usaba sus recuerdos para atraerla al asiento vacío. Sobre la mesa, el teléfono analógico sonó. Vera lo dejó repicar seis veces antes de contestar. Una niña cantó la melodía de la caja de música y añadió un verso que solo las hermanas conocían. Después dijo: «Vera, él está a punto de abrir la primera puerta».",
    ],
  },
  {
    title: "Nadie recuerda a Vera",
    visual:
      "Mujer sola en el vestíbulo de una estación mientras empleados y cámaras no la reconocen, su ficha desaparece de pantallas digitales y detrás se superpone una fotografía memorial de 2004, atmósfera inquietante realista",
    paragraphs: [
      "Salieron de la cámara secreta y encontraron a Sonia, la supervisora de turno, acompañada por dos agentes. Vera levantó las manos y empezó a explicarse, pero Sonia la miró sin rastro de reconocimiento. Llevaban cinco años trabajando juntas. Aun así, preguntó quién era y por qué vestía un uniforme de la estación. En el bolsillo de Vera, su tarjeta laboral se había vuelto una lámina blanca.",
      "Marcos trató de defenderla. Sonia recordó su nombre, aunque no que hubiera entrado de servicio esa noche. Los agentes consultaron la documentación de Vera. El sistema devolvió una inscripción de defunción fechada el 14 de noviembre de 2004: VERA SALVATIERRA RUIZ, once años, víctima no recuperada del incendio de Santa Lucía. Su vida adulta —estudios, contratos, domicilio— se deshacía en cada base de datos que abrían.",
      "El tren no solo estaba acercándose. Estaba corrigiendo el exterior para recuperar a la pasajera que figuraba en su manifiesto original. Los recuerdos digitales desaparecían primero; después comenzaban a ceder los humanos. Sonia apartó la vista un instante y, cuando volvió a mirar, preguntó de nuevo quién era Vera. Uno de los agentes llevó la mano a las esposas.",
      "Marcos activó la alarma de incendios. Las puertas de emergencia se abrieron y el vestíbulo se llenó de viajeros desalojados de los primeros trenes de la mañana. Escaparon entre la multitud. Cada pantalla que cruzaban mostraba durante un segundo el rostro de Vera a los once años y la palabra EMBARQUE. Ella intentó llamar a vecinos y antiguos compañeros. Ninguno reconoció su voz.",
      "—Yo sí te recuerdo —dijo Marcos. Se había escrito con rotulador en el antebrazo: VERA. LUCÍA. TREN 317. NO OLVIDAR. También llevaba en el bolsillo la fotografía en papel, el reloj y una grabadora analógica. «Quizá mañana piense que eres una desconocida, pero ahora sé lo que he visto». Vera quiso agradecerlo y descubrió que no encontraba el apellido de Marcos. El olvido ya trabajaba en ambas direcciones.",
      "Se refugiaron en una sala de mantenimiento sin conexión a la red. La cuenta atrás marcaba setenta y cuatro minutos. En el cuaderno de Gabriel, la dirección del kilómetro 0,8 estaba acompañada por un croquis del túnel norte. Para llegar hasta Marta debían cruzar el tramo clausurado y pasar junto al anillo que mantenía atrapado al tren.",
      "La megafonía anunció una incidencia y pidió evacuar la estación. A continuación, la voz de Esteban ocupó todos los altavoces: «Vera ya no existe. Si sigue avanzando, el circuito borrará también a quienes la ayuden. Entrégame el billete y sacaré a Daniel sin poner en peligro a nadie más». Marcos arrancó de la pared el altavoz más cercano.",
      "Vera miró su reflejo en una puerta de acero. Por un instante vio a la niña de once años, cubierta de hollín, con una herida circular en la muñeca. La niña apoyó la palma desde el otro lado y movió los labios: «Falta una». Cuando la imagen volvió a ser la suya, Vera comprendió que solo tenía dos opciones: permitir que el tren la borrara o subir a él y obligarlo a devolver todo lo que había robado.",
    ],
  },
  {
    title: "El túnel clausurado",
    visual:
      "Dos personas avanzan con linternas por un túnel ferroviario clausurado, raíles cubiertos de ceniza, ecos translúcidos de un tren de 2004 y un anillo electromagnético al fondo, suspense realista",
    paragraphs: [
      "Entraron en el túnel por una compuerta de ventilación. Marcos llevaba herramientas, una batería portátil y la grabadora; Vera, el billete dentro de una bolsa impermeable. Tras cien metros, las luces modernas quedaron atrás. En el suelo, el polvo conservaba huellas recientes de un bastón: Esteban iba delante.",
      "La vía terminaba contra un muro de hormigón según todos los planos. Sin embargo, al acercarse, el haz de las linternas atravesó la superficie. Era una imagen sin consistencia, una máscara proyectada por el campo de Umbral. Cruzaron y encontraron dos raíles que descendían en espiral bajo la ciudad. Las paredes estaban cubiertas por una escarcha negra que quemaba al tocarla.",
      "Cada diecisiete segundos el túnel cambiaba. Por un parpadeo aparecían cables nuevos, lámparas encendidas y técnicos vestidos con uniformes de 2004. Luego todo volvía a la ruina. Eran restos del mismo instante repetido millones de veces. En uno de aquellos destellos, Vera se vio a sí misma corriendo junto a Lucía. Trató de alcanzarlas, pero su mano pasó a través de las dos niñas como a través de humo frío.",
      "Más adelante encontraron el puesto desde el que Esteban había accionado la derivación. Una grabación automática seguía repitiéndose en el altavoz: «Clave de masa incorrecta. Veinticuatro validaciones. Capacidad máxima: veintitrés». Después sonaba la voz del joven Esteban: «Retirad a la niña del asiento 24 y ejecutad el cierre». No había sido un accidente instintivo, sino una decisión consciente.",
      "Un rugido se acercó por la espalda. El 317 surgió sin faros, silencioso al principio y ensordecedor cuando compartió su misma fase. Marcos empujó a Vera dentro de un nicho. Los vagones pasaron a centímetros. Ella alcanzó a ver escenas distintas en cada ventana: pasajeros dormidos, pasajeros gritando, los asientos vacíos, Lucía ya de pie. En la última ventana, Gabriel miró directamente hacia ellos y señaló hacia el norte.",
      "La succión del tren arrancó la mochila de Marcos y la lanzó a la vía. La grabadora quedó atrapada bajo una rueda que todavía no existía del todo. Al partirse, reprodujo a velocidad deformada todas las voces captadas esa noche. Una de ellas no pertenecía a Lucía ni a Gabriel. Era la propia voz de Vera diciendo: «Catedral antes que Norte». Aún no había pronunciado esas palabras.",
      "Llegaron a una bifurcación. El croquis indicaba la derecha, pero las huellas de Esteban seguían por la izquierda. Vera eligió el mapa. Tras una curva encontraron una puerta blindada con la inscripción KM 0,8 y una luz azul que latía al ritmo del tren. Detrás alguien descorrió tres cerrojos antes de que llamaran.",
      "Una mujer de cabello blanco, máscara de soldadura y bastón metálico los apuntó con una pistola de clavos. «Si sois una imitación, no podréis contestar», dijo. Miró a Vera. «¿Qué te dijo Gabriel antes de que ese tren partiera?». Vera cerró los ojos. El recuerdo regresó limpio: su padre, al otro lado del cristal, le había gritado «cuida de tu hermana mayor». La mujer bajó el arma. «Entonces llegas veintidós años tarde, pero aún llegas a tiempo».",
    ],
  },
  {
    title: "Las luces del norte",
    visual:
      "Cámara electromagnética subterránea con tres grandes anillos de luz azul alrededor de una vía, ingeniera anciana ante controles analógicos y un tren atrapado como estela luminosa, ciencia ficción contenida y realista",
    paragraphs: [
      "Marta Dávila había cumplido setenta y seis años esperando aquella madrugada. Fue la directora técnica de Umbral y la persona que firmó su cancelación. Cuando la compañía y el ministerio ocultaron la desaparición, guardó copias de los planos y convirtió el kilómetro 0,8 en un observatorio clandestino. Cada noche medía el pulso del tren; cada año enviaba a Vera una carta que nunca llegó porque Esteban interceptaba cualquier contacto.",
      "La cámara se abría detrás de ella como el interior de una catedral industrial. Tres anillos rodeaban la vía y lanzaban arcos azules hacia un convoy que solo se distinguía como una estela. Las «luces del norte» eran el primer desvío. Llevaban veintidós años encendidas con la energía residual del incendio y con pequeñas descargas que Marta introducía para evitar el colapso.",
      "Marta confirmó las reglas. Abrir una puerta dentro del anillo rompería la protección individual de cada pasajero. No envejecerían veintidós años de forma normal; sus células intentarían ocupar simultáneamente todos los estados negados por el bucle. El resultado sería una desintegración rápida. Solo cuando los tres desvíos formasen una línea y el tren alcanzara la salida sur podrían bajar sin pagar aquella deuda.",
      "Para reordenar la ruta necesitaban un apagón de tres minutos. Marcos podía provocarlo desde la subestación principal. Marta operaría Norte; una consola remota controlaba Catedral y el cambio de Río debía accionarse a mano desde la locomotora. El billete de Vera permitiría subir al convoy durante la oscuridad. La mitad de Lucía validaría la salida. Faltaba la llave maestra de Esteban para desbloquear el sistema.",
      "Vera preguntó si las llamadas podían ser imitaciones. Marta admitió que el circuito había aprendido voces y recuerdos, pero señaló un osciloscopio. La señal de Lucía contenía pequeñas variaciones, decisiones nuevas en cada vuelta. «Una máquina repite. Tu hermana está cambiando el mensaje. Sigue ahí, y lleva años buscando una combinación que consiga llegar hasta ti».",
      "En una pantalla analógica apareció el interior del vagón seis. Lucía escribía con el dedo sobre el cristal empañado: 05:23, PUERTA 4. Gabriel cruzó detrás de ella con uniforme de ingeniero y sangre en la frente. No había envejecido. Vera apoyó la mano sobre la imagen. En ese momento se encendió una luz roja: alguien estaba introduciendo la llave maestra en el control de andén cero.",
      "Esteban habló por el interfono. Había tomado el puesto de señales y bloqueado las salidas. Dijo que no esperaría otro plan ni otro ciclo. A las cinco y veintitrés abriría la puerta cuatro durante los diecisiete segundos de materialización, sacaría a Daniel y dejaría que el tren continuase. Marta le suplicó que recordara las pruebas con animales. Él desconectó la comunicación.",
      "Faltaban nueve minutos. Marta encendió los anillos del norte a máxima potencia, y toda la cámara se llenó de una aurora azul. «Si abre esa puerta, no podremos estabilizar el siguiente paso», advirtió. Vera guardó su billete y echó a correr hacia el andén cero. Por primera vez aquella noche no iba detrás de una aparición: iba a impedir una muerte.",
    ],
  },
  {
    title: "Un pasajero menos",
    visual:
      "Puerta de un tren antiguo abriéndose entre destellos azules en un andén secreto, un joven dentro, un anciano intentando alcanzarlo y una mujer corriendo para impedirlo, tensión extrema, realismo cinematográfico",
    paragraphs: [
      "Vera llegó al andén cero cuando el reloj marcó las cinco y veintitrés. Esteban había conectado cables desde el puesto de señales hasta una caja abierta junto a la vía. La llave maestra ocupaba el centro del mecanismo. En el túnel crecía una luz amarilla y el aire olía a metal después de una tormenta.",
      "—Daniel —llamó el anciano por el micrófono—. Ponte frente a la puerta cuatro. Voy a sacarte. El tren entró en el andén como una fotografía revelándose. Primero aparecieron las luces; después los contornos verdes de los vagones y, por último, los pasajeros. Un joven de dieciocho años se acercó al cristal. Tenía el mismo mentón de Esteban y una chaqueta vaquera pasada de moda.",
      "Vera se lanzó sobre la caja de control. Esteban la apartó con el bastón y giró la llave. La puerta cuatro se abrió apenas un palmo. Del interior salió una ráfaga helada cargada de voces superpuestas. Daniel extendió una mano, pero antes de tocar a su padre su piel comenzó a cubrirse de líneas oscuras. Vera gritó que se apartara.",
      "Julián Costa, el interventor de la tarjeta, apareció detrás del muchacho. Lo empujó hacia el vagón y ocupó su lugar en el umbral. Durante un segundo miró a Vera con una calma terrible. «Ahora sois veintitrés», dijo. Después tiró de la puerta desde fuera para cerrarla, pero el campo lo había atrapado entre ambos tiempos.",
      "Su uniforme perdió el color. El cabello se volvió blanco, la piel se llenó de grietas luminosas y su cuerpo pareció multiplicarse en cientos de posturas transparentes. No cayó ni gritó: se deshizo en una nube de ceniza que el tren arrastró hacia el túnel. La tarjeta que Vera guardaba en el bolsillo se calentó hasta quemarla y quedó completamente en blanco.",
      "Esteban soltó un alarido y trató de abrir de nuevo. Vera arrancó la llave maestra mientras Marcos desconectaba los cables. La puerta se cerró sobre la mano extendida de Daniel sin llegar a tocarla. El convoy perdió consistencia y pasó a través del extremo del andén. Dentro, Lucía golpeaba el cristal y señalaba el asiento vacío de Julián.",
      "La vía comenzó a hundirse. Sin el interventor, el sistema contaba veintidós masas donde debía haber veintitrés. Cada vuelta aumentaría el error hasta romper los anillos. Marta habló por el comunicador: «Julián ha creado una vacante real. El tren intentará llenarla con la única pasajera validada que permanece fuera». Todas las luces se volvieron hacia Vera como ojos.",
      "El suelo cedió antes de que pudieran alcanzar la escalera. Vera, Marcos y Esteban cayeron junto con una sección del andén. Descendieron entre cables, azulejos y polvo hasta una bóveda que no aparecía en ningún plano moderno. Sobre ellos, el 317 dio otra vuelta. Esta vez su silbido sonó más grave, como si la estación entera hubiese empezado a respirar.",
    ],
  },
  {
    title: "La ciudad bajo las vías",
    visual:
      "Gran estación ferroviaria subterránea abandonada bajo una ciudad, arcos de ladrillo, vías antiguas, carteles de distintas épocas y tres personas entre polvo y linternas, misterio de exploración realista",
    paragraphs: [
      "Cayeron sobre el tejado oxidado de un vagón de madera. Marcos se abrió la ceja; Esteban perdió el bastón, pero ninguno se rompió un hueso. Cuando el polvo se asentó descubrieron una estación mucho más antigua que Santa Lucía. Cinco andenes se extendían bajo bóvedas de ladrillo, unidos por pasadizos que continuaban en todas direcciones.",
      "Era la terminal original del siglo XIX, sepultada cuando la ciudad construyó encima. Durante décadas había servido como red de carga, refugio de guerra y laboratorio de Umbral. Había señales de todos esos tiempos: camillas, cajas de munición vacías, bobinas electromagnéticas y mapas cuyos nombres correspondían a calles situadas veinte metros sobre sus cabezas.",
      "Esteban recuperó el bastón y culpó a Vera por la muerte de Julián. Ella le puso la llave maestra delante del rostro. «Lo mató la puerta que tú abriste». El anciano no respondió. A lo lejos, el tren volvió a pasar y una onda de presión recorrió las bóvedas. Varios ladrillos cayeron. El circuito no resistiría mucho más.",
      "Marcos encontró una pared cubierta de frases. Estaban escritas con carbón, tiza, sangre seca y puntas metálicas. Algunas se repetían miles de veces: NO ABRÁIS; DIECISIETE MINUTOS; VERA, PUERTA CUATRO. Otras formaban una conversación entre pasajeros que nunca habían podido verse fuera del tren y trabajadores del laboratorio. Lucía había utilizado los ecos temporales para dejar instrucciones en el pasado de la estación.",
      "Una línea reciente decía: «JULIÁN ELEGIRÁ. SU ASIENTO QUEDARÁ LIBRE. VERA DEBE OCUPARLO ANTES DEL ÚLTIMO CICLO». Debajo, con una letra distinta, Gabriel había añadido: «Entonces la masa será correcta, pero la salida exigirá dos validaciones simultáneas». Vera comprendió que Lucía llevaba repitiendo la noche no solo para pedir ayuda, sino para construir paso a paso la única versión en la que todos los demás sobrevivían.",
      "Marta descendió por una escalera de servicio y examinó la pared. Calculó que quedaban dos ciclos estables. El primero comenzaría a las cinco y veinticuatro; el último terminaría con la llegada anunciada a las cinco y cuarenta y una. Si Vera no estaba dentro para entonces, el campo la absorbería de cualquier modo y borraría todo lo que hubiese vivido desde 2004.",
      "Esteban miró el nombre de Daniel repetido entre las marcas. Encontró una frase de su hijo: «PAPÁ, NO ABRAS. ESTA VEZ ESCÚCHAME». Apoyó los dedos en las letras y por primera vez pareció un hombre cansado, no una amenaza. Admitió que había escuchado mensajes semejantes durante años, pero siempre creyó que Marta los fabricaba para impedirle actuar.",
      "Sobre un plano de la estación enterrada, las líneas Norte, Catedral y Río formaban un triángulo. En el centro había una zona borrada por el incendio. Marta señaló la ceniza adherida al papel: contenía polvo ferromagnético de los primeros inductores. Si lograban reproducir el pulso del tren, las partículas podrían revelar la ruta que Gabriel ocultó. Solo quedaban sesenta y siete minutos para hacerlo y colocar a cada uno en su puesto.",
    ],
  },
  {
    title: "El mapa de ceniza",
    visual:
      "Plano ferroviario quemado donde ceniza magnética se organiza en una ruta luminosa con tres puntos Norte Catedral y Río, varias manos alrededor bajo luz de linterna, intriga tecnológica realista",
    paragraphs: [
      "Marta tendió el plano sobre el suelo y conectó la batería de Marcos a dos raíles. Cada vez que el 317 pasaba por el anillo, la ceniza vibraba y se desplazaba unos milímetros. Después de tres pulsos, las partículas dibujaron una vía que no figuraba impresa: salía de Catedral, regresaba a Norte y terminaba en Río.",
      "—El orden está invertido —dijo Marcos. El esquema del sobre indicaba Norte, Catedral y Río. Vera recordó la grabación rota en el túnel, su propia voz pronunciando una frase que aún no había dicho: «Catedral antes que Norte». Gabriel había dejado dos rutas. La primera servía con los veintitrés pasajeros originales; la segunda compensaba la pérdida de Julián incorporando a Vera desde un punto intermedio.",
      "El plan exigía precisión. A las cinco y treinta y ocho cortarían toda la energía de Santa Lucía durante tres minutos. Esteban usaría su llave para invertir Catedral. Marta mantendría abierto Norte desde el kilómetro 0,8. Marcos activaría el apagón y, después, correría al cambio de Río. Vera esperaría en la puerta cuatro, validaría el billete y ocuparía el lugar de Julián.",
      "Había un problema: Río no podía abrirse desde fuera. La palanca que decidía la salida estaba en la locomotora. Gabriel tendría que accionarla y mantenerla hasta que el último vagón abandonara el campo. Si soltaba antes, el tren volvería al circuito; si la mantenía, la cabina quedaría del lado de la contención cuando los coches de pasajeros pasaran a la vía real.",
      "Vera se negó a aceptar que su padre debiera quedarse. Marta respondió que Gabriel conocía el coste desde la primera noche. Había enviado el mapa para salvar a sus hijas, no para salvarse. Esteban escuchaba en silencio. Cuando Vera le exigió la llave maestra, la cerró en su puño. «Si os la doy, ¿me prometes que Daniel saldrá?». Vera no hizo una promesa imposible. «Prometo que no volveremos a abrir una puerta antes de tiempo».",
      "Marta conectó un altavoz a la frecuencia del tren. Entre golpes de ruedas apareció la voz de Daniel. No hablaba a Vera, sino a Esteban: «Llevo veintidós años viendo el momento en que elegiste por mí. Si quieres sacarme, haz por una vez lo que te pedimos». El anciano se quitó la cadena del cuello y entregó la llave.",
      "La ceniza volvió a moverse. Bajo la ruta surgió una última advertencia que ninguno había visto: ASIENTO 24: SIN RETORNO SI LAS DOS HERMANAS NO VALIDAN JUNTAS. Vera llevaba el billete de ida. Lucía conservaba la mitad de vuelta, pero para unirlas tendría que encontrarla dentro del tren antes de que alcanzaran Río.",
      "Se repartieron los relojes sincronizados y abandonaron la estación enterrada. Mientras subían, Vera vio el mapa deshacerse detrás de ellos. Las partículas formaron durante un instante la silueta de Gabriel al mando de la locomotora. Luego todo quedó reducido a ceniza común. Faltaban dieciséis minutos para el apagón.",
    ],
  },
  {
    title: "Tres minutos de oscuridad",
    visual:
      "Estación moderna completamente a oscuras mientras un tren de 2004 se materializa con luz propia, una mujer espera ante la puerta cuatro sosteniendo un billete, escena épica de suspense realista",
    paragraphs: [
      "A las cinco y treinta y seis, la policía controlaba todas las salidas de Santa Lucía. Los viajeros habían sido evacuados por una falsa fuga de gas que Marcos introdujo en el sistema. Desde la subestación, él veía a los agentes recorrer las cámaras con linternas. Vera avanzó por los túneles de equipaje hasta el andén cero. Llevaba el billete, el reloj de Gabriel y la ficha de latón.",
      "Marta confirmó su posición en Norte. Esteban llegó a Catedral con la llave maestra y repitió el código de activación. Nadie confiaba del todo en él, pero no había sustituto. Marcos apoyó la mano sobre el interruptor general. A las cinco y treinta y ocho en punto lo bajó.",
      "La ciudad visible a través de los lucernarios se apagó por sectores. En Santa Lucía murieron pantallas, ascensores, cámaras y relojes. Solo permanecieron las antiguas luces amarillas del tren 317, que apareció al fondo del túnel y frenó por primera vez en veintidós años. El silencio hizo audible cada giro de sus ruedas.",
      "Vera esperó frente a la puerta cuatro. El indicador del vagón marcaba 03:17. Introdujo el billete en la ranura exterior y colocó la ficha sobre el número 24. Una perforadora invisible abrió un agujero en el cartón. La puerta se separó apenas lo suficiente para que pasara de lado. Dentro olía a humo, colonia barata y café recién derramado.",
      "Al poner el pie en el vagón, recuperó de golpe todos los recuerdos que el circuito había borrado: su primer día de universidad, la muerte de su madre, cada turno en objetos perdidos, el rostro de Marcos. También recordó millones de versiones de aquel mismo instante, posibilidades que nunca había vivido. En algunas rescataba a Lucía. En otras, el tren salía vacío. En la mayoría no llegaba a subir.",
      "La puerta empezó a cerrarse. Una mano la detuvo desde fuera. Esteban se coló tras ella y arrancó el billete de la ranura. Había abandonado el cambio de Catedral. «No pienso dejar a mi hijo con desconocidos», dijo. Vera trató de regresar, pero el andén ya era transparente. El tren comenzó a moverse.",
      "En el comunicador, la voz de Marta se llenó de interferencias. Catedral no había cambiado. Marcos dejó la subestación a oscuras y corrió hacia el control auxiliar. Le quedaban menos de noventa segundos para recorrer dos plantas, abrir una sala bloqueada y girar manualmente el desvío. Si fallaba, el 317 volvería al inicio con Vera y Esteban dentro.",
      "Las luces de emergencia se encendieron en el vagón. Veintidós pasajeros alzaron la cabeza al mismo tiempo. Sus movimientos se reiniciaron: una mujer buscó un bolso, un niño preguntó si ya habían llegado y Daniel golpeó la puerta del fondo. Solo una persona no repitió el gesto. Lucía permaneció de pie en el pasillo, mirando a Vera como si hubiese sabido exactamente dónde aparecería.",
    ],
  },
  {
    title: "La mujer que esperaba",
    visual:
      "Dos hermanas se reencuentran dentro de un tren detenido en 2004, una adulta y una adolescente con abrigo amarillo se abrazan entre pasajeros suspendidos y humo, emoción contenida y suspense cinematográfico realista",
    paragraphs: [
      "Lucía seguía teniendo dieciséis años. El flequillo, el abrigo amarillo, la pequeña cicatriz sobre la ceja: todo era idéntico a la fotografía. Pero la forma de observar a Vera no pertenecía a una adolescente. Había en sus ojos el cansancio de quien ha esperado más de lo que una vida debería permitir.",
      "Durante un segundo ninguna se movió. Vera había imaginado aquel encuentro tantas veces que la realidad le pareció más frágil que un sueño. Lucía fue la primera en acercarse. Le tocó las mejillas, estudió las líneas alrededor de sus ojos y sonrió con tristeza. «Eres mayor que yo», susurró. Entonces se abrazaron mientras el vagón entero temblaba al cambiar de vía.",
      "Lucía explicó que no recordaba todas las vueltas. Al principio despertaba sin saber nada; después empezó a conservar imágenes sueltas gracias a la mitad del billete. Aprendió a dejar mensajes en los ecos, a cambiar una palabra en cada repetición y a guiar a Julián hacia el sacrificio que había elegido. Para ella no habían pasado veintidós años continuos, pero sí una cantidad incontable de despertares.",
      "—Te he visto venir de cientos de maneras —dijo—. Esta es la primera en la que Marcos consigue cambiar Catedral. Como respuesta, el tren dio un salto violento. Por las ventanas apareció durante un instante el vestíbulo moderno de Santa Lucía. Marcos lo había logrado cuando quedaban cuatro segundos de apagón.",
      "Lucía sacó del forro del abrigo un triángulo de cartón. Encajaba con el borde rasgado del billete de Vera y completaba la palabra RETORNO, pero aún no podían unirlos. Primero debían llegar a la locomotora y conseguir que Gabriel abriera Río. Hasta entonces, las dos mitades tenían que permanecer separadas para anclar el principio y el final del tren.",
      "Un grito llegó desde el vagón siguiente. Esteban había encontrado a Daniel y trataba de llevárselo hacia una puerta. Su hijo lo apartó. Para Daniel la discusión de 2004 acababa de suceder minutos antes. «Me encerraste aquí porque no soportabas que me marchara», le dijo. «Y ahora vuelves a decidir sin escuchar». Esteban envejeció más con esas palabras que en las dos décadas anteriores.",
      "El resto de pasajeros comenzó a despertar del ciclo. Recordaban a Julián y entendían que faltaba. Una mujer preguntó qué año era. Vera respondió la verdad. Nadie habló durante varios segundos; solo se oyó el traqueteo. Un hombre miró la foto de un bebé en su cartera y calculó en silencio la edad que tendría. La salida, comprendió Vera, también podía ser una forma de pérdida.",
      "Lucía le tomó la mano. «Papá está en la cabina. Ha mantenido el tren estable desde la primera vuelta, pero está herido y cada ciclo le cuesta más recordar quién es». Señaló la puerta que comunicaba con los coches delanteros. Al otro lado, las luces se apagaban una tras otra. La ruta hacia Río acababa de empezar.",
    ],
  },
  {
    title: "El maquinista",
    visual:
      "Cabina de locomotora de 2004 atravesando un túnel de luces temporales, padre e hijas reunidos ante controles analógicos mientras un reloj marca 3:17, drama de suspense realista",
    paragraphs: [
      "Vera y Lucía avanzaron hacia la locomotora mientras el tren alternaba entre épocas. Al abrir una puerta veían el vagón intacto; al cruzarla aparecía quemado, cubierto de hielo o vacío. Lucía sabía esperar el destello correcto. «Pisa cuando escuches el segundo golpe», indicaba. Quien se movía fuera de ritmo podía quedar atrapado en una versión distinta del convoy.",
      "En el primer coche encontraron a Gabriel inclinado sobre un cuadro eléctrico. Tenía cuarenta y dos años, la misma edad que la noche de la desaparición. Una herida seca le cruzaba la frente y llevaba el reloj ausente en la muñeca como una marca pálida. Al ver a Vera, buscó en su rostro a la niña que había dejado en el andén.",
      "—Papá, soy yo. Gabriel pronunció su nombre y se abrazó a las dos. No hubo tiempo para contar veintidós años. El anillo de Norte se acercaba y los indicadores vibraban. Gabriel explicó que había saltado a la locomotora cuando el tren empezó a moverse. Desde entonces mantenía manualmente la velocidad del ciclo, despertando solo durante unos minutos en cada vuelta.",
      "La salida sur requería separar la locomotora de los vagones en el punto de Río. Alguien debía sostener el freno de inducción dentro de la cabina para mantener abierto el campo mientras los coches cruzaban. La locomotora no llegaría al otro lado. Gabriel llevaba toda la noche —y todas sus repeticiones— preparado para quedarse.",
      "Vera se negó. Quiso buscar una forma de bloquear la palanca, pero Gabriel mostró restos de herramientas fundidas alrededor del mecanismo. Umbral detectaba el peso y el pulso de un operador vivo. «No diseñamos una salida automática porque nunca imaginamos que alguien permanecería dentro más de diecisiete minutos». Miró a sus hijas. «Mi trabajo era traeros a casa».",
      "La puerta de la cabina se abrió y Esteban entró con Daniel detrás. Al ver a Gabriel, levantó la pistola de señales. Lo acusó de haber cambiado la ruta para castigarle. Gabriel respondió que fue Esteban quien activó una tecnología cancelada y cerró las puertas aun sabiendo que había niños a bordo. Daniel se colocó entre ambos. «Se acabó», dijo. «Nadie más va a pagar por aquella decisión».",
      "El tren penetró en el anillo Norte. Marta mantuvo el desvío mientras arcos azules recorrían el techo. Durante unos segundos Gabriel olvidó dónde estaba y soltó el regulador. Vera lo sujetó; Lucía corrigió la velocidad siguiendo marcas que ella misma había grabado en ciclos anteriores. Detrás, los pasajeros empezaron a recordar a la vez y sus voces llenaron el convoy.",
      "Al salir del anillo, solo quedaba Río. Gabriel entregó a Vera una manivela de latón y señaló el acoplamiento que separaría la locomotora. Esteban observó la palanca de inducción. Por primera vez entendió con claridad cuál era el precio de la salida. Guardó la pistola y preguntó cuánto tiempo tendría que sostenerla. Gabriel respondió: «Hasta que dejes de oír el tren».",
    ],
  },
  {
    title: "La estación despierta",
    visual:
      "Gran estación al amanecer despertando con relojes y paneles encendidos a la vez, pasajeros evacuados observan la silueta de un tren antiguo atravesar muros, luz azul y ámbar, realismo cinematográfico",
    paragraphs: [
      "A las cinco y cuarenta, Santa Lucía despertó de golpe. Volvió la electricidad, pero ningún sistema recuperó su estado normal. Los paneles mostraron fotografías de los desaparecidos. Las máquinas expendedoras imprimieron billetes para el tren 317. Todos los relojes, desde el vestíbulo hasta las oficinas, giraron hacia atrás y se detuvieron en las tres y diecisiete.",
      "Los agentes que registraban la estación vieron pasar un convoy antiguo detrás de las paredes. Algunos corrieron; otros permanecieron inmóviles ante los rostros que aparecían en las ventanas. Fuera, sobre las calles aún oscuras, las farolas parpadearon siguiendo el avance subterráneo del tren hacia el río.",
      "Marcos llegó al puesto de cambio sur con menos de un minuto. La palanca estaba soldada por óxido y un motor de bloqueo la mantenía en dirección al circuito. Usó una barra para romper la carcasa. Por el comunicador oyó a Vera, pero su voz llegaba antes de que pronunciara cada frase. El tiempo exterior y el del convoy empezaban a superponerse.",
      "En la locomotora, Gabriel colocó las manos de Esteban sobre el freno de inducción. «Cuando lo bajes no podrás soltarlo. Si lo haces, arrastrarás los vagones de nuevo contigo». Daniel pidió a su padre que regresara. Esteban lo miró como había debido mirarlo antes de convertir el miedo a perderlo en una prisión.",
      "—Creí que protegerte era impedir que eligieras —dijo—. Llevo veintidós años abriendo la puerta equivocada. Daniel negó con la cabeza y trató de apartarlo de la palanca. Esteban lo abrazó una sola vez. Después lo empujó suavemente hacia Gabriel y cerró la puerta de la cabina entre ambos.",
      "Gabriel, Vera, Lucía y Daniel retrocedieron al primer vagón. A través del cristal vieron a Esteban bajar el freno. La locomotora se cubrió de luz azul. El ruido del tren dejó de ser una repetición y se convirtió en una carrera continua. Por primera vez, los indicadores avanzaron más allá de las 03:17:00.",
      "Marcos consiguió mover la palanca exterior unos centímetros. No bastaba. Apoyó ambos pies en el muro y tiró hasta que se le abrió la piel de las manos. Marta desvió hacia Río la última reserva de los anillos del norte. La descarga recorrió kilómetros de cable abandonado y golpeó el motor bloqueado. La aguja cambió con un estampido.",
      "La estación enterrada se iluminó bajo la ciudad. Cada uno de sus andenes apareció durante un segundo en Santa Lucía, superpuesto a los modernos. Vera vio pasar la vida que había construido sin su familia y, al otro lado, la vida que pudo haber tenido. Luego ambas imágenes se cerraron como las hojas de una puerta. El tren tomó la salida sur.",
    ],
  },
  {
    title: "La hora imposible",
    visual:
      "Reloj de tren avanzando de 3:17 a 3:18 mientras dos hermanas unen mitades de un billete frente a un mecanismo luminoso, la locomotora se separa al fondo, clímax cinematográfico realista",
    paragraphs: [
      "El reloj del primer vagón marcó las 03:17:59. El segundero intentó avanzar, retrocedió y volvió a intentarlo. El circuito entero se aferraba a la hora que lo había contenido durante veintidós años. Lucía y Vera colocaron las dos mitades del billete sobre el validador de emergencia. Encajaban, pero la máquina no las aceptó.",
      "Faltaba el asiento 24. Vera corrió hasta el lugar que había quedado vacío tras la muerte de Julián y hundió la ficha de latón en el reposabrazos. Un aro metálico se cerró alrededor de su muñeca, justo sobre la cicatriz de la infancia. El sistema había reconocido a la pasajera retirada en 2004 y trataba de retenerla.",
      "Lucía sujetó el billete unido contra el lector. Gabriel giró la manivela del acoplamiento. No ocurrió nada. En la cabina, Esteban seguía presionando el freno, pero la locomotora y los vagones permanecían enlazados. Marta comprendió el fallo al leer los instrumentos: el tren contaba veinticuatro anclas. El recuerdo temporal de Julián continuaba ocupando su sitio.",
      "La tarjeta en blanco cayó del bolsillo de Vera. Sobre su superficie apareció por última vez el rostro del interventor. Julián había previsto aquel momento. La tarjeta se deslizó sola por el pasillo hasta la perforadora y entró en la ranura de cancelación. Sonó un golpe seco. En todas las ventanillas se reflejó su figura levantando la gorra a modo de despedida.",
      "El indicador bajó a veintitrés. La manivela cedió y el acoplamiento se abrió. Daniel quiso volver con su padre, pero Gabriel lo retuvo. A través del cristal delantero, Esteban mantenía los brazos rígidos sobre la palanca. Ya no los miraba: contemplaba la vía que se cerraba frente a él.",
      "—Ahora —gritó Gabriel. Lucía y Vera empujaron juntas el billete en el validador. La máquina perforó las dos mitades con un mismo agujero. El aro se abrió en la muñeca de Vera y el reloj pasó, por fin, de las tres y diecisiete a las tres y dieciocho.",
      "La locomotora se separó. Durante unos metros siguió delante de ellos, envuelta en arcos azules. Esteban apareció en la puerta de la cabina, ya borroso. Daniel apoyó la mano en el cristal. Su padre repitió el gesto. Después una curva imposible se llevó la locomotora hacia la oscuridad mientras los vagones continuaban por una vía recta hacia la luz.",
      "El freno de inducción dejó de oírse. El campo se cerró detrás del último coche con un golpe que rompió todas las ventanas del laboratorio. Marta cayó al suelo. Marcos perdió la comunicación. Durante un segundo no hubo señal del tren en ningún punto de la red. Luego, en el panel principal de Santa Lucía, apareció una llegada: 317, procedencia 2004, andén 1.",
    ],
  },
  {
    title: "El tren de las 3:17",
    visual:
      "Tren verde de 2004 entrando al amanecer en una estación moderna llena de personal de emergencia, dos hermanas y su padre visibles tras una ventana, escena de llegada emotiva y realista",
    paragraphs: [
      "El 317 emergió del túnel sur a las cinco y cuarenta y una. Ya no atravesaba paredes ni dejaba estelas: pesaba, hacía ruido y lanzaba chispas reales contra los raíles. Entró demasiado rápido en el andén 1. Gabriel corrió al freno mecánico del primer vagón mientras los pasajeros se sujetaban a los asientos.",
      "Marcos vio el convoy desde el puesto de cambio y accionó la señal de emergencia. Los topes hidráulicos se elevaron al final de la vía. El tren chocó contra ellos, recorrió otros veinte metros y se detuvo con un gemido de metal. Una de las ventanas se quebró. Después solo quedó el sonido del vapor y las alarmas de la estación.",
      "Nadie se atrevió a abrir de inmediato. Marta comprobó desde sus instrumentos que el campo había caído a cero. Vera y Lucía introdujeron el billete completo en la puerta cuatro. Esta vez las hojas se abrieron sin frío, sin ceniza y sin voces. El aire del amanecer entró en el vagón.",
      "Lucía fue la primera en bajar. Veintidós años después de desaparecer, puso un pie en el mismo andén con dieciséis años y el abrigo amarillo manchado de humo. Vera descendió a su lado. Al tocar el suelo, los teléfonos de toda la estación recuperaron de golpe sus fotografías, sus mensajes y su nombre. Sonia, al otro extremo del vestíbulo, recordó quién era y empezó a llorar sin saber por qué.",
      "Los pasajeros salieron uno a uno. Algunos encontraron a sus familias entre los curiosos que la policía no había conseguido alejar; otros preguntaron por personas fallecidas durante su ausencia. Daniel se quedó junto a la puerta mirando el túnel. No había locomotora detrás del primer vagón, solo un acoplamiento quemado y una vía vacía.",
      "Gabriel bajó el último. Miró la estación transformada, los paneles digitales y a sus hijas, una todavía adolescente y la otra ya mayor que él cuando partió. Vera quiso explicarle todo el tiempo perdido, pero él le rodeó los hombros. «Ya habrá tiempo», dijo. Era una frase sencilla y, después de aquella noche, sonó como una promesa extraordinaria.",
      "Marcos llegó con las manos ensangrentadas. Vera lo reconoció antes de ver su nombre escrito en el brazo. Se abrazaron sin decidir si era alivio, gratitud o algo que tendría que esperar. Marta apareció acompañada por los agentes, sosteniendo las cintas y los planos que demostraban lo ocurrido. Esta vez nadie podría reducirlo a cuatro víctimas y una avería.",
      "Cuando el sol entró por la cubierta de vidrio, el panel borró la llegada del 317. En su lugar mostró los nombres de todos los pasajeros recuperados. Faltaban dos: Julián Costa y Esteban Vela. Daniel observó los huecos vacíos hasta que las letras se apagaron. Luego dobló con cuidado el billete que Vera le entregó y lo guardó como la única prueba de que una puerta cerrada a tiempo también podía ser un acto de amor.",
    ],
  },
  {
    title: "Donde terminan las vías",
    visual:
      "Andén tranquilo de Santa Lucía semanas después, memorial con reloj a las 3:18, dos hermanas de edades distintas y su padre frente a la vía clausurada al amanecer, final emotivo y misterioso realista",
    paragraphs: [
      "La versión oficial tardó semanas en tomar forma. La reapertura del caso reveló documentos falsificados, pagos de la antigua compañía ferroviaria y órdenes de silencio firmadas en 2004. Nadie supo explicar Umbral sin recurrir a palabras que parecían ciencia ficción, pero veintidós pasajeros sin envejecer y un tren registrado en cientos de teléfonos hicieron imposible volver a enterrarlo.",
      "Los regresados tuvieron que aprender un mundo que había avanzado sin ellos. Daniel encontró a su madre con el cabello blanco. El niño de uno de los viajeros era ahora mayor que su padre. Gabriel descubrió que su esposa había muerto creyendo que él y Lucía no regresarían. Guardó silencio durante un día entero y después pidió a Vera que le contara cómo había sido su vida, año por año.",
      "Lucía rechazó que la trataran como una reliquia. Volvió a estudiar, se cortó el cabello y conservó el abrigo amarillo doblado en una caja. A veces despertaba cada diecisiete minutos convencida de que el ciclo comenzaba otra vez. Entonces llamaba a Vera y ambas permanecían al teléfono hasta oír algún ruido cotidiano: un autobús, una persiana, el viento. Cualquier sonido que avanzara sin repetirse.",
      "Marta dirigió el sellado de los tres anillos. Antes de desconectar Norte, recuperó la última lectura de la locomotora: había continuado por el circuito durante una fracción de segundo exterior, quizá una vuelta más en su propio tiempo. No encontró señales de Esteban. Daniel pidió que su nombre figurase junto al de Julián en el memorial, no como víctima, sino como responsable que al final había elegido quedarse.",
      "En el andén 1 colocaron un reloj detenido a las tres y dieciocho. Debajo, una placa recordaba a quienes hicieron posible el regreso. Vera volvió a su puesto en objetos perdidos. Decía que, después de haber recuperado a dos personas durante veintidós años, ningún paraguas ni ninguna maleta podían considerarse definitivamente perdidos.",
      "Marcos pasó a verla la noche en que se cumplió un mes. A las tres y diecisiete, todas las luces permanecieron encendidas y ningún tren apareció en el panel. Vera sintió alivio y una pequeña decepción que no quiso admitir. Juntos bajaron hasta la puerta del antiguo andén cero. El acceso estaba soldado y cubierto por hormigón nuevo.",
      "El teléfono gris sonó cuando regresaban a la oficina. Vera y Marcos se miraron. Ella descolgó. Durante varios segundos solo escuchó una señal de vía cada vez más lejana. Después llegó la voz cansada de Esteban: «Las puertas están cerradas. Esta vez, todas». No pidió ayuda ni pronunció el nombre de Daniel. La línea se cortó antes de que Vera pudiera responder.",
      "Vera dejó el auricular en su sitio. Afuera, el primer tren de la mañana entró a la hora prevista y abrió sus puertas. Los viajeros bajaron somnolientos, sin saber que bajo sus pies terminaba una vía imposible. El reloj del memorial avanzó un segundo por sí solo y volvió a detenerse. No en las 3:17, sino en las 3:18. Vera sonrió. Luego salió al andén para recibir el día.",
    ],
  },
];

export const stationChapters: Chapter[] = stationChapterDrafts.map(
  ({ title, paragraphs, visual, visualAfter }, index) => {
    const number = index + 1;
    const wordCount = paragraphs.join(" ").trim().split(/\s+/).length;

    return {
      number,
      title,
      readingMinutes: Math.max(3, Math.ceil(wordCount / 190)),
      paragraphs,
      visuals: [
        {
          id: `la-estacion-de-las-317-capitulo-${number}-imagen-1`,
          afterParagraph: visualAfter ?? Math.ceil(paragraphs.length / 2),
          alt: `Escena del capítulo ${number}, ${title}, de La estación de las 3:17`,
          prompt: visual,
          aspectRatio: "16/9",
          status: "pending",
          url: null,
        },
      ],
    };
  },
);

export const stationReadingMinutes = stationChapters.reduce(
  (total, chapter) => total + chapter.readingMinutes,
  0,
);
