import type { Chapter } from "@/lib/types";

interface LazarusChapterDraft {
  title: string;
  paragraphs: string[];
  visual: string;
}

const lazarusChapterDrafts: LazarusChapterDraft[] = [
  {
    title: "Cámara cuatro",
    visual:
      "Laboratorio subterráneo futurista en alarma roja, un hombre empapado sale de una cámara de restauración marcada LZ-04 y descubre otra camilla en la oscuridad, thriller de ciencia ficción realista, encuadre cinematográfico, sin texto",
    paragraphs: [
      "Las alarmas llevaban horas sonando cuando Elías abrió los ojos dentro de la cámara.",
      "Lo primero que sintió fue frío. No el frío de una habitación sin calefacción, sino uno antiguo y profundo, instalado en los huesos. Estaba desnudo, suspendido en un líquido oscuro, con una mascarilla ajustada a la boca y decenas de filamentos adheridos al pecho. Más allá del cristal empañado, una luz roja giraba sobre un techo metálico.",
      "No sabía dónde estaba. Tampoco sabía quién era.",
      "Golpeó el cristal. El sonido quedó amortiguado por el líquido. Volvió a hacerlo y una grieta blanca se extendió frente a su rostro. La tercera vez, la cámara se abrió con una detonación seca. Cayó sobre el suelo, arrastrando cables y respirando como si acabara de nacer.",
      "Una voz femenina surgió de los altavoces. —Secuencia de restauración interrumpida. Daño neurológico pendiente de evaluación.",
      "Elías permaneció de rodillas. Algunas palabras acudían a él sin esfuerzo: restauración, presión, oxígeno, salida. Otras parecían pertenecer a otra persona. Se miró las manos. En la cara interna de su muñeca izquierda había cuatro caracteres grabados bajo la piel: LZ-04.",
      "La sala contenía cinco cámaras verticales. La primera estaba vacía y tenía el cristal roto hacia dentro. La segunda había ardido. La tercera permanecía abierta, cubierta de manchas secas. Sobre la cuarta parpadeaba una luz verde. La quinta no tenía número.",
      "Junto a una taquilla encontró ropa negra, botas de combate y una tarjeta de identificación. La fotografía era suya, aunque el hombre retratado parecía varios años mayor. ELÍAS VEGA. DIRECTOR DEL PROYECTO. ACCESO ABSOLUTO. En el reverso aparecía otra inscripción: FALLECIDO: 14 DE NOVIEMBRE. No indicaba el año.",
      "Elías se acercó a la puerta, pero el lector biométrico no reaccionó. Apoyó la mano y la pantalla mostró una línea azul recorriendo sus dedos. —Identidad genética confirmada —anunció la voz—. Bienvenido, director Vega. La puerta se abrió.",
      "El corredor exterior estaba a oscuras. Había marcas de disparos en las paredes y un rastro de sangre conducía hasta una intersección. Elías avanzó siguiendo ese rastro, sorprendido por la seguridad con la que su cuerpo se movía. Sabía caminar sin hacer ruido. Sabía dónde mirar antes de doblar una esquina. Sabía desmontar el arma que encontró junto a un guardia muerto. No recordaba haber aprendido ninguna de aquellas cosas.",
      "En la siguiente sala descubrió una camilla rodeada de instrumental quirúrgico. Sobre ella yacía un hombre vestido con el mismo uniforme negro. Tenía su misma estatura, sus mismas manos y su mismo rostro. El cadáver llevaba grabado en la muñeca el código LZ-03.",
      "Elías se acercó conteniendo la respiración. El hombre había muerto de un disparo en el abdomen. En su mano derecha apretaba una llave de cristal; en la izquierda, alguien había escrito tres palabras con sangre: ADA ESTÁ MINTIENDO.",
      "Entonces los altavoces dejaron de emitir la alarma. Una mujer habló desde algún lugar de la instalación. —Elías, si puedes oírme, no abras ninguna puerta. Él miró la que acababa de cruzar. Al otro lado ya se escuchaban pasos.",
    ],
  },
  {
    title: "El cadáver con mi rostro",
    visual:
      "Dos hombres idénticos en un laboratorio oscuro, uno vivo arrodillado junto al cadáver de su réplica marcada LZ-03, drones de seguridad acercándose por un corredor rojo, ciencia ficción realista y tensa",
    paragraphs: [
      "Elías arrastró el cadáver hasta la pared y apagó la luz de la sala.",
      "Los pasos se aproximaron por el corredor. No eran humanos. Sonaban demasiado regulares, acompañados por el zumbido de pequeños motores. Su cuerpo reaccionó antes que su pensamiento: retiró el cargador del arma, comprobó la munición y se agachó detrás de la camilla.",
      "Una esfera metálica apareció flotando bajo el marco de la puerta. Proyectó una cuadrícula azul sobre el suelo. —Unidad no registrada —dijo una voz mecánica—. Permanezca inmóvil. Elías disparó dos veces. La esfera se estrelló contra la pared y explotó en una lluvia de chispas.",
      "No sintió miedo hasta que todo terminó. —Has despertado demasiado pronto —dijo la mujer a través de los altavoces—. El proceso necesitaba otros cuarenta minutos. —¿Quién eres? —Ada Serrano. Estoy en el nivel médico.",
      "Elías miró el mensaje escrito en la mano del cadáver. —¿Quién es el hombre de la camilla? Al otro lado se produjo un silencio. —Tú. —No soy yo. —Tienes razón. Pero ahora no dispongo de tiempo para explicártelo. Una unidad de recuperación acaba de entrar en el complejo. Se llaman Cerbero. Si te encuentran, extraerán lo que llevas dentro y destruirán el resto.",
      "—No llevo nada dentro. —Llevas algo por lo que han matado a treinta y siete personas.",
      "Una detonación hizo temblar el techo. El polvo cayó sobre la camilla. En la pared se encendió un plano de emergencia: el nivel superior había sido vulnerado.",
      "Elías tomó la llave de cristal que sujetaba LZ-03. Al hacerlo descubrió una pequeña incisión bajo la oreja del cadáver. Él se tocó el mismo lugar y encontró una cicatriz idéntica.",
      "La llave abrió un terminal oculto en la pared. En la pantalla apareció una grabación. El hombre del vídeo era él, pero llevaba barba y tenía un vendaje ensangrentado alrededor del abdomen. —Si estás viendo esto, eres el cuarto —dijo LZ-03—. Eso significa que yo no conseguí salir.",
      "La imagen tembló. Detrás del hombre sonaban disparos. —No confíes en tus recuerdos. No confíes en la voz de los altavoces. Y, sobre todo, no permitas que Valcárcel te lleve al núcleo. Lo que busca no está en esta instalación. Está escondido dentro de nosotros.",
      "El hombre acercó el rostro a la cámara. —No habrá un quinto, Elías. Ada solo preparó cuatro cuerpos. La grabación terminó.",
      "Elías buscó más archivos. Encontró tres fichas médicas: LZ-01: TERMINADO. LZ-02: TERMINADO. LZ-03: TRAUMA BALÍSTICO / FALLO ORGÁNICO. LZ-04: RESTAURACIÓN INCOMPLETA. Junto a ellas aparecía la fotografía de un hombre llamado Elías Vega, fallecido cuatro años atrás durante una explosión en aquella misma instalación.",
      "—¿Lo has visto? —preguntó Ada. —Dice que no confíe en ti. —Los tres dijeron lo mismo al principio. —¿Cuántas veces me has despertado? —Esta es la cuarta.",
      "Una nueva explosión sacudió el corredor. Las luces de emergencia se apagaron durante un segundo. —Cerbero llegará a tu posición en ocho minutos —continuó Ada—. Si quieres respuestas, ven a buscarme. Si quieres morir como los anteriores, quédate ahí.",
      "Elías recogió el arma y abrió la puerta del extremo opuesto. Antes de marcharse volvió a mirar a LZ-03. Por un instante creyó que el cadáver respiraba.",
    ],
  },
  {
    title: "Todas mis firmas",
    visual:
      "Sala de control circular cubierta de pantallas con expedientes clasificados, un hombre descubre decenas de documentos firmados con su nombre y una cuenta atrás roja, thriller tecnológico realista",
    paragraphs: [
      "El corredor descendía hacia el corazón de la montaña.",
      "Elías avanzó guiado por señales que parecían despertar recuerdos físicos. Giraba antes de leer los indicadores. Sabía qué escaleras estaban vigiladas y qué conductos comunicaban con los laboratorios. Aquel lugar resultaba tan familiar como una casa olvidada.",
      "Llegó a una sala de control circular. Cientos de pantallas cubrían las paredes, aunque la mayoría mostraba el mismo mensaje: PROYECTO LÁZARO EN CUARENTENA.",
      "Introdujo la llave de cristal. El sistema solicitó su huella, su retina y una frase de autorización que no recordaba. Sin embargo, cuando el micrófono se iluminó, las palabras surgieron solas. —La muerte no conserva secretos. Las pantallas se encendieron.",
      "Había miles de documentos: informes neurológicos, expedientes militares, órdenes de traslado, autopsias y listas de sujetos. Todos llevaban la misma firma digital. La suya. El primer archivo había sido firmado nueve años atrás. El último, apenas diecisiete horas antes de su despertar.",
      "Elías abrió una orden reciente. AUTORIZO LA ACTIVACIÓN DEL PROTOCOLO CONCORDIA. Más abajo encontró otra, firmada solo tres minutos después. ORDENO LA DESTRUCCIÓN INMEDIATA DEL PROYECTO LÁZARO. Las dos firmas eran auténticas.",
      "—Ada. —Sigo aquí. —¿Por qué firmé dos órdenes contrarias? —Las firmó LZ-03, pero no bajo la misma voluntad. Valcárcel lo obligó a activar Concordia mediante una orden implantada. Tres minutos después recuperó el control e intentó destruir el proyecto.",
      "En la pantalla apareció la ficha del fundador del proyecto. El hombre de la fotografía era él. Doctor en neuroingeniería, especialista en operaciones encubiertas y antiguo responsable de la División de Inteligencia Estratégica. Elías leyó tres veces el cargo. —No soy científico. —Tu memoria declarativa está fragmentada. Las habilidades permanecen, pero has perdido gran parte de tu vida. Es uno de los efectos de la restauración.",
      "—¿Restauración de qué? —De ti.",
      "En una carpeta protegida encontró una grabación anterior a su muerte. El Elías original estaba sentado en la misma sala, con el rostro agotado. —Si alguno de nosotros llega a escuchar esto —decía—, significará que Ada ha incumplido su promesa. No la juzgues demasiado pronto, pero tampoco confíes en ella. Ada siempre ha sido incapaz de dejar morir aquello que ama.",
      "La grabación se interrumpió. En el plano apareció un grupo de señales avanzando por el nivel superior. Doce soldados. Se movían en dos formaciones y desconectaban las cámaras a su paso.",
      "—Cerbero —dijo Ada—. Tienes cinco minutos. —¿Quién es Valcárcel? —El hombre que convirtió nuestro trabajo en un arma. —¿Nuestro? —Tú y yo creamos Lázaro.",
      "Elías cerró los ojos. Vio durante un instante una playa gris, una mujer doblando una hoja de papel y unas manos infantiles intentando imitarla. La visión desapareció tan rápido como había llegado. —Hay una mujer en mis recuerdos. —Lucía. La forma en que Ada pronunció el nombre le produjo más dolor que cualquier herida. —¿Quién era? —Tu esposa.",
      "Elías buscó su ficha, pero el sistema bloqueó el acceso. SUJETO LÁZARO 000. Antes de poder preguntar, una bala atravesó la puerta de la sala de control. Cerbero lo había encontrado.",
    ],
  },
  {
    title: "Ada",
    visual:
      "Neurocientífica herida tras un cristal de aislamiento y un agente idéntico a un hombre muerto apuntándola con un fusil, laboratorio médico bajo luz roja, suspense tecnológico cinematográfico",
    paragraphs: [
      "Elías se arrojó al suelo cuando una segunda bala rompió una pantalla.",
      "Las puertas se abrieron y dos soldados entraron protegidos por escudos. Elías disparó contra las luces. La oscuridad le concedió menos de tres segundos, pero su cuerpo supo aprovecharlos. Rodó detrás de una consola, derribó al primer hombre y utilizó su escudo para golpear al segundo.",
      "No pensó. Actuó. Cuando volvió a ser consciente de sí mismo, ambos soldados estaban en el suelo y él sostenía un fusil que no recordaba haber recogido.",
      "—No los mates —ordenó Ada. —Han intentado matarme. —Sus órdenes son capturarte vivo. Elías comprobó el pulso de los hombres. Seguían respirando.",
      "Siguió las indicaciones de Ada hasta el nivel médico. La encontró encerrada detrás de un cristal de aislamiento. Era una mujer de unos cincuenta años, delgada, con el cabello oscuro atravesado por mechones grises. Llevaba una bata manchada de sangre y presionaba una venda contra su costado.",
      "Elías apuntó hacia ella. —Abre la puerta —dijo Ada. —LZ-03 escribió que mentías. —LZ-03 también me disparó. Ada apartó la bata y mostró una herida cerca de las costillas.",
      "—¿Por qué? —Porque Valcárcel había activado una orden dentro de su memoria. Cuando consiguió recuperar el control, se disparó a sí mismo antes de volver a atacarme. —¿Y aun así me despertaste? —No fuiste una decisión. Fuiste una emergencia.",
      "El nivel médico comenzó a perder oxígeno. Ada señaló un lector junto a la puerta. La llave de cristal encajaba en él. —Si quisiera matarte, bastaría con esperar —dijo Elías. —Lo sé.",
      "La serenidad de aquella respuesta le molestó más que una súplica. Introdujo la llave. Ada salió apoyándose contra la pared. Al llegar junto a él levantó una mano hacia su rostro, pero se detuvo antes de tocarlo. —Eres más joven —murmuró.",
      "—¿Cuántos años tenía cuando morí? —Cuarenta y dos. Este cuerpo fue cultivado a partir de una muestra que entregaste a los treinta y seis. Elías observó su reflejo en el cristal. No era el hombre de las grabaciones. Se parecía a él, pero todavía no llevaba todo su cansancio.",
      "—Entonces soy un clon. —Eres un organismo humano completo con una reconstrucción parcial de su arquitectura neural. —Eso significa que soy un clon. —Significa que todavía no sabemos qué palabra utilizar.",
      "Las luces parpadearon. En los altavoces apareció una voz masculina. —Doctor Serrano, apártese del sujeto. Ada palideció. —Valcárcel. —La instalación está bajo autoridad militar —continuó la voz—. Entregue a LZ-04 y podrá salir con vida.",
      "Elías acercó el fusil al cristal de una cámara para ver el reflejo del corredor. Distinguió un punto rojo desplazándose hacia la espalda de Ada. La empujó al suelo. El disparo atravesó la puerta y rozó el hombro de Elías.",
      "El dolor despertó otro recuerdo: Lucía cosiéndole una herida bajo la luz de una cocina, diciéndole que algún día regresaría a casa sin partes suficientes para seguir llamándose Elías. No recordó qué le había respondido. Solo recordó que ambos habían reído.",
    ],
  },
  {
    title: "Recuerdos prestados",
    visual:
      "Agente herido y científica escapando bajo una plataforma industrial mientras soldados armados pasan sobre ellos, destellos de una playa y una mujer en su memoria, ciencia ficción de acción realista",
    paragraphs: [
      "Ada selló la herida con espuma quirúrgica mientras Elías vigilaba la entrada.",
      "—¿Ese recuerdo era verdadero? —preguntó él. —¿Cuál? —Lucía curándome en una cocina. Ada evitó mirarlo. —No puedo saberlo.",
      "—Tú introdujiste los recuerdos en mi cabeza. —Reconstruimos un mapa a partir del último registro neural del original. Pero la memoria no es una grabación. Cada vez que recuerdas algo, lo modificas. Lázaro no devuelve el pasado: construye una versión compatible con los restos que encuentra. —Entonces podría recordar cosas que nunca ocurrieron. —Sí.",
      "Cerbero entró en el nivel médico por dos accesos. Ada condujo a Elías hasta un montacargas de instrumental. Descendieron tendidos bajo una plataforma, oyendo las botas de los soldados sobre sus cabezas.",
      "A mitad del trayecto, la voz de una mujer irrumpió en la frecuencia del fusil. —LZ-04, soy la comandante Inés Soria. Entrégate y la doctora Serrano recibirá atención médica. —Vuestras balas tienen una forma extraña de ofrecer ayuda. —Tú asesinaste a mi hermano.",
      "Elías miró a Ada. —¿Es cierto? Ada tardó demasiado en responder.",
      "Una imagen atravesó la mente de Elías: un hombre arrodillado en un pasillo blanco, levantando las manos; el fogonazo de un arma; sangre extendiéndose bajo su cuerpo. Elías recordaba haber apretado el gatillo.",
      "—Se llamaba Daniel Soria —continuó la comandante—. Trabajaba en mantenimiento. LZ-02 le disparó durante la segunda fuga. —Yo no soy LZ-02. —Tenía tu cara, tu voz y tus recuerdos.",
      "El montacargas se detuvo. Elías y Ada salieron a una galería de turbinas. Bajo ellos, el agua circulaba con un estruendo ensordecedor. —¿Maté a ese hombre? —preguntó Elías. —Vi el cuerpo —respondió Ada—. No vi quién disparó.",
      "Cerbero apareció en la pasarela superior. Elías derribó una tubería para crear una cortina de vapor y avanzó cubriendo a Ada. Cada movimiento le resultaba conocido. Había luchado allí antes, quizá tres veces.",
      "Uno de los soldados cayó desde la pasarela y quedó colgado de la barandilla. Elías podría haber seguido corriendo, pero regresó y lo sujetó por el brazo. El soldado lo miró con terror. —Director Vega… Elías consiguió subirlo. El hombre trató de alcanzar su pistola, pero él se la quitó.",
      "—¿Me conocías? —Todos lo conocíamos. Usted diseñó la instalación. —¿Y Daniel Soria? El soldado miró hacia las cámaras. —No puedo hablar.",
      "Un disparo alcanzó la tubería junto a su cabeza. Provenía de las posiciones de Cerbero. No pretendían silenciar a Elías, sino al soldado. Elías y Ada escaparon por una compuerta de mantenimiento. Antes de cerrarla, él vio cómo los propios compañeros del hombre lo arrastraban fuera de la pasarela.",
      "—No han venido a rescatar el proyecto —dijo—. Han venido a borrar lo que ocurrió aquí. Ada negó lentamente. —Han venido a utilizarlo una última vez.",
    ],
  },
  {
    title: "Cerbero",
    visual:
      "Comandante militar frente a una pared de vigilancia observa a un agente perseguido por pasarelas de turbinas, vídeo oculto revela una ejecución, acción conspirativa de ciencia ficción realista",
    paragraphs: [
      "La comandante Soria dirigía a sus hombres desde el centro de seguridad.",
      "En las pantallas vio a Elías atravesar la galería de turbinas con los mismos movimientos que recordaba de LZ-02. La misma inclinación del hombro. La misma pausa antes de disparar. La misma mirada inexpresiva con la que, según sus recuerdos, había matado a Daniel.",
      "Valcárcel apareció detrás de ella. —No confundas el rostro con la persona —dijo el general. —Para usted todos son herramientas. —Para eso fueron creados. Soria apretó la mandíbula.",
      "Mientras tanto, Elías y Ada avanzaban por un conducto bajo el sistema de ventilación. Ella perdía sangre. Él lo advirtió, pero Ada rechazó detenerse. —Necesitamos llegar al Archivo de Engramas —dijo—. Allí encontrarás las respuestas. —¿Y qué encontrarás tú? —Una forma de acabar con esto.",
      "Al salir del conducto, dos soldados los esperaban. Elías derribó al primero, pero el segundo lo golpeó con una descarga eléctrica. Despertó arrodillado ante Soria, con las manos inmovilizadas.",
      "La comandante tenía una cicatriz fina sobre el labio y ojos que llevaban demasiado tiempo sin dormir. —Mírame —ordenó. Elías obedeció. —¿Recuerdas a mi hermano? —Recuerdo haber disparado a un hombre. No sé si el recuerdo es mío.",
      "Soria lo golpeó. —Era mecánico. Tenía dos hijas. —Entonces averigua por qué un mecánico aparecía en un corredor restringido durante una fuga. La duda cruzó brevemente el rostro de la comandante.",
      "Ada activó a distancia el sistema contra incendios. El techo descargó una espuma espesa y las cámaras quedaron cegadas. Elías utilizó las esposas para atraer a un soldado, le quitó la llave y escapó entre la confusión.",
      "Antes de abandonar la sala conectó la llave de cristal a un terminal. Buscó el nombre de Daniel Soria. Encontró una grabación clasificada.",
      "En ella, LZ-02 arrastraba a Daniel por el mismo pasillo que Elías recordaba. El técnico estaba herido. LZ-02 intentaba protegerlo. Valcárcel apareció al fondo y disparó. Después se acercó al cuerpo, recogió el arma de LZ-02 y la colocó junto a la sangre.",
      "El archivo incluía un segundo vídeo: Soria inconsciente en una camilla mientras Ada discutía con varios militares. Una máquina proyectaba estímulos directamente sobre su corteza cerebral. RECONSTRUCCIÓN DEL RECUERDO: COMPLETADA.",
      "Elías envió las imágenes al comunicador de la comandante. —Tu recuerdo fue fabricado —dijo—. El hombre que buscas todavía está dentro de esta instalación, pero no soy yo.",
      "Soria contempló la grabación sin hablar. Valcárcel ordenó cortar la transmisión. Cuando la pantalla se apagó, la comandante comprendió que podía seguir obedeciendo o descubrir cuántos recuerdos suyos habían sido escritos por otros.",
      "En el nivel inferior, Ada apoyó la mano sobre una puerta acorazada. Detrás se extendía una sala tan grande que sus límites se perdían en la oscuridad. —Bienvenido al lugar donde guardamos a los muertos —dijo.",
    ],
  },
  {
    title: "El archivo de los ausentes",
    visual:
      "Inmenso archivo subterráneo con miles de columnas de cristal luminosas que guardan memorias humanas, un hombre frente al registro dorado de su esposa fallecida, ciencia ficción elegante y oscura",
    paragraphs: [
      "Las columnas de cristal se alzaban como árboles transparentes.",
      "Había miles. Cada una contenía un entramado de luz suspendido en una solución conductora. Algunas pulsaban lentamente; otras permanecían apagadas. Bajo ellas figuraban nombres, fechas y códigos.",
      "Elías leyó las primeras placas. Un ministro. Una piloto. Dos agentes de inteligencia. Un niño de nueve años. Personas fallecidas y personas que, según los registros públicos, seguían vivas.",
      "—¿Qué es todo esto? —preguntó. —Mapas de memoria —respondió Ada—. Algunos fueron donados para investigación. Otros se obtuvieron sin consentimiento cuando Defensa tomó el control. —¿Cuántos? —Dos mil ochocientos doce. —¿Son conscientes? —No. Son estructuras. Posibilidades. Para que exista una conciencia necesitan un cerebro capaz de interpretarlas.",
      "Elías avanzó entre las columnas hasta encontrar un nombre que ya conocía. LUCÍA ORTEGA VEGA. SUJETO 000. La luz del interior tenía un tono dorado. Al acercarse, un altavoz emitió una respiración. —Elías —dijo una voz.",
      "Elías recordó la sala en la que había despertado. —La quinta cámara. La que no tenía número. Ada asintió. —Fue la de Lucía. El primer prototipo, anterior a LZ-01. No había otro Elías esperando dentro: fue allí donde ella regresó durante once minutos.",
      "Él apoyó la mano en el cristal. Ada lo apartó. —No es ella. —Ha dicho mi nombre. —Es una respuesta automática construida con patrones de voz. —Despiértala. —No.",
      "Elías la sujetó por la bata. —Me has despertado cuatro veces y ahora decides respetar a los muertos. Ada no se defendió. —Lucía padecía una enfermedad neurodegenerativa. Fue la primera persona que permitió que cartografiáramos su cerebro. Queríamos conservar sus recuerdos antes de que desaparecieran.",
      "—Queríamos. —Lázaro nació para ayudar a pacientes como ella. No para resucitar soldados.",
      "Ada abrió un archivo fechado ocho años atrás. En las imágenes aparecía Lucía: una mujer de cabello castaño, mirada serena y manos siempre ocupadas en doblar pequeños papeles. A su lado estaban Ada y el Elías original.",
      "—Tu esposa sabía que no sobreviviría —continuó—. Vosotros dos convencisteis al comité para intentar la primera restauración completa. —¿Funcionó? Ada miró la columna dorada. —Durante once minutos.",
      "La voz volvió a sonar. —Elías, ¿por qué me has dejado aquí? La pregunta penetró en él como un cuchillo. Recordó una habitación frente al mar, el olor de la lluvia y a Lucía colocando un barco de papel sobre el alféizar. Recordó prometerle que encontraría una forma de salvarla. No sabía si alguna de aquellas cosas había ocurrido.",
      "En una pantalla cercana apareció el rostro de Valcárcel. —Puedo devolvértela —dijo el general—. Entrégame la llave que llevas dentro y Lucía será la siguiente en despertar.",
      "Elías miró la columna. —No lo escuches —advirtió Ada. —Tú ya lo hiciste una vez —respondió él. Valcárcel sonrió. —Pregúntale qué dijo tu esposa durante aquellos once minutos.",
      "Ada bajó la mirada. Elías abrió el archivo de la primera resurrección.",
    ],
  },
  {
    title: "La primera resurrección",
    visual:
      "Mujer recién reconstruida despierta en una habitación clínica blanca mientras su marido le toma la mano y una científica observa monitores, escena emotiva e inquietante de ciencia ficción realista",
    paragraphs: [
      "Lucía despertó en una habitación blanca.",
      "El vídeo mostraba al Elías original sentado junto a la cama. Sostenía la mano de una mujer idéntica a su esposa, pero aquella mujer observaba el mundo como si acabara de caer en él.",
      "—¿Dónde está la ventana? —preguntó. —No hay ninguna. —Sí la hay. Puedo ver el mar. Elías la abrazó llorando. Lucía permaneció inmóvil. —Recuerdo este abrazo —dijo—, pero lo recuerdo desde tu lugar.",
      "Ada apareció en la grabación y comprobó los monitores. —La reconstrucción ha mezclado las fuentes —explicó—. Utilizamos recuerdos de familiares para completar las zonas dañadas.",
      "La mujer miró a Elías. —Recuerdo verte dormir aunque nunca te vi desde fuera. Recuerdo tu infancia. Recuerdo el día en que me conociste, pero también recuerdo cómo me mirabas. ¿Cuál de los dos soy? Elías trató de tranquilizarla. —Eres Lucía. —No. Soy la forma que Lucía dejó dentro de vosotros.",
      "Durante los siguientes minutos, la mujer sufrió cientos de recuerdos incompatibles. Lloró por padres que no reconocía y llamó hija a Ada, que era mayor que ella. Finalmente pidió que detuvieran el proceso. —No me conviertas en una habitación llena de ecos —suplicó.",
      "El Elías original desconectó la máquina. La grabación terminó con él sentado en el suelo, incapaz de soltar la mano de aquel cuerpo sin vida.",
      "Elías se apartó de la pantalla. —Yo la maté. —Respetaste su decisión —dijo Ada. —Primero decidí traerla de vuelta. —Porque estabas desesperado. Después comprendiste que una copia de la memoria no era la continuidad de una persona. —Sin embargo, me copiaste a mí.",
      "Ada cerró el archivo. —Cuando descubriste lo que Valcárcel estaba preparando, instalaste un bloqueo en el núcleo. Solo tu patrón neural podía abrirlo o destruirlo. Moriste antes de completar el sabotaje. —Y tú necesitabas mi llave. —Te necesitaba a ti. —No soy él. —Lo sé.",
      "La respuesta de Ada carecía de defensa. Esa sinceridad hizo más difícil odiarla. Las luces de las columnas comenzaron a encenderse una tras otra. Valcárcel estaba iniciando la extracción del archivo.",
      "—¿Qué pretende hacer con estos recuerdos? —No quiere resucitar a los muertos —respondió Ada—. Quiere introducirlos en los vivos.",
      "Una columna situada al final de la sala proyectó una grabación sin que ninguno de los dos la activara. Era LZ-01. Parecía recién despertado. Vestía el uniforme negro y miraba directamente a la cámara.",
      "—El primer fragmento está donde comenzó todo —dijo—. Si eres el siguiente, recuerda algo importante: no eres responsable de nuestros pecados, pero sí de lo que hagas después de conocerlos. En la parte inferior apareció una secuencia cifrada.",
      "Ada se acercó. —Es una de las firmas. —¿Cuántas necesitamos? —Cuatro.",
      "Las puertas del archivo se cerraron de golpe. Un gas blanquecino comenzó a salir por las rejillas. La voz de Valcárcel llenó la sala. —Ya tengo tres cuerpos, doctor Serrano. Solo necesito que el cuarto siga respirando.",
    ],
  },
  {
    title: "LZ-01",
    visual:
      "Grabación holográfica del primer clon LZ-01 herido frente a un código neural, dos fugitivos observan mientras gas blanco invade un archivo subterráneo, thriller de ciencia ficción realista",
    paragraphs: [
      "Ada corrió hacia el sistema de ventilación mientras Elías disparaba contra las rejillas. El gas descendía formando una niebla densa. —No es venenoso —dijo ella—. Quieren dormirte. —Eso no mejora la situación.",
      "Elías utilizó una bala para romper la tubería de refrigeración de una columna vacía. El cambio de presión bloqueó los conductos y activó el protocolo contra fugas. Las compuertas se abrieron. Escaparon hacia una cámara de servicio situada bajo el archivo.",
      "Allí pudieron examinar el mensaje de LZ-01. La primera copia había permanecido despierta nueve días. Los informes lo describían como estable, obediente y convencido de ser el Elías original. Durante ese tiempo firmó órdenes de transferencia, interrogó a prisioneros y ayudó a desarrollar el Protocolo Concordia.",
      "—Trabajó para Valcárcel —dijo Elías. —Hasta que encontró la grabación de Lucía —respondió Ada—. Entonces comprendió lo que era.",
      "LZ-01 había intentado destruir el archivo. Fracasó y fue abatido junto al reactor. Antes de morir ocultó una parte del código de cancelación dentro de su propia firma neural.",
      "LZ-02 encontró ese fragmento. Añadió otro y trató de sacar las pruebas de la instalación. Durante la fuga fue activado mediante una orden implantada y perdió el control. Daniel Soria murió intentando ayudarlo.",
      "LZ-03 despertó sabiendo lo ocurrido. Consiguió interrumpir la energía, evacuar a gran parte del personal y herir a Ada durante uno de sus episodios. Después se disparó para impedir que Valcárcel utilizara su cuerpo.",
      "—Cada uno despertó con menos recuerdos —dijo Elías. —Porque eliminé todas las zonas donde encontramos órdenes de Valcárcel. Tu restauración está incompleta y creo que eres el primero que puede elegir sin que sepamos de antemano qué harás. Pero tu mapa contiene restos de las otras versiones. No puedo garantizar que no quede alguna ruta dormida que nunca llegamos a localizar.",
      "En una pantalla apareció una llamada de Soria. —He comprobado el vídeo de mi hermano —dijo la comandante—. Es auténtico. —Entonces sabes quién lo mató. —Sé quién disparó. Todavía no sé por qué.",
      "Ada le envió los informes de manipulación. Soria guardó silencio al descubrir su propia firma autorizando el tratamiento que había borrado sus recuerdos. También ella había consentido algo que no recordaba.",
      "—Valcárcel se dirige al núcleo —informó—. Tiene a siete hombres conmigo y otros cinco leales únicamente a él. —¿De qué lado estás? —preguntó Elías. —Del lado que me devuelva la verdad. —La verdad no puede devolverse. Solo puedes decidir qué hacer con ella.",
      "Soria respiró hondo. —Entonces decidamos deprisa. En setenta y ocho minutos se abrirá una ventana de comunicación con la red militar. Cuando eso ocurra, Concordia podrá transmitirse. —¿Transmitir qué? Ada proyectó el esquema de doce centros de mando conectados a la red terapéutica Mnemósine. —Un recuerdo —dijo—. Uno capaz de iniciar o detener una guerra.",
    ],
  },
  {
    title: "Una guerra que aún no existe",
    visual:
      "General autoritario aparece en múltiples pantallas rodeado de simulaciones de ciudades destruidas y doce mandos militares conectados, cuenta atrás roja, ciencia ficción política cinematográfica",
    paragraphs: [
      "Valcárcel solicitó hablar con ellos.",
      "Su rostro apareció en todas las pantallas del nivel inferior. Detrás se veía el núcleo del proyecto: una estructura esférica rodeada de anillos magnéticos.",
      "—Dentro de cuarenta y ocho horas —dijo—, dos potencias iniciarán un conflicto que nadie podrá contener. Los servicios de inteligencia han confirmado el ataque. Millones de personas morirán durante la primera semana. Ada negó con la cabeza. —Ningún informe puede predecir eso con certeza. —La certeza es un lujo de quienes no deben tomar decisiones.",
      "Valcárcel mostró doce expedientes. Generales, ministros y responsables de defensa. Todos utilizaban implantes Mnemósine para tratar el estrés traumático.",
      "—Concordia les hará recordar una guerra que todavía no ha ocurrido —explicó—. Recordarán ciudades destruidas, familias muertas y órdenes de lanzamiento de las que se arrepentirán el resto de sus vidas. Cuando llegue el momento de atacar, no lo harán.",
      "Elías contempló las simulaciones. Las imágenes parecían recuerdos auténticos: una niña cubierta de ceniza, hospitales sin luz, soldados caminando entre edificios calcinados. —Quieres torturarlos con vidas falsas. —Quiero salvar millones de vidas reales.",
      "—¿Y después? —preguntó Ada—. ¿Implantaréis recuerdos de lealtad a los disidentes? ¿Confesiones en quienes se nieguen a confesar? ¿Amor por el gobierno adecuado? —Después habrá un mundo en el que podamos discutir esos límites.",
      "Valcárcel dirigió la mirada hacia Elías. —Tú comprendías la necesidad. El Protocolo Concordia lleva tu firma. —También lleva mi orden de destrucción. —Porque siempre fuiste brillante y débil en partes iguales.",
      "El general activó la columna de Lucía. Su voz llenó la sala. —Elías… —Puedo reconstruirla sin los errores del primer intento —prometió Valcárcel—. Hemos mejorado. Dame el patrón de autorización y ambos podréis abandonar este lugar.",
      "Durante un instante, Elías quiso creerle. No porque recordara realmente a Lucía, sino porque sentía el espacio que había dejado. Era una ausencia heredada, pero dolía como una propia.",
      "Miró a Ada. —Si la despertáramos, ¿sería una persona? —Sí —respondió ella—. Una persona nueva, condenada a creer que debe continuar una vida que no vivió.",
      "Elías apagó la pantalla. —No utilizaremos a los muertos para gobernar a los vivos. La voz de Valcárcel regresó por los altavoces. —Eso ya lo dijiste tres veces.",
      "En el plano, el contador cambió. INICIO DE CONCORDIA: 01:03:16. —Y las tres veces moriste antes de impedirlo —añadió el general.",
    ],
  },
  {
    title: "La traición",
    visual:
      "Científica sostiene una jeringa frente a un hombre conectado a un aro neural, después huye con un dispositivo de firmas mientras él queda tras un cristal, tensión cinematográfica realista",
    paragraphs: [
      "Ada condujo a Elías hasta una sala de calibración.",
      "Para reunir las firmas de LZ-01, LZ-02 y LZ-03 debían combinar sus registros con la actividad cerebral de LZ-04. Elías se sentó dentro de un aro metálico mientras ella colocaba sensores alrededor de su cabeza.",
      "—Esto puede despertar recuerdos que Valcárcel implantó —advirtió. —Hazlo. Las luces se volvieron blancas.",
      "Elías vio tres muertes. Sintió las balas que atravesaron a LZ-01 junto al reactor. Vivió la descarga que hizo caer a LZ-02 mientras Daniel Soria se desangraba en sus brazos. Experimentó el instante en que LZ-03 comprendió que estaba a punto de disparar contra Ada y volvió el arma hacia sí mismo.",
      "Abrió los ojos gritando. Ada sostenía una jeringa. —Lo siento —dijo. La aguja penetró en su cuello.",
      "Elías despertó encerrado detrás de un cristal. Ada había desaparecido y el dispositivo que contenía las tres firmas ya no estaba. —Ada —golpeó la puerta—. ¿Qué has hecho?",
      "Una grabación comenzó a reproducirse. Aparecía el Elías original. —Si estás viendo esto, probablemente creerás que Ada te ha traicionado —decía—. No confíes en ella. Intentará salvarte incluso cuando el mundo necesite que mueras.",
      "El vídeo continuaba más allá del punto donde se había detenido la primera vez. —Yo le pedí que no me devolviera. Sé que romperá esa promesa porque siempre confundimos el amor con la incapacidad de despedirnos. Si despiertas, recuerda que ella no es tu creadora ni tu dueña. Tampoco permitas que se convierta en tu verdugo. La última decisión debe ser tuya.",
      "Elías comprendió entonces por qué Ada había tomado las firmas. No pretendía ejecutar el Protocolo Ceniza, que necesitaba cuatro patrones, sino utilizar las tres primeras para abrir los cierres exteriores y provocar una sobrecarga manual de los anillos magnéticos. El núcleo quedaría destruido, pero alguien tendría que permanecer en la cámara regulando la reacción hasta el colapso. Ada no intentaba completar el sacrificio de Elías. Intentaba ocupar su lugar.",
      "La voz de Valcárcel apareció en la frecuencia general. —Doctor Serrano bajo custodia. Una cámara mostró a Ada arrodillada ante el general. Dos soldados la sujetaban mientras Valcárcel examinaba el dispositivo de las firmas.",
      "—Gracias por traerme las tres primeras partes —dijo—. Ahora solo falta el cuarto hombre.",
      "Elías buscó una salida. La celda no tenía cerraduras visibles, pero su mano encontró instintivamente una irregularidad bajo el asiento. Presionó dos veces, esperó y volvió a presionar. Un panel se abrió. Dentro había una pequeña herramienta y una nota escrita a mano: SIEMPRE ESCONDES UNA SALIDA EN LAS HABITACIONES QUE DISEÑAS.",
      "No sabía cuál de sus versiones la había dejado allí. Mientras desmontaba el cierre, Soria contactó con él. —Los hombres de Valcárcel controlan el núcleo. Puedo darte siete minutos antes de que descubran que he cambiado de bando.",
      "—¿Por qué debería confiar en ti? —No deberías. Pero mi hermano confió en uno de vosotros. La puerta se abrió. Elías recogió el fusil. —Entonces procura que esta vez valga la pena.",
    ],
  },
  {
    title: "El cuarto hombre",
    visual:
      "Agente arrodillado lucha contra una orden implantada mientras apunta involuntariamente a una comandante, general y científica cautiva junto a un núcleo esférico, acción de ciencia ficción realista",
    paragraphs: [
      "Soria lo esperaba en un corredor sin cámaras. Le entregó un arma y una cápsula inhibidora. —Valcárcel utiliza frases de activación —explicó—. Esta cápsula puede interrumpir la respuesta durante unos minutos. —¿Qué frase utilizó con LZ-03? —No lo sabemos. —Sí lo sabéis. Solo que no la recuerdas. Soria soportó la acusación sin responder.",
      "Llegaron al núcleo por una pasarela elevada. Ada permanecía atada frente a Valcárcel. El dispositivo de las firmas estaba conectado a la consola principal.",
      "El general sonrió al ver a Elías. —Siempre llegas por la misma puerta. —Y tú siempre hablas demasiado. —Necesito que comprendas lo que eres antes de pedirme que te obedezca.",
      "Valcárcel abrió el expediente LZ-04. Elías no había recibido únicamente el mapa neural del original. Ada había combinado restos de las tres restauraciones anteriores. Sus miedos, sus descubrimientos y los últimos minutos de sus vidas se encontraban entrelazados dentro de él.",
      "—No eres la cuarta copia de Elías Vega —dijo el general—. Eres una copia de todas las copias. Un hombre construido con tres fracasos. —Por eso puedo encontrar sus firmas. —Y por eso no puedes distinguir una decisión propia de una orden heredada.",
      "Valcárcel se acercó. —San Telmo no tiene campanas. Las palabras atravesaron a Elías.",
      "Su cuerpo se volvió contra Soria. Le golpeó el brazo, le arrebató el arma y apuntó hacia su cabeza. Él seguía consciente, atrapado detrás de sus propios ojos. Soria introdujo la cápsula inhibidora bajo su mandíbula.",
      "Elías cayó de rodillas. Dentro de su mente escuchó órdenes pronunciadas con su propia voz: proteger el núcleo, entregar las firmas, eliminar a cualquiera que interfiriese.",
      "Valcárcel tomó el arma. —La libertad es solo una historia que el cerebro se cuenta después de obedecer.",
      "Ada se lanzó contra el general. El disparo pasó junto a su cabeza. Soria derribó a uno de los guardias y Elías, todavía temblando, consiguió levantarse.",
      "Valcárcel retrocedió hacia el ascensor del núcleo con el dispositivo de las firmas. —Podría haberme matado —dijo Soria. —Sí. —¿Por qué no lo hiciste? Elías observó sus manos. —Porque la orden quería hacerlo.",
      "Comprendió que aquella negativa, pequeña y dolorosa, era la primera cosa de la que podía estar seguro. No pertenecía al Elías original, ni a las tres copias, ni a Ada. Era suya.",
      "Soria liberó a Ada. La científica se arrodilló junto a Elías y comprendió lo que había ocurrido. —La frase estaba escondida en los restos de LZ-03. Limpié el mapa del original, pero al utilizar fragmentos de las restauraciones anteriores volví a introducir la orden sin saberlo. —Entonces no soy libre. —Has escuchado la orden y has conseguido resistirla. Eso no te hace menos libre.",
      "Valcárcel cerró las puertas del ascensor. En la consola apareció un nuevo mensaje: PROTOCOLO CONCORDIA ACELERADO. Quedaban cuarenta y un minutos.",
    ],
  },
  {
    title: "Memoria de fuego",
    visual:
      "Centro de datos subterráneo calcinado, comandante contempla dos recuerdos contradictorios mientras un holograma de LZ-02 revela una firma oculta entre servidores quemados, ciencia ficción oscura",
    paragraphs: [
      "El camino más corto hacia el núcleo atravesaba el centro de datos destruido durante la fuga de LZ-02.",
      "El fuego había fundido las paredes y convertido los servidores en bloques negros. El aire todavía olía a plástico quemado, aunque habían pasado meses.",
      "Soria se detuvo ante una marca de sangre. —Aquí encontraron a Daniel.",
      "Elías vio cómo los recuerdos implantados de la comandante trataban de imponerse a las imágenes verdaderas. En una versión, LZ-02 ejecutaba a su hermano. En otra, intentaba arrastrarlo lejos de Valcárcel.",
      "Soria cerró los ojos. —Puedo recordar las dos cosas. —Un recuerdo no se vuelve verdadero porque duela —dijo Ada. —Tampoco deja de doler porque sea falso.",
      "Ada encontró el registro de LZ-02 dentro de un servidor protegido. El vídeo mostraba al segundo Elías gravemente herido. —Si has llegado hasta aquí, Valcárcel habrá intentado convertir nuestros errores en una prueba de que no podemos elegir —decía—. No le creas. Una decisión no vale menos porque otros la hayan tomado antes.",
      "LZ-02 mostró una secuencia dibujada sobre el suelo con su propia sangre. —La segunda firma está escondida en el recuerdo del fuego. La tercera no está en un archivo. LZ-03 la llevó consigo.",
      "Elías recordó la llave de cristal encontrada en la mano del cadáver. La abrió por la mitad y descubrió un filamento casi invisible. Al conectarlo, apareció el tercer patrón.",
      "La primera firma tampoco se había perdido con el dispositivo: al contemplarla en el Archivo de Engramas, la memoria compuesta de Elías había retenido la secuencia de LZ-01 con una precisión que él mismo desconocía. La reprodujo en la consola y Ada unió los tres patrones en una copia nueva. Tres firmas completas. Faltaba la suya.",
      "El sistema de seguridad ARGOS los detectó. Las puertas cortafuegos comenzaron a cerrarse. Ada cruzó primero. Elías pasó después, pero Soria quedó al otro lado. Un grupo de soldados apareció detrás de ella.",
      "—Sigue —ordenó la comandante—. Yo los detendré. —No voy a dejarte. —Tu segunda versión no pudo salvar a mi hermano. Permite que yo decida qué hacer con lo que queda de su muerte.",
      "Soria se volvió hacia los soldados. En lugar de disparar, proyectó sobre las paredes las imágenes de Valcárcel asesinando a Daniel y manipulando sus recuerdos. —Miradlo —les dijo—. Después preguntaos qué parte de vuestra lealtad os pertenece.",
      "Los soldados redujeron la velocidad. Elías y Ada continuaron mientras detrás de ellos comenzaba una discusión que pronto se transformó en disparos.",
      "—¿Sobrevivirá? —preguntó Elías. —No puedo saberlo. —Parece que esa es tu respuesta para todo. —Es la respuesta más honesta que tiene la ciencia.",
      "Llegaron a una cámara de memoria intacta. En el centro los esperaba el último registro del Elías original. Ada no quiso acercarse. —Aquí murió —dijo.",
    ],
  },
  {
    title: "El día que murió Elías Vega",
    visual:
      "Científico agente mantiene abierta una compuerta en un laboratorio en llamas para salvar a una mujer mientras coloca cargas de demolición, sacrificio heroico de ciencia ficción realista",
    paragraphs: [
      "La grabación comenzó con la evacuación del complejo.",
      "El Elías original recorría los laboratorios colocando cargas mientras Ada liberaba a los sujetos retenidos. Algunos eran soldados heridos. Otros eran civiles secuestrados para completar mapas de figuras políticas y militares.",
      "Valcárcel había utilizado recuerdos de familiares, enemigos y amantes para construir personalidades controlables. Elías descubrió entonces la verdadera finalidad de Concordia.",
      "El recuerdo de la guerra era solo la primera demostración. Después llegarían identidades completas: presidentes obedientes, agentes reemplazables y testigos incapaces de distinguir lo vivido de lo implantado.",
      "El original activó la destrucción del núcleo, pero Valcárcel bloqueó la orden utilizando las propias credenciales de Elías. —Todos los archivos llevan mi firma —decía a la cámara—. Fue así como me venció. Construí un sistema que solo confiaba en mí y después creó tantos de mí como necesitó.",
      "Antes de colocar la última carga, Elías dividió el código de destrucción en cuatro patrones. Confiaba en que ninguna copia pudiera ser obligada a revelar el código completo.",
      "La explosión se inició antes de tiempo. Ada quedó atrapada detrás de una compuerta. Elías regresó a buscarla y mantuvo abierta la puerta manualmente mientras el laboratorio se derrumbaba.",
      "—Prométeme que no me traerás de vuelta —le pidió. —Todavía puedes salir. —Promételo. Ada consiguió atravesar la compuerta. —Te lo prometo. Elías sonrió, aunque sabía que estaba mintiendo.",
      "La puerta cayó entre ambos. La última imagen mostraba al original sentado entre las llamas, mirando directamente a la cámara. —Si uno de vosotros despierta algún día, no pierdas tiempo preguntándote si eres yo. No lo eres. Yo terminaré aquí.",
      "Respiró con dificultad. —Pregunta qué vas a hacer con lo que te he dejado. La grabación terminó.",
      "Ada permaneció inmóvil. —Rompí la promesa nueve días después —confesó—. Restauré a LZ-01 porque solo tu patrón podía detener el proyecto. Cuando murió, sellaron la instalación y durante años busqué otra forma de abrir el núcleo. Valcárcel reactivó Concordia hace unos meses y entonces desperté al segundo. Después al tercero. —Y después a mí. —Cada vez me decía que sería la última. Cada vez despertaba a alguien y le entregaba una guerra que no había elegido.",
      "Elías comprendió el cansancio de aquella mujer. No era el dolor de haber perdido una sola vez al mismo hombre, sino el de haber conocido cuatro versiones distintas y haberlas conducido hacia la misma muerte.",
      "—¿Por qué me sedaste? —preguntó. —Porque la sobrecarga manual podía destruir el núcleo sin tu cuarta firma. Quien la iniciara tendría que quedarse dentro, y pensaba hacerlo yo. —Valcárcel tenía razón en algo. No puedes dejar morir aquello que amas. Ada lo miró con los ojos llenos de lágrimas. —Tú no eres el hombre al que amé. —No. —Pero tampoco quiero verte morir.",
      "Elías tomó su mano. —Entonces ayúdame a conseguir que esta vez no muera nadie más. Una explosión estremeció el nivel inferior. La voz de Soria llegó entre interferencias. —El núcleo está abierto. Valcárcel ha iniciado la transmisión. Quedaban diecinueve minutos.",
    ],
  },
  {
    title: "Cuatro firmas",
    visual:
      "Cuatro patrones neurales luminosos convergen sobre una consola mientras un hombre contempla el recuerdo de una mujer junto al mar y soldados irrumpen, clímax tecnológico realista",
    paragraphs: [
      "Las tres primeras firmas formaban una secuencia incompleta.",
      "La cuarta no podía extraerse de Elías mediante fuerza. El original la había vinculado a un acto voluntario: LZ-04 debía elegir un recuerdo y renunciar para siempre a él. Esa pérdida generaría un patrón neural irrepetible.",
      "—¿Qué recuerdo? —preguntó Ada. —El sistema no lo especifica.",
      "Elías pensó en la playa, en la cocina y en los barcos de papel. No sabía si aquellas escenas habían sucedido, pero constituían lo único parecido a una vida que poseía. —Utilizaré a Lucía. —Es el núcleo más estable de tu identidad. Si lo eliminas, podrías perder mucho más que su recuerdo. —Quizá por eso el original lo eligió.",
      "Se conectó a la consola. La imagen de Lucía apareció ante él: sonreía frente al mar mientras doblaba una hoja. El sistema formuló una pregunta: ¿AUTORIZA LA RENUNCIA?",
      "Antes de que pudiera responder, un disparo destruyó la consola. Valcárcel apareció en la entrada acompañado por dos soldados. Llevaba el dispositivo de las firmas sujeto al pecho.",
      "—Cuatro hombres con el mismo rostro —dijo—, y todos convencidos de que sacrificarse los hace libres. Ada se interpuso. —Concordia no evitará una guerra. Solo te dará el poder de decidir qué recuerda el mundo.",
      "—El mundo siempre ha sido gobernado por relatos, doctora. Yo solo he eliminado la parte imprevisible. Una detonación abrió la puerta lateral. Soria apareció detrás de los soldados, cojeando y acompañada por dos hombres que habían visto la grabación de Daniel. Sangraba por una pierna, pero mantenía el arma firme. —General, queda arrestado.",
      "Valcárcel rio. —¿Por orden de quién? ¿De los recuerdos que yo te permití conservar? Soria disparó contra el dispositivo de su pecho. El impacto no lo destruyó, pero desconectó una de las firmas.",
      "Los soldados se volvieron hacia ella. Elías aprovechó la distracción para derribar al primero. Ada luchó por alcanzar la consola mientras Soria se enfrentaba al segundo.",
      "El disparo había desprendido el módulo de LZ-03. Valcárcel lo arrancó del arnés antes de huir hacia el ascensor. Elías recuperó el resto del dispositivo, que aún conservaba las firmas de LZ-01 y LZ-02, pero la consola destruida se había llevado la copia reconstruida desde la llave. —Podemos reconstruirla otra vez —dijo Ada. —No a tiempo.",
      "Soria recogió el arma de uno de los soldados. —Valcárcel se dirige a la antena central. Desde allí puede completar la transmisión manualmente.",
      "Las luces del complejo adquirieron un tono azul. PROTOCOLO CONCORDIA CONECTADO. En las paredes aparecieron imágenes de ciudades que todavía no habían sido destruidas. Los tres miraron el contador. Doce minutos.",
    ],
  },
  {
    title: "La ciudad bajo la montaña",
    visual:
      "Ciudad artificial abandonada construida dentro de una montaña, fachadas domésticas bajo techo industrial, fugitivos corren entre soldados y una casa contiene un barco de papel, ciencia ficción realista",
    paragraphs: [
      "Para llegar a la antena debían atravesar una ciudad que no existía.",
      "Oculta bajo la montaña había una reproducción completa de varias calles: edificios, comercios, viviendas e incluso una pequeña plaza. Todo había sido construido para probar a los sujetos restaurados en escenarios familiares.",
      "Elías reconoció una casa situada al final de la calle. —Crecí aquí. Ada negó con la cabeza. —Creciste en un edificio parecido. Este lugar fue creado a partir de tus recuerdos.",
      "Entraron. En la cocina estaba la mesa que Elías había visto junto a Lucía. En el dormitorio había fotografías de una infancia que no podía recordar. Los cajones contenían cartas, facturas y objetos envejecidos artificialmente.",
      "—¿Cuántos de mis recuerdos nacieron aquí? —Ninguno —respondió Ada—. Pero comprobamos su estabilidad recreando los espacios. El cerebro completa lo que le mostramos. A veces añadió detalles que nunca estuvieron en el registro original.",
      "Elías encontró un barco de papel sobre el alféizar. Dentro había una frase escrita por LZ-03: NO IMPORTA DÓNDE NACIÓ EL RECUERDO. IMPORTA LO QUE TE PIDE QUE HAGAS. Bajo la frase aparecía la tercera firma completa.",
      "LZ-03 había sabido que su cuerpo podía caer en manos de Valcárcel y había ocultado una copia allí. Ada la conectó a los dos módulos supervivientes. Las tres primeras firmas volvieron a estar completas. El cuarto espacio permanecía vacío, pero el protocolo de destrucción ya podía armarse. —Podemos detenerlo —dijo Ada—, si decides completar la última firma dentro del núcleo.",
      "Un grupo de soldados entró en la calle artificial. Soria se situó tras un vehículo sin motor y respondió al fuego. —Seguid —ordenó. —Vienes con nosotros —dijo Elías. —Alguien debe impedir que suban.",
      "Esta vez, dos soldados de Cerbero se colocaron junto a ella. Habían visto las pruebas contra Valcárcel.",
      "Elías comprendió que no podía salvar a todos obligándolos a retirarse. Eso también habría sido una forma de arrebatarles la elección. Él y Ada corrieron hacia el túnel del núcleo.",
      "Mientras avanzaban, las fachadas se iluminaron y decenas de voces comenzaron a repetir recuerdos falsos: declaraciones de guerra, despedidas, ciudades bombardeadas. La transmisión estaba cargándose.",
      "Al final del túnel encontraron la entrada a la cámara central. Valcárcel los esperaba junto a la esfera de memoria. —Bienvenidos a vuestro verdadero hogar —dijo. El contador marcaba seis minutos.",
    ],
  },
  {
    title: "La orden Lázaro",
    visual:
      "Esfera de memoria suspendida sobre un pozo, miles de filamentos conectados a una red militar mundial, agente y científica enfrentan a un general durante una cuenta atrás, ciencia ficción épica realista",
    paragraphs: [
      "La esfera giraba suspendida sobre un pozo sin fondo visible.",
      "Miles de filamentos de luz conectaban el archivo con la antena. En las pantallas, los doce objetivos de Concordia aparecían preparados para recibir el paquete de memoria.",
      "Valcárcel había conectado la firma de LZ-03 a la consola. —La transmisión ya no necesita vuestra autorización —dijo—. Solo vuestra incapacidad para detenerla.",
      "Elías levantó el dispositivo con las tres firmas y el cuarto espacio todavía vacío. —Tengo preparada la orden de destrucción. —Y para completarla deberás entrar en la esfera y entregar la última firma —respondió Valcárcel—. El proceso borrará el patrón que te mantiene estable. Ada no te lo ha contado todo.",
      "Elías miró hacia ella. —Es posible que sobrevivas —dijo Ada—, pero perderás toda tu memoria autobiográfica reconstruida. —Morirá por quinta vez —afirmó Valcárcel—. Y tú despertarás al siguiente en cuanto vuelvas a sentirte sola. —No hay otro cuerpo —respondió Ada. —Los habrá. Siempre habrá gobiernos dispuestos a fabricar uno.",
      "Valcárcel activó una señal. ORDEN LÁZARO.",
      "Los soldados de Cerbero recibieron simultáneamente recuerdos contradictorios. Algunos vieron a sus compañeros como enemigos. Otros recordaron órdenes que jamás habían recibido. Los disparos resonaron por toda la ciudad subterránea.",
      "Soria abrió una frecuencia general. —Escuchadme. Lo que estáis viendo no es real. Valcárcel ha utilizado el proyecto contra nosotros. Bajad las armas y comprobad las grabaciones. Su voz consiguió detener a algunos. Otros siguieron luchando contra amenazas que solo existían dentro de sus cabezas.",
      "Ada alcanzó la consola secundaria y cortó nueve de las doce conexiones. Las tres restantes se mantuvieron activas. Valcárcel le disparó.",
      "Elías la sujetó antes de que cayera al pozo. La bala había atravesado su abdomen. —Ve —susurró ella—. Yo cerraré las conexiones. —Te desangrarás. —Llevo intentando decidir por ti desde que despertaste. No me obligues a hacerlo otra vez.",
      "Elías la dejó junto a la consola y avanzó hacia la esfera. Valcárcel se interpuso. —Si destruyes el archivo, no matarás cuerpos, pero eliminarás miles de personas posibles. Lucía podría volver. Tu esposa, mi hijo, todos los que perdimos.",
      "—No quieres devolverles la vida. —Quiero que su muerte sirva para algo. —Ya sirvió. Nos enseñó que no nos pertenecían.",
      "Valcárcel disparó. La bala rozó la cabeza de Elías. El contador marcó sesenta segundos. Elías saltó hacia la plataforma de la esfera.",
    ],
  },
  {
    title: "Lo que debe morir",
    visual:
      "Dos hombres luchan sobre una pasarela estrecha suspendida sobre un pozo, frente a una esfera neural abierta y miles de nombres luminosos, clímax de acción de ciencia ficción realista",
    paragraphs: [
      "La lucha ocurrió sobre una pasarela de menos de un metro de anchura.",
      "Valcárcel era mayor, pero conocía cada movimiento que el cuerpo de Elías había aprendido. Había estudiado a las cuatro versiones. Anticipaba sus golpes y sabía qué heridas todavía no habían terminado de cerrar.",
      "—No tienes ninguna decisión propia —dijo mientras lo golpeaba contra la barandilla—. Incluso tu rebeldía fue diseñada por el original. Elías recibió otro golpe y sintió el vacío a su espalda. —Puede ser.",
      "Bloqueó el brazo de Valcárcel. —Pero tú llevas años obedeciendo al miedo de perder el control. El general cayó sobre la plataforma. Elías alcanzó la entrada de la esfera e introdujo las tres firmas recuperadas.",
      "PROTOCOLO CENIZA ARMADO. CUARTA FIRMA PENDIENTE. El sistema explicó las consecuencias: todos los mapas almacenados serían destruidos, las redes de propagación quedarían inutilizadas y la capa autobiográfica reconstruida de LZ-04 sería borrada al generar la firma final. No moriría necesariamente. Pero dejaría de recordar quién era.",
      "Valcárcel se levantó con el rostro ensangrentado. —Todavía puedes conservar el archivo —dijo—. Desconéctalo y llévatelo. Nadie tendrá que desaparecer.",
      "Elías contempló los nombres de las columnas. Miles de vidas reducidas a materiales utilizables. Algunas habían sido entregadas voluntariamente; otras, robadas. Conservarlas significaba aceptar que alguien volvería a usarlas. Destruirlas significaba cerrar para siempre una puerta que la humanidad quizá pudiera aprender algún día a cruzar.",
      "Ada habló desde la consola. —No puedo elegir por ellos. Tampoco por ti. El contador llegó a veinte segundos.",
      "Elías apoyó la mano sobre el lector. —La muerte no conserva secretos. La esfera se abrió.",
      "Filamentos de luz rodearon su cabeza. El sistema entró en sus recuerdos buscando el patrón de renuncia.",
      "Valcárcel se lanzó hacia él, pero la compuerta de mantenimiento se abrió a espaldas del general. Soria había dejado a los dos soldados conteniendo el combate en la ciudad artificial y había seguido el conducto de servicio hasta la cámara. Apareció cojeando en la entrada y disparó al suelo frente a Valcárcel. —Se acabó. —Si lo desconectas, la transmisión continuará —advirtió el general. Soria bajó ligeramente el arma.",
      "El general aprovechó el instante y corrió hacia la consola. Ada activó la última barrera. Una descarga lanzó a Valcárcel contra el suelo.",
      "El contador llegó a cero. Las tres conexiones restantes comenzaron a transmitir. Elías cerró los ojos y entró en el último lugar que todavía le pertenecía.",
    ],
  },
  {
    title: "El último recuerdo",
    visual:
      "Playa gris silenciosa dentro de una memoria, un hombre se sienta junto a una mujer que dobla un barco de papel mientras el paisaje digital se desintegra, ciencia ficción emotiva realista",
    paragraphs: [
      "Estaba en la playa.",
      "El cielo tenía el color del metal y el mar avanzaba sin producir sonido. Lucía se encontraba sentada sobre la arena, doblando un papel.",
      "Elías sabía que no era ella. Era un refugio construido con recuerdos incompletos, restos de grabaciones y deseos heredados. Aun así, se sentó a su lado.",
      "—No recuerdo haberte amado —dijo. —Tu cuerpo sí. —Mi cuerpo recuerda demasiadas cosas. —Entonces no le pidas que decida quién eres.",
      "Elías observó el agua inmóvil. —Si ejecuto el protocolo, desaparecerás. —Ya desaparecí. —Podríamos despertarte otra vez. —¿Para quién? ¿Para ti o para mí? Elías no supo responder.",
      "Lucía dejó el barco sobre la arena. —Pasaste años creyendo que amar era impedir que algo terminara. Pero las cosas no valen menos porque terminen.",
      "El paisaje comenzó a romperse. Detrás del mar aparecieron los laboratorios, el reactor y los rostros de LZ-01, LZ-02 y LZ-03. —¿Qué quedará de mí? —preguntó Elías. —Lo que hagas antes de olvidarlo.",
      "En el mundo real, Valcárcel consiguió levantarse. Se abalanzó sobre Ada y trató de desconectar la esfera. Soria lo sujetó.",
      "El general forcejeó hasta alcanzar un cable neural. Cuando lo tocó, miles de recuerdos entraron en su mente al mismo tiempo: el miedo de los sujetos retenidos, la muerte de Daniel, las últimas palabras de Lucía y las cuatro agonías de Elías.",
      "Valcárcel cayó gritando. No eran castigos inventados. Eran las memorias que había utilizado como herramientas. Ada cerró las tres conexiones restantes.",
      "Dentro de la esfera, Elías tomó el barco de papel. El sistema le preguntó por última vez: ¿AUTORIZA LA RENUNCIA A SU MEMORIA AUTOBIOGRÁFICA?",
      "Pensó en el hombre original, muerto entre las llamas. Pensó en las tres copias que habían luchado sin saber si sus decisiones les pertenecían. Comprendió que no tenía que demostrar que era uno de ellos. Bastaba con responder por sí mismo.",
      "—Autorizo. El mar recuperó su sonido. Lucía sonrió. —Vivir no es regresar, Elías. La primera ola alcanzó el barco de papel. —Es continuar.",
      "La renuncia generó la cuarta firma. El Protocolo Ceniza quedó completo y la luz lo borró todo. Las columnas del archivo se apagaron simultáneamente. La transmisión quedó interrumpida. Los patrones de Concordia se deshicieron antes de llegar a los tres objetivos. El Proyecto Lázaro dejó de existir.",
      "Cuando Ada llegó hasta la esfera, encontró a Elías tendido en el interior. Respiraba. Abrió los ojos y la miró sin reconocerla. —¿Quién soy? —preguntó.",
    ],
  },
  {
    title: "Un nombre para mañana",
    visual:
      "Hombre sin recuerdos y una científica frente al mar gris, un pequeño barco de papel cruza la primera ola al amanecer, final esperanzador de ciencia ficción cinematográfica realista",
    paragraphs: [
      "Seis meses después, la entrada a la instalación fue sellada con hormigón.",
      "Las pruebas recuperadas provocaron detenciones, dimisiones y una investigación internacional. Valcárcel sobrevivió, pero no volvió a distinguir completamente sus recuerdos de los de sus víctimas. Pasaba los días escribiendo nombres en las paredes de una habitación vigilada.",
      "Inés Soria declaró durante catorce semanas. Después dejó el ejército. Sabía que Valcárcel había disparado a su hermano porque las grabaciones lo demostraban, pero conservó dos recuerdos incompatibles de aquel día. Aceptó que quizá nunca recuperaría la certeza sobre qué había visto, oído y sentido realmente.",
      "Ada sobrevivió al disparo. Visitaba a Elías todos los jueves en el centro de rehabilitación. Él conservaba el lenguaje, los conocimientos y buena parte de sus habilidades, pero había perdido cualquier recuerdo personal anterior a la destrucción del proyecto.",
      "Sabía conducir, disparar y reparar un sistema de refrigeración. No sabía quién le había enseñado.",
      "La primera vez que Ada le entregó su expediente, Elías no quiso abrirlo. —Ahí dentro hay una vida completa —dijo ella. —La vida de otro hombre. —También están las decisiones de los que vinieron después. —Puedo leerlas algún día. Pero no quiero convertirlas en órdenes. Ada asintió. Había aprendido, al fin, a no decidir por él.",
      "Soria acudió una mañana y dejó sobre la mesa la antigua tarjeta de identificación. ELÍAS VEGA. DIRECTOR DEL PROYECTO. —No sé si te pertenece —dijo—. Pero fuiste tú quien me enseñó la verdad sobre mi hermano. —¿Cuál de nosotros? —Importa menos de lo que crees.",
      "Elías conservó la tarjeta, aunque no volvió a utilizarla. Cuando le permitieron abandonar el centro eligió llamarse Elías. No porque se considerara la continuación del fundador de Lázaro, sino porque un nombre podía ser también una promesa.",
      "Pidió que lo llevaran al mar. Ada lo acompañó hasta una playa de cielo gris. Ninguno de los dos habló del proyecto, de Lucía ni de los hombres que habían compartido su rostro.",
      "Elías se sentó sobre la arena. Encontró una hoja doblada dentro del bolsillo de su chaqueta. Ada juró que no la había puesto allí. Sus manos comenzaron a moverse.",
      "Dobló el papel por la mitad, marcó las esquinas y levantó una pequeña vela. No sabía de dónde procedía aquel gesto. Quizá era una habilidad que el protocolo no había conseguido borrar. Quizá la había aprendido después. Quizá algunas cosas sobrevivían sin necesidad de convertirse en recuerdos.",
      "Colocó el barco junto al agua. —¿Crees que volverá? —preguntó Ada. Elías observó cómo la corriente se lo llevaba. —No. El barco superó la primera ola. —Pero puede seguir adelante.",
      "Permaneció mirando el horizonte hasta que el papel desapareció. Por primera vez desde que había abierto los ojos en la cámara cuatro, Elías no sintió que estuviera regresando de ninguna parte. Sintió que acababa de empezar.",
    ],
  },
];

export const lazarusChapters: Chapter[] = lazarusChapterDrafts.map(
  ({ title, paragraphs, visual }, index) => {
    const number = index + 1;
    const wordCount = paragraphs.join(" ").trim().split(/\s+/).length;

    return {
      number,
      title,
      readingMinutes: Math.max(3, Math.ceil(wordCount / 190)),
      paragraphs,
      visuals: [
        {
          id: `proyecto-lazaro-capitulo-${number}-imagen-1`,
          afterParagraph: Math.ceil(paragraphs.length / 2),
          alt: `Escena del capítulo ${number}, ${title}, de Proyecto Lázaro`,
          prompt: visual,
          aspectRatio: "16/9",
          status: "pending",
          url: null,
        },
      ],
    };
  },
);

export const lazarusReadingMinutes = lazarusChapters.reduce(
  (total, chapter) => total + chapter.readingMinutes,
  0,
);
